'use client';

import {useParams} from 'next/navigation';
import {useCallback,useEffect,useState} from 'react';
import HubButton from '../../../components/ui/HubButton';
import ApprovedOfferIndicator from '../../../components/rfq/ApprovedOfferIndicator';

const show=(value:unknown)=>value===null||value===undefined||value===''?'—':Array.isArray(value)?value.join(', '):String(value);
const human=(value:unknown)=>show(value).replaceAll('_',' ').replace(/\b\w/g,char=>char.toUpperCase());

export default function CustomerRfqDetailPage(){
 const {rfqId}=useParams<{rfqId:string}>(),[data,setData]=useState<any>(null),[readiness,setReadiness]=useState<any>(null),[error,setError]=useState(''),[invoiceError,setInvoiceError]=useState(''),[invoiceSuccess,setInvoiceSuccess]=useState<any>(null),[busy,setBusy]=useState(''),[offerModal,setOfferModal]=useState<{offer:any;item:any}|null>(null),[confirmOffer,setConfirmOffer]=useState<{offer:any;item:any}|null>(null),[offerList,setOfferList]=useState<{offers:any[];item:any}|null>(null),[invoiceModal,setInvoiceModal]=useState(false);
 const load=useCallback(async()=>{const [a,b]=await Promise.all([fetch(`/api/customer/rfqs/${rfqId}`,{cache:'no-store'}),fetch(`/api/customer/rfqs/${rfqId}/invoice-readiness`,{cache:'no-store'})]);const details=await a.json().catch(()=>({})),ready=await b.json().catch(()=>null);if(!a.ok)throw new Error(details.error||'RFQ could not be loaded.');setData(details);setReadiness(b.ok?ready:null)},[rfqId]);
 useEffect(()=>{load().catch(reason=>setError(reason instanceof Error?reason.message:'RFQ could not be loaded.'))},[load]);
 useEffect(()=>{if(!offerModal&&!offerList&&!confirmOffer&&!invoiceModal)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous}},[offerModal,offerList,confirmOffer,invoiceModal]);
 if(error&&!data)return <main className="min-h-screen bg-slate-950 p-8 text-white"><p>{error}</p></main>;if(!data)return <main className="min-h-screen bg-slate-950 p-8 text-white">Loading RFQ…</main>;
 const openOffer=(offer:any,item:any)=>setOfferModal({offer,item});
 const approve=async()=>{if(!confirmOffer)return;setBusy('approve');setError('');try{const response=await fetch(`/api/customer/rfqs/${rfqId}/offers/${confirmOffer.offer.offerPositionId}/approve`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({rfqItemId:confirmOffer.item.rfq_item_id})}),result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'Offer approval failed.');setConfirmOffer(null);setOfferModal(null);await load()}catch(reason){setError(reason instanceof Error?reason.message:'Offer approval failed.')}finally{setBusy('')}};
 const createInvoice=async()=>{if(busy==='invoice')return;setBusy('invoice');setInvoiceError('');setInvoiceSuccess(null);try{const response=await fetch(`/api/customer/rfqs/${rfqId}/create-invoice`,{method:'POST'}),result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'Invoice could not be created.');if(!result.invoice?.id)throw new Error('Invoice could not be created: the server returned no canonical Invoice ID.');setInvoiceModal(false);setInvoiceSuccess({invoice:result.invoice,emailDelivery:result.emailDelivery});window.dispatchEvent(new CustomEvent('invoice-created',{detail:result.invoice}));await load()}catch(reason){setInvoiceError(reason instanceof Error?reason.message:'Invoice could not be created.')}finally{setBusy('')}};
 return <main className="min-h-screen bg-gradient-to-br from-slate-950 via-blue-950 to-slate-900 px-3 py-5 sm:px-4 sm:py-8"><div className="mx-auto max-w-[1500px] space-y-6">
  <header className="sticky top-[154px] z-30 rounded-2xl bg-blue-950 p-4 text-white shadow-xl sm:top-[142px] lg:top-[106px]"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-cyan-300">Electron Market Customer</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">{data.rfq.procurementNumber}</h1><p className="mt-1 text-sm text-blue-100">{data.rfq.currentStageLabel||human(data.rfq.status)}</p></div><div className="flex flex-wrap gap-2"><HubButton href="/customer/dashboard">Back to Dashboard</HubButton>{String(data.rfq.status).toLowerCase()==='draft'&&<HubButton href={`/create-request?rfq=${rfqId}&mode=edit`}>Edit Draft</HubButton>}</div></div></header>
  {error&&<div className="rounded-lg bg-red-50 p-3 text-red-700">{error}</div>}
  {invoiceSuccess&&<div className="rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-emerald-800"><p className="font-bold">{invoiceSuccess.emailDelivery?.status==='sent'?`Invoice ${invoiceSuccess.invoice.invoiceNumber} was created and a test email was sent to the Buyer.`:invoiceSuccess.emailDelivery?.error==='buyer_email_missing'?`Invoice ${invoiceSuccess.invoice.invoiceNumber||invoiceSuccess.invoice.procurementNumber} was created, but no Buyer email is configured.`:`Invoice ${invoiceSuccess.invoice.invoiceNumber||invoiceSuccess.invoice.procurementNumber} was created, but the test email could not be delivered. The Invoice remains available.`}</p><div className="mt-3 flex gap-2"><a href="/customer/dashboard#customer-invoices" className="rounded-lg bg-blue-700 px-4 py-2 font-bold text-white">View Invoice</a><button type="button" onClick={()=>setInvoiceSuccess(null)} className="rounded-lg border border-emerald-400 px-4 py-2 font-bold">Back to RFQ</button></div></div>}
  <Section title="RFQ Positions and Supplier Offers"><div className="overflow-x-auto rounded-xl border border-slate-200"><table className="w-[1380px] table-fixed text-left text-xs"><colgroup>{[50,170,230,110,120,95,140,155,155,155].map((width,index)=><col key={index} style={{width}}/>)}</colgroup><thead className="bg-slate-900 text-white"><tr>{['№','Part Num','Name','Requested pcs','Requested price','Responses','Approved','Offer 1','Offer 2','Offer 3'].map(label=><th key={label} className="px-3 py-3 font-bold uppercase tracking-wide">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100 bg-white">{data.items.map((item:any,index:number)=>{const offers=item.offers??[],approvedIndex=offers.findIndex((offer:any)=>offer.approved),approved=approvedIndex>=0?offers[approvedIndex]:null;return <tr key={item.rfq_item_id} className="align-top hover:bg-slate-50"><td className="px-3 py-3 font-bold">{show(item.bom_row??item.line_number??index+1)}</td><td className="px-3 py-3 font-semibold text-blue-950">{show(item.part_number)}</td><td className="px-3 py-3"><span className="block truncate" title={item.description||''}>{show(item.description)}</span></td><td className="px-3 py-3">{show(item.requested_quantity)} {show(item.quantity_unit)}</td><td className="px-3 py-3">{item.target_unit_price!=null?`${show(item.currency)} ${show(item.target_unit_price)}`:'—'}</td><td className="px-3 py-3"><ResponseBadge count={offers.length}/><div className="mt-1 text-[10px] text-slate-600">{safeCoverage(item,offers)}</div>{offers.length>3&&<button type="button" onClick={()=>setOfferList({offers,item})} className="mt-1 font-bold text-blue-700 underline">+{offers.length-3} more</button>}</td><td className="px-2 py-3 text-center">{approved?<ApprovedOfferIndicator detail={`Offer ${approvedIndex+1}`}/>:<span className="text-slate-400">—</span>}</td>{[0,1,2].map(slot=><td key={slot} className="px-2 py-2"><OfferCell offer={offers[slot]} empty={slot===0?'No offer yet':'—'} partNumber={item.part_number} onOpen={()=>openOffer(offers[slot],item)}/></td>)}</tr>})}</tbody></table></div></Section>
  {(data.unmatchedOffers??[]).length>0&&<Section title="Unmatched or Review Required Information"><p className="mb-3 text-sm text-slate-600">These supplier positions are still under review and are not yet connected to an RFQ line.</p><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.unmatchedOffers.map((offer:any)=><button key={offer.offerPositionId} type="button" onClick={()=>openOffer(offer,null)} className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-left shadow-sm hover:border-amber-400"><div className="font-bold text-slate-950">{offer.supplierAlias}</div><div className="mt-1 truncate text-sm">{show(offer.offeredMpn)}</div><div className="mt-2 text-xs text-amber-800">Review in progress · View details</div></button>)}</div></Section>}
  <Section title="RFQ Summary"><Grid rows={[["Procurement number",data.rfq.procurementNumber],["Status",human(data.rfq.status)],["Current stage",data.rfq.currentStageLabel],["Source BOM",data.bom?.fileName],["Created",data.rfq.createdAt],["Required delivery",data.rfq.requiredDeliveryDate],["Customer reference",data.rfq.customerReference],["Supplier offers",`${data.offerSummary.positionCount} positions from ${data.offerSummary.supplierCount} supplier(s)`]]}/></Section>
  <Section title="Order Preferences"><Grid rows={[["Priority",human(data.preferences?.search_priority)],["Maximum lead time",data.preferences?.max_lead_time_days?`${data.preferences.max_lead_time_days} days`:'No maximum'],["Allowed countries",data.preferences?.supplier_countries],["Independent suppliers",data.preferences?.allow_independent_suppliers?'Allowed':'Not allowed'],["Alternative parts",data.preferences?.allow_alternatives?'Allowed':'Not allowed'],["Split delivery",data.preferences?.allow_split_delivery?'Allowed':'Not allowed'],["Budget",data.preferences?.budget_amount!=null?`${data.preferences.budget_amount} ${data.preferences.budget_currency||''}`:'No maximum'],["Certificates",data.preferences?.certificate_requirements]]}/></Section>
  <Section title="Invoice Actions"><p className="text-sm text-slate-600">{readiness?.ready?`${readiness.approvedPositions} approved position${readiness.approvedPositions===1?' is':'s are'} ready for Invoice.`:'Approve at least one Invoice-eligible supplier offer to create an Invoice.'}</p>{readiness?.blockers?.length>0&&<ul className="mt-3 list-disc pl-5 text-sm text-amber-800">{readiness.blockers.map((blocker:any)=><li key={`${blocker.code}-${blocker.offerItemId??''}`}>{blocker.message}</li>)}</ul>}<button type="button" disabled={!readiness?.ready} onClick={()=>setInvoiceModal(true)} className="mt-4 rounded-xl bg-emerald-700 px-4 py-2.5 font-bold text-white shadow-lg disabled:cursor-not-allowed disabled:opacity-50">Create Invoice from Approved Positions</button></Section>
  {offerModal&&<ApprovalOfferModal offer={offerModal.offer} item={offerModal.item} onClose={()=>setOfferModal(null)} onApprove={()=>setConfirmOffer(offerModal)}/>} 
  {offerList&&<Modal title={`All ${offerList.offers.length} offers`} onClose={()=>setOfferList(null)}><div className="space-y-2">{offerList.offers.map((offer:any,index:number)=><button key={offer.offerPositionId} type="button" onClick={()=>{setOfferList(null);openOffer(offer,offerList.item)}} className={`flex w-full items-center justify-between rounded-lg border p-3 text-left hover:bg-blue-50 ${offer.approved?'border-emerald-400 bg-emerald-50':'border-slate-200'}`}><span className="font-bold">Offer {index+1} · {offer.supplierAlias}</span><span className="flex items-center gap-2">{offer.approved&&<ApprovedOfferIndicator/>}{safePrice(offer)}</span></button>)}</div></Modal>}
  {confirmOffer&&<ApprovalConfirmation offer={confirmOffer.offer} item={confirmOffer.item} busy={busy==='approve'} onCancel={()=>setConfirmOffer(null)} onConfirm={approve}/>} 
  {invoiceModal&&<InvoiceConfirmation data={data} readiness={readiness} busy={busy==='invoice'} onCancel={()=>{if(busy!=='invoice'){setInvoiceModal(false);setInvoiceError('')}}} onConfirm={createInvoice}/>} 
  {invoiceModal&&invoiceError&&<div className="fixed inset-x-4 bottom-6 z-[110] mx-auto max-w-3xl rounded-xl border border-red-300 bg-red-50 p-4 text-sm font-semibold text-red-800 shadow-2xl" role="alert">{invoiceError}</div>}
 </div></main>;
}

function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl bg-white p-4 shadow-2xl sm:p-5"><h2 className="mb-4 text-xl font-bold text-blue-950">{title}</h2>{children}</section>}
function Grid({rows}:{rows:Array<[string,unknown]>}){return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{rows.map(([label,value])=><Field key={label} label={label} value={value}/>)}</div>}
function Field({label,value}:{label:string;value:unknown}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-1 break-words text-sm font-semibold text-slate-900">{show(value)}</p></div>}
function ResponseBadge({count}:{count:number}){return <span className={`inline-flex rounded-full px-2 py-1 font-bold ${count===0?'bg-slate-100 text-slate-600':count===1?'bg-blue-100 text-blue-800':'bg-emerald-100 text-emerald-800'}`}>{count} {count===1?'offer':'offers'}</span>}
function safePrice(offer:any){if(!offer)return '—';if(offer.unitPrice==null)return 'Price pending';if(!offer.currency)return 'Currency pending';return `${offer.currency} ${offer.unitPrice} / ${offer.priceBasisUnit||'unit'}`}
function safeCoverage(item:any,offers:any[]){if(!offers.length)return 'No offers';if(item.sourcingState==='Offer requires review')return 'Review required';if(offers.some(o=>o.quantityCoverageStatus==='full'))return 'Full coverage';if(offers.some(o=>o.quantityCoverageStatus==='partial'))return 'Partial coverage';return 'Quantity pending'}
function OfferCell({offer,empty,partNumber,onOpen}:{offer:any;empty:string;partNumber:string;onOpen:()=>void}){if(!offer)return <div className="py-3 text-center text-slate-400">{empty}</div>;return <button type="button" onClick={onOpen} aria-label={`Open details for ${offer.supplierAlias} offer on ${partNumber}`} className={`min-h-16 w-full cursor-pointer rounded-lg border p-2 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-blue-500 ${offer.approved?'border-emerald-400 bg-emerald-50':'border-blue-200 bg-blue-50'}`}><span className="block font-bold text-blue-950">{safePrice(offer)}</span><span className="mt-1 block truncate text-[10px] text-slate-600">{offer.supplierAlias}</span>{offer.approved&&<span className="mt-1 block text-[10px] font-bold text-emerald-700">✓ Approved · {show(offer.approvedQuantity)}</span>}{offer.matchState==='Offer requires review'&&<span className="mt-1 block text-[10px] font-bold text-amber-700">Review in progress</span>}</button>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/75 p-3" role="dialog" aria-modal="true"><div className="max-h-[92vh] w-full max-w-5xl overflow-y-auto rounded-2xl bg-white p-4 shadow-2xl sm:p-6"><div className="mb-5 flex items-center justify-between gap-3"><h2 className="text-2xl font-bold text-blue-950">{title}</h2><button type="button" onClick={onClose} className="rounded-lg border px-3 py-2 font-bold">Close</button></div>{children}</div></div>}
function CustomerOfferModal({offer,item,onClose}:{offer:any;item:any;onClose:()=>void}){const requested=item?.requested_quantity;const lineTotal=offer.unitPrice!=null&&offer.offeredQuantity!=null&&offer.priceBasisQuantity?Number(offer.unitPrice)*Number(offer.offeredQuantity)/Number(offer.priceBasisQuantity):null;const safeMatch=offer.matchState==='Matched'?'Matched product':offer.responseStatus==='alternative_proposed'?'Alternative proposed':'Review required';return <Modal title="Supplier Offer Details" onClose={onClose}><div className="space-y-5"><DetailGroup title="Product" rows={[["Supplier",offer.supplierAlias],["Requested MPN",item?.part_number],["Offered MPN",offer.offeredMpn],["Manufacturer",offer.manufacturer],["Offer status",human(offer.responseStatus)]]}/><DetailGroup title="Quantity" rows={[["Requested quantity",requested],["Offered quantity",offer.offeredQuantity],["Available quantity",offer.availableQuantity],["Covered quantity",offer.coveredQuantity],["Remaining quantity",offer.uncoveredQuantity],["Coverage",human(offer.quantityCoverageStatus)]]}/><DetailGroup title="Price" rows={[["Unit price",offer.unitPrice],["Currency",offer.currency],["Price basis",`${show(offer.priceBasisQuantity)} / ${show(offer.priceBasisUnit)}`],["Line total",lineTotal]]}/><DetailGroup title="Delivery and commercial conditions" rows={[["MOQ",offer.moq],["Lead time",offer.leadTimeDays!=null?`${offer.leadTimeDays} days`:null],["Packaging",offer.packaging],["Condition",human(offer.condition)],["Date code",offer.dateCode],["Incoterms",offer.incoterms],["Payment terms",offer.paymentTerms],["Quotation validity",offer.quotationValidUntil],["Certificates",offer.certificateAvailable==null?null:offer.certificateAvailable?'Available':'Not provided']]}/><DetailGroup title="Offer status" rows={[["Matching",safeMatch],["Commercial status",offer.unitPrice==null?'Price pending':!offer.currency?'Currency pending':'Commercial details available']]}/></div></Modal>}
function ApprovalOfferModal({offer,item,onClose,onApprove}:{offer:any;item:any;onClose:()=>void;onApprove:()=>void}){const lineTotal=offer.unitPrice!=null&&offer.offeredQuantity!=null&&offer.priceBasisQuantity?Number(offer.unitPrice)*Number(offer.offeredQuantity)/Number(offer.priceBasisQuantity):null;return <Modal title="Supplier Offer Details" onClose={onClose}><div className="space-y-5"><DetailGroup title="Product" rows={[["Supplier",offer.supplierAlias],["Requested MPN",item?.part_number],["Offered MPN",offer.offeredMpn],["Manufacturer",offer.manufacturer],["Offer status",human(offer.responseStatus)]]}/><DetailGroup title="Quantity" rows={[["Requested quantity",item?.requested_quantity],["Offered quantity",offer.offeredQuantity],["Available quantity",offer.availableQuantity],["Approved quantity",offer.approvedQuantity]]}/><DetailGroup title="Price" rows={[["Unit price",offer.unitPrice],["Currency",offer.currency],["Price basis",`${show(offer.priceBasisQuantity)} / ${show(offer.priceBasisUnit)}`],["Line total",lineTotal]]}/><DetailGroup title="Commercial conditions" rows={[["MOQ",offer.moq],["Lead time",offer.leadTimeDays!=null?`${offer.leadTimeDays} days`:null],["Packaging",offer.packaging],["Condition",human(offer.condition)],["Date code",offer.dateCode],["Certificates",offer.certificateAvailable==null?null:offer.certificateAvailable?'Available':'Not provided']]}/></div><div className="mt-6 flex justify-end gap-3">{offer.approved?<span className="rounded-lg bg-emerald-100 px-4 py-2 font-bold text-emerald-800">✓ Approved</span>:<button type="button" onClick={onApprove} className="rounded-lg bg-blue-700 px-4 py-2 font-bold text-white">Approve this offer</button>}</div></Modal>}
function ApprovalConfirmation({offer,item,busy,onCancel,onConfirm}:{offer:any;item:any;busy:boolean;onCancel:()=>void;onConfirm:()=>void}){const usable=Math.min(Number(item.requested_quantity??0),Number(offer.availableQuantity??offer.offeredQuantity??0));return <Modal title="Confirm Supplier Offer Approval" onClose={onCancel}><p className="mb-4 text-slate-700">Approve this supplier offer for the selected RFQ position?</p><Grid rows={[["RFQ position",item.line_number],["Requested MPN",item.part_number],["Requested quantity",item.requested_quantity],["Supplier",offer.supplierAlias],["Offered MPN",offer.offeredMpn],["Offered quantity",offer.offeredQuantity],["Available quantity",offer.availableQuantity],["Approved quantity",usable],["Unit price",offer.unitPrice],["Currency",offer.currency],["Price basis",`${show(offer.priceBasisQuantity)} / ${show(offer.priceBasisUnit)}`],["Lead time",offer.leadTimeDays!=null?`${offer.leadTimeDays} days`:null],["MOQ",offer.moq]]}/><p className="mt-4 rounded-lg bg-blue-50 p-3 text-sm text-blue-900">This approved position will become eligible for inclusion in the next Draft Invoice. Other RFQ positions will remain open until separately approved.</p><div className="mt-6 flex justify-end gap-3"><button onClick={onCancel} disabled={busy} className="rounded-lg border px-4 py-2">Cancel</button><button onClick={onConfirm} disabled={busy} className="rounded-lg bg-blue-700 px-4 py-2 font-bold text-white disabled:opacity-60">{busy?'Approving…':'Confirm approval'}</button></div></Modal>}
function InvoiceConfirmation({data,readiness,busy,onCancel,onConfirm}:{data:any;readiness:any;busy:boolean;onCancel:()=>void;onConfirm:()=>void}){const approved=(data.items??[]).flatMap((item:any)=>(item.offers??[]).filter((offer:any)=>offer.approved).map((offer:any)=>({item,offer})));const subtotals=new Map<string,number>();for(const {offer} of approved){const total=Number(offer.unitPrice??0)*Number(offer.approvedQuantity??0)/Number(offer.priceBasisQuantity??1);subtotals.set(offer.currency,(subtotals.get(offer.currency)??0)+total)}return <Modal title="Create Draft Invoice" onClose={onCancel}><Grid rows={[["Procurement number",data.rfq.procurementNumber],["Total RFQ positions",data.items.length],["Approved positions",readiness?.approvedPositions??0],["Unapproved positions remaining",data.items.length-(readiness?.approvedPositions??0)],["Invoice subtotal",[...subtotals].map(([currency,total])=>`${currency} ${total.toFixed(2)}`).join(', ')]]}/><div className="mt-4 space-y-2">{approved.map(({item,offer}:any)=><div key={offer.offerPositionId} className="rounded-lg border p-3 text-sm"><b>{item.part_number}</b> · {offer.supplierAlias} · {offer.approvedQuantity} · {safePrice(offer)}</div>)}</div><p className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Only approved positions will be included in this Draft Invoice. All other RFQ positions will remain open.</p><div className="mt-6 flex justify-end gap-3"><button onClick={onCancel} disabled={busy} className="rounded-lg border px-4 py-2">Cancel</button><button onClick={onConfirm} disabled={busy} className="rounded-lg bg-emerald-700 px-4 py-2 font-bold text-white disabled:opacity-60">{busy?'Creating…':'Create Draft Invoice'}</button></div></Modal>}
function DetailGroup({title,rows}:{title:string;rows:Array<[string,unknown]>}){return <section><h3 className="mb-2 font-bold text-blue-950">{title}</h3><Grid rows={rows}/></section>}
