import { NextResponse } from 'next/server';
import { requireInternalApi } from '../../../../../lib/auth/require-internal-api';

const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const fail=(error:string,message:string,status:number)=>NextResponse.json({error,message},{status});
const text=(value:unknown)=>typeof value==='string'&&value.trim()?value.trim():null;
const safeHtmlText=(value:string|null)=>value?value
  .replace(/<(script|style|iframe|object|embed|svg|form)[\s\S]*?<\/\1\s*>/gi,' ')
  .replace(/<img\b[^>]*>/gi,' ')
  .replace(/<\s*br\s*\/?>/gi,'\n')
  .replace(/<\/(p|div|li|tr|h[1-6])\s*>/gi,'\n')
  .replace(/<[^>]+>/g,' ')
  .replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'")
  .replace(/[ \t]+/g,' ').replace(/\n\s*\n\s*\n+/g,'\n\n').trim().slice(0,200000):null;
const tableRows=(value:unknown):number=>Array.isArray(value)?value.reduce((sum,row)=>sum+(Array.isArray(row)?row.length:row&&typeof row==='object'?1:0),0):value&&typeof value==='object'?Object.values(value).reduce((sum,row)=>sum+tableRows(row),0):0;
const event=(label:string,at:unknown,status?:string|null)=>at?{label,at,status:status??null}:null;

export async function GET(_:Request,{params}:{params:Promise<{messageId:string}>}){
 const auth=await requireInternalApi();if('error'in auth)return fail(auth.status===401?'authentication_required':'authorization_required',auth.error,auth.status);
 const id=decodeURIComponent((await params).messageId).trim();if(!uuid.test(id))return fail('invalid_message_id','Invalid message ID.',400);
 const message=await auth.admin.from('supplier_inbound_messages').select('id,procurement_chain_id,rfq_id,supplier_id,provider,provider_message_id,internet_message_id,in_reply_to_message_id,thread_reference,sender_email,recipient_email,subject,body_text,body_html,detected_procurement_number,procurement_identification_method,procurement_identification_confidence,rfq_identification_method,rfq_identification_confidence,supplier_identification_method,supplier_identification_confidence,sender_authorization_status,received_at,processing_status,processing_attempts,processing_error,raw_email_storage_path,created_at,updated_at').eq('id',id).maybeSingle();
 if(message.error){console.error('[supplier-inbox-detail-message]',message.error.message);return fail('message_load_failed','Message could not be loaded.',500)}if(!message.data)return fail('message_not_found','Message was not found.',404);
 const [runs,responses,items,attachments,reviews]=await Promise.all([
  auth.admin.from('supplier_message_parse_runs').select('id,parser_version,model_name,status,extracted_payload,validated_payload,extraction_confidence,validation_error,started_at,completed_at,created_at').eq('message_id',id).order('created_at',{ascending:false}).limit(10),
  auth.admin.from('supplier_responses').select('id,response_type,response_relationship,response_revision,status,default_currency,quote_valid_until_raw,quote_valid_until,remaining_items_status,explicitly_offered_item_count,partial_item_count,explicitly_unavailable_item_count,review_item_count,overall_parse_confidence,needs_review,created_at,updated_at').eq('source_message_id',id).limit(2),
  auth.admin.from('supplier_response_items').select('id,supplier_response_id,source_attachment_id,source_sheet_name,source_row_number,source_page_number,requested_mpn,requested_manufacturer,requested_quantity,response_status,offered_mpn,offered_manufacturer,offered_quantity,available_quantity,price_raw,price_amount,price_basis_quantity,price_basis_unit,calculated_unit_price,currency,moq,lead_time_raw,lead_time_days,stock_confirmed,condition,supplier_note_private,extraction_confidence,matching_confidence,match_method,normalization_status,review_status,bom_item_id,rfq_item_id,created_at').eq('source_message_id',id).order('source_row_number').limit(500),
  auth.admin.from('supplier_message_attachments').select('id,original_file_name,sanitized_display_name,mime_type,file_size_bytes,attachment_type,extraction_status,extracted_table_json,extraction_error,created_at').eq('message_id',id).order('created_at').limit(100),
  auth.admin.from('supplier_response_match_reviews').select('id,supplier_response_item_id,review_type,status,reason,extraction_confidence,matching_confidence,resolution_note,reviewed_at,created_at').eq('message_id',id).order('created_at').limit(500),
 ]);
 for(const [name,result] of Object.entries({runs,responses,items,attachments,reviews}))if(result.error){console.error(`[supplier-inbox-detail-${name}]`,result.error.message);return fail('message_detail_load_failed','Message details could not be loaded.',500)}
 const row=message.data,latestRun=runs.data?.[0]??null,response=responses.data?.[0]??null,payload=latestRun?.validated_payload??latestRun?.extracted_payload??null;
 const bomIds=[...new Set((items.data??[]).map((item:any)=>item.bom_item_id).filter(Boolean))];
 const [chain,rfq,profile,bom]=await Promise.all([
  row.procurement_chain_id?auth.admin.from('procurement_chains').select('id,procurement_number,current_stage,current_stage_label,status').eq('id',row.procurement_chain_id).maybeSingle():Promise.resolve({data:null,error:null}),
  row.rfq_id?auth.admin.from('rfq_orders0').select('rfq_id,order_number,rfq_status,priority_status,deadline_at').eq('rfq_id',row.rfq_id).maybeSingle():Promise.resolve({data:null,error:null}),
  row.supplier_id?auth.admin.from('user_profiles').select('id,email,company_name,full_name,role').eq('id',row.supplier_id).maybeSingle():Promise.resolve({data:null,error:null}),
  bomIds.length?auth.admin.from('customer_bom_upload_items').select('id,row_number,part_number,manufacturer,manufacturer_part_number,quantity').in('id',bomIds):Promise.resolve({data:[],error:null}),
 ]);
 for(const result of [chain,rfq,profile,bom])if(result.error){console.error('[supplier-inbox-detail-linked]',result.error.message);return fail('linked_record_load_failed','Linked records could not be loaded.',500)}
 const bomMap=new Map((bom.data??[]).map((item:any)=>[item.id,item])),reviewMap=new Map<string,any[]>();for(const review of reviews.data??[]){if(!review.supplier_response_item_id)continue;reviewMap.set(review.supplier_response_item_id,[...(reviewMap.get(review.supplier_response_item_id)??[]),review])}
 const extractedItems=(items.data??[]).map((item:any)=>({id:item.id,row:item.source_row_number,sourceSheet:item.source_sheet_name,sourcePage:item.source_page_number,matchedItem:bomMap.get(item.bom_item_id)??null,customerPartNumber:item.requested_mpn,supplierPartNumber:item.offered_mpn,manufacturer:item.offered_manufacturer??item.requested_manufacturer,requestedQuantity:item.requested_quantity,responseStatus:item.response_status,offeredQuantity:item.offered_quantity,availableQuantity:item.available_quantity,priceRaw:item.price_raw,unitPrice:item.calculated_unit_price??item.price_amount,currency:item.currency,priceBasisQuantity:item.price_basis_quantity,priceBasisUnit:item.price_basis_unit,moq:item.moq,leadTime:item.lead_time_raw,leadTimeDays:item.lead_time_days,stockConfirmed:item.stock_confirmed,condition:item.condition,comment:item.supplier_note_private,extractionConfidence:item.extraction_confidence,matchingConfidence:item.matching_confidence,matchMethod:item.match_method,normalizationStatus:item.normalization_status,reviewStatus:item.review_status,reviews:reviewMap.get(item.id)??[]}));
 const missing:string[]=[];if(response&&!response.default_currency&&extractedItems.some((item:any)=>item.unitPrice!=null))missing.push('Currency is missing for one or more prices.');if(extractedItems.some((item:any)=>item.unitPrice==null&&item.responseStatus==='offered'))missing.push('Price is missing for one or more offered positions.');if(extractedItems.some((item:any)=>!item.leadTime&&item.responseStatus==='offered'))missing.push('Lead time is missing for one or more offered positions.');
 const risks=[...new Set([text(latestRun?.validation_error),text(row.processing_error),...(reviews.data??[]).filter((review:any)=>review.status==='pending').map((review:any)=>review.reason)].filter(Boolean))];
 const prices=extractedItems.filter((item:any)=>item.unitPrice!=null).slice(0,8).map((item:any)=>({partNumber:item.supplierPartNumber??item.customerPartNumber,amount:item.unitPrice,currency:item.currency}));
 const summary=payload?{summary:text(payload.supplierGeneralMessage)??`${extractedItems.length} commercial position${extractedItems.length===1?' was':'s were'} extracted from the supplier response.`,responseType:payload.responseType??response?.response_type??null,responseRelationship:payload.responseRelationship??response?.response_relationship??null,defaultCurrency:payload.defaultCurrency??response?.default_currency??null,quoteValidUntil:payload.quoteValidUntilNormalized??payload.quoteValidUntilRaw??response?.quote_valid_until??response?.quote_valid_until_raw??null,remainingItemsStatus:payload.remainingItemsStatus??response?.remaining_items_status??null,positionCount:extractedItems.length,availablePositionCount:extractedItems.filter((item:any)=>item.responseStatus==='offered'||item.responseStatus==='partial_quantity').length,prices,missingInformation:missing,risks,recommendedAction:risks.length||response?.needs_review?'Review flagged positions and resolve ambiguities before validating the response.':'Validate the parsed supplier response and continue commercial comparison.',createdAt:latestRun?.completed_at??latestRun?.created_at,modelLabel:latestRun?.model_name??null}:null;
 const processingHistory=[event('Email received',row.received_at,row.processing_status),event('Message stored',row.created_at),...((attachments.data??[]).map((attachment:any)=>event(`Attachment stored: ${attachment.sanitized_display_name||attachment.original_file_name}`,attachment.created_at,attachment.extraction_status))),...((runs.data??[]).flatMap((run:any)=>[event('AI parsing started',run.started_at,run.status),event('AI parsing completed',run.completed_at,run.status)])),...((reviews.data??[]).flatMap((review:any)=>[event(`Review required: ${review.review_type}`,review.created_at,review.status),event(`Review completed: ${review.review_type}`,review.reviewed_at,review.status)]))].filter(Boolean).sort((a:any,b:any)=>new Date(a.at).getTime()-new Date(b.at).getTime());
 const pendingTypes=new Set((reviews.data??[]).filter((review:any)=>review.status==='pending').map((review:any)=>review.review_type));
 const states={senderAuthorization:row.sender_authorization_status==='authorized'?'Authorized':pendingTypes.has('sender_identity_ambiguous')?'Ambiguous':row.sender_authorization_status==='quarantined'?'Unauthorized':'Pending',procurementMatching:row.procurement_chain_id&&row.detected_procurement_number?`Matched to ${row.detected_procurement_number}`:pendingTypes.has('procurement_chain_not_found')?'Procurement not found':pendingTypes.has('procurement_number_missing')?'Number missing':'Review required',rfqAssignment:row.rfq_id?(row.processing_error==='awaiting_rfq_completion'?'Awaiting RFQ completion':'Linked'):row.processing_error==='awaiting_rfq_creation'?'Awaiting RFQ creation':'Assignment required',aiProcessing:row.processing_status==='parsed'?'Parsed':row.processing_status==='needs_review'?'Review required':row.processing_status==='failed'?'Failed':row.processing_status==='processing'?'Processing':'Received'};
 return NextResponse.json({email:{id:row.id,from:row.sender_email,to:row.recipient_email,cc:null,subject:row.subject,receivedAt:row.received_at,provider:row.provider,providerMessageId:row.provider_message_id,internetMessageId:row.internet_message_id,plainTextBody:row.body_text,htmlPreviewText:safeHtmlText(row.body_html),hasRawSource:Boolean(row.raw_email_storage_path),procurementNumber:row.detected_procurement_number,identification:{procurementMethod:row.procurement_identification_method,procurementConfidence:row.procurement_identification_confidence,rfqMethod:row.rfq_identification_method,rfqConfidence:row.rfq_identification_confidence,supplierMethod:row.supplier_identification_method,supplierConfidence:row.supplier_identification_confidence,senderAuthorizationStatus:row.sender_authorization_status},processingStatus:row.processing_status,processingAttempts:row.processing_attempts,processingError:row.processing_error,reviewStatus:(reviews.data??[]).some((review:any)=>review.status==='pending')?'required':response?.status??'not_required'},states,aiSummary:summary,aiAnalysis:{parseStatus:latestRun?.status??null,parserVersion:latestRun?.parser_version??null,extractionConfidence:latestRun?.extraction_confidence??response?.overall_parse_confidence??null,warnings:risks,missingInformation:missing},linkedRecords:{procurementChain:chain.data,rfq:rfq.data,supplier:profile.data},response,extractedItems,attachments:(attachments.data??[]).map((attachment:any)=>({id:attachment.id,fileName:attachment.sanitized_display_name||attachment.original_file_name,mimeType:attachment.mime_type,sizeBytes:attachment.file_size_bytes,type:attachment.attachment_type,extractionStatus:attachment.extraction_status,processingError:attachment.extraction_error,extractedRowCount:tableRows(attachment.extracted_table_json),downloadUrl:`/api/admin/supplier-inbox/files/attachment/${attachment.id}`})),reviews:reviews.data??[],processingHistory,actions:{rawDownloadUrl:row.raw_email_storage_path?`/api/admin/supplier-inbox/files/raw/${row.id}`:null,procurementUrl:row.rfq_id?`/admin/rfqs/${row.rfq_id}`:row.procurement_chain_id?`/admin/procurement-progress/${row.procurement_chain_id}`:null}} ,{headers:{'cache-control':'private, no-store'}});
}
