import {NextResponse} from 'next/server';
import {requireInternalApi} from '../../../../../lib/auth/require-internal-api';
import {resolveCanonicalSupplierId} from '../../../../../lib/suppliers/canonical';

const fail=(error:string,status=400)=>NextResponse.json({error},{status});
const itemSelect='id,upload_id,row_number,part_number,manufacturer,supplier_sku,product_name,description,package_case,condition,available_quantity,moq,unit,unit_price,currency,compare_at_price,lead_time,stock_location,country_of_origin,shipping_from,incoterms,datasheet_url,product_image_url_1,warranty,notes,active,validation_status,validation_errors,import_status,created_product_id,created_at';

export async function GET(_:Request,{params}:{params:Promise<{supplierId:string}>}){
 const auth=await requireInternalApi();if('error'in auth)return fail(auth.error,auth.status);
 const inputId=(await params).supplierId;let identity;
 try{identity=await resolveCanonicalSupplierId(auth.admin,inputId)}catch(error){console.error('Supplier identity resolution failed:',error);return fail('Supplier relationship could not be resolved.',409)}
 if(!identity)return fail('Supplier relationship could not be resolved.',404);
 const {canonicalSupplierId,sourceProfileId,profile,supplier}=identity;
 const [contacts,documents,products,emails,uploads,verified]=await Promise.all([
  auth.admin.from('supplier_company_contacts').select('*').eq('profile_id',sourceProfileId).order('contact_index'),
  auth.admin.from('supplier_company_documents').select('document_id,document_slot,document_type,document_title,file_name,file_mime_type,file_size_bytes,storage_bucket,storage_path,document_status,uploaded_at,created_at').eq('profile_id',sourceProfileId).order('document_slot'),
  auth.admin.from('products').select('product_id,product_name,brand_manufacturer,part_number_mpn,category,product_type,short_description,main_image_url,moq_quantity,lead_time,availability,condition,product_status,review_status,is_public,public_sort_order,review_reason,reviewed_at,source_upload_id,source_upload_item_id,source_row_number,source_file_name').eq('supplier_id',canonicalSupplierId).order('created_date',{ascending:false}),
  auth.admin.from('supplier_contact_emails').select('id,contact_id,email,email_type,is_active,is_verified,consented,can_send_quotes,updated_at').eq('source_profile_id',sourceProfileId).order('created_at'),
  auth.admin.from('supplier_stock_uploads').select('id,upload_number,document_name,original_file_name,file_url,file_type,supplier_company_name,uploaded_by_user_id,total_rows,valid_rows,error_rows,status,ai_processing_status,ai_processing_error,column_mapping_status,column_mapping,created_at').eq('supplier_id',canonicalSupplierId).order('created_at',{ascending:false}),
  auth.admin.from('verified_supplier').select('supplier_id,canonical_supplier_id,public_slug,name,pic,public_display_name,public_short_description,public_detailed_description,public_country,public_city,public_supplier_type,public_brands,public_categories,cover_image_url,public_website_url,regions_served,delivery_countries,preferred_currencies,employee_count,supported_languages,minimum_order_value,minimum_order_currency,typical_lead_time_min_days,typical_lead_time_max_days,response_time_hours,public_incoterms,public_payment_terms,manufacturing_capabilities,engineering_capabilities,testing_capabilities,quality_control_capabilities,custom_sourcing_capabilities,additional_capabilities,show_on_homepage,show_public_website,is_public,is_active,homepage_sort_order,public_directory_sort_order,has_pending_public_changes,public_profile_updated_at').eq('canonical_supplier_id',canonicalSupplierId).maybeSingle(),
 ]);
 for(const result of[contacts,documents,products,emails,uploads,verified])if(result.error){console.error('Supplier review query failed:',result.error);return fail('Supplier review data could not be loaded.',500)}
 const uploadIds=(uploads.data??[]).map((row:any)=>row.id);const items=uploadIds.length?await auth.admin.from('supplier_stock_upload_items').select(itemSelect).in('upload_id',uploadIds).order('row_number'):{data:[],error:null};
 if(items.error){console.error('Supplier uploaded rows query failed:',items.error);return fail('Uploaded product rows could not be loaded.',500)}
 const audit=await auth.admin.from('supplier_verification_audit_log').select('id,action,reason,previous_values,new_values,performed_by,created_at').eq('profile_id',sourceProfileId).order('created_at',{ascending:false}).limit(100);
 if(audit.error)console.error('Optional supplier audit history failed:',audit.error);
 const linkedContactIds=new Set((emails.data??[]).map((row:any)=>row.contact_id).filter(Boolean));const realContacts=(contacts.data??[]).filter((row:any)=>linkedContactIds.has(row.contact_id)||row.is_primary||row.is_active===false||['contact_name','contact_position','department','contact_email','contact_phone','contact_whatsapp'].some(key=>String(row[key]??'').trim()));
 const uploadedRows=items.data??[],structured=products.data??[];const counts={uploadCount:(uploads.data??[]).length,uploadedRowCount:uploadedRows.length,validUploadedRowCount:uploadedRows.filter((x:any)=>x.validation_status==='valid').length,structuredProductCount:structured.length,approvedProductCount:structured.filter((x:any)=>x.review_status==='approved').length,publicProductCount:structured.filter((x:any)=>x.review_status==='approved'&&x.is_public&&x.product_status==='active').length};
 return NextResponse.json({supplier,profile,canonicalSupplierId,identity:{sourceProfileId:identity.sourceProfileId,authUserId:identity.authUserId,companyProfileId:identity.companyProfileId,inputIdType:identity.inputIdType,wasLegacyId:identity.wasLegacyId},contacts:realContacts,authorizedEmails:emails.data??[],emails:emails.data??[],documents:documents.data??[],productUploads:uploads.data??[],uploadedItems:uploadedRows,structuredProducts:structured,products:structured,verification:{status:profile.verification_status,checklist:profile.verification_checklist},publicProfile:verified.data??null,verifiedSupplier:verified.data??null,verifiedProfile:verified.data??null,auditLog:audit.data??[],audit:audit.data??[],counts});
}

export async function PATCH(request:Request,{params}:{params:Promise<{supplierId:string}>}){
 const auth=await requireInternalApi();if('error'in auth)return fail(auth.error,auth.status);let identity;
 try{identity=await resolveCanonicalSupplierId(auth.admin,(await params).supplierId)}catch{return fail('Supplier relationship could not be resolved.',409)}if(!identity)return fail('Supplier relationship could not be resolved.',404);
 const body=await request.json().catch(()=>null);if(!body)return fail('Invalid JSON body.');const allowed=['company_name','business_registration_number','tax_vat_number','country_iso2','country_name','legal_address','office_address','website','company_phone','company_email','company_description','product_categories_text','years_in_business','public_display_name','public_short_description','public_detailed_description','public_city','public_supplier_type','public_brands','public_categories','logo_url','cover_image_url','regions_served','delivery_countries','preferred_currencies','employee_count','admin_notes','verification_checklist','verification_status','decision_reason'];const update:any={};for(const key of allowed)if(Object.hasOwn(body,key))update[key]=body[key];if(['rejected','suspended','revoked','needs_update'].includes(update.verification_status)&&!String(update.decision_reason??'').trim())return fail('A decision reason is required for this status.');update.reviewed_by=auth.user.id;update.reviewed_at=new Date().toISOString();if(['approved','verified'].includes(update.verification_status)){update.verified_by=auth.user.id;update.verified_at=new Date().toISOString()}const before=identity.profile;const saved=await auth.admin.from('supplier_company_profiles').update(update).eq('profile_id',identity.sourceProfileId).select('*').single();if(saved.error){console.error('Supplier profile save failed:',saved.error);return fail('Supplier profile could not be saved.',409)}await auth.admin.from('supplier_verification_audit_log').insert({profile_id:identity.sourceProfileId,canonical_supplier_id:identity.canonicalSupplierId,action:update.verification_status?`supplier_${update.verification_status}`:'company_data_updated_by_admin',previous_values:before,new_values:saved.data,reason:update.decision_reason||null,performed_by:auth.user.id});return NextResponse.json({profile:saved.data,canonicalSupplierId:identity.canonicalSupplierId});
}
