import {NextRequest,NextResponse} from 'next/server';
import {getCurrentUserAndAdmin} from '../../../../lib/ai/config';
import {createAdminClient} from '../../../../lib/supabase/admin';
import {clarificationVariables,extractionVariables,invalidateSupplierEmailPromptConfig,promptDefaults,semanticVariables,validatePromptTemplate} from '../../../../lib/supplier-email/prompt-config';
const fail=(error:string,status=400)=>NextResponse.json({error},{status});
async function auth(){const current=await getCurrentUserAndAdmin();return{...current,admin:createAdminClient()}}
export async function GET(){const a=await auth();if(!a.isAdmin||!a.admin)return fail('Admin access required.',403);const rows=await a.admin.from('supplier_email_ai_prompt_versions').select('*').eq('configuration_key','supplier_email_processing').order('version_number',{ascending:false});if(rows.error)return fail(rows.error.message,500);const runs=await a.admin.from('supplier_inbound_messages').select('id,detected_procurement_number,supplier_id,processing_status,processing_error,updated_at').order('updated_at',{ascending:false}).limit(10);return NextResponse.json({active:rows.data?.find((r:any)=>r.status==='active')??promptDefaults,versions:rows.data??[],credentials:{openaiConfigured:Boolean(process.env.OPENAI_API_KEY),nexarConfigured:Boolean(process.env.NEXAR_CLIENT_ID&&process.env.NEXAR_CLIENT_SECRET)},variables:{extraction:extractionVariables,semantic:semanticVariables,clarification:clarificationVariables},diagnostics:runs.data??[]})}
export async function POST(request:NextRequest){
 const a=await auth();if(!a.isAdmin||!a.user||!a.admin)return fail('Admin access required.',403);const body=await request.json().catch(()=>({})),action=String(body.action||'validate'),config={...promptDefaults,...body.config};
 const validations=[validatePromptTemplate(String(config.extraction_user_template),extractionVariables,['email_body','procurement_number']),validatePromptTemplate(String(config.semantic_user_template),semanticVariables,['supplier_item_json','rfq_candidates_json']),validatePromptTemplate(String(config.clarification_user_template),clarificationVariables,['procurement_number','rfq_position','candidate_part_number','clarification_token'])],errors=validations.flatMap(v=>v.errors);
 if(action==='validate'||action==='test')return NextResponse.json({valid:!errors.length,errors,preview:action==='test'?{processingEngine:'openai_primary',extractionModel:config.extraction_model,semanticModel:config.semantic_model,clarificationModel:config.clarification_model,persisted:false,warning:'Preview mode does not create RFQ offers or send email.'}:undefined});if(errors.length)return fail(errors.join(' '));
 if(action==='activate'||action==='rollback'){const id=String(body.id||'');if(!id)return fail('Version ID is required.');const activated=await a.admin.rpc('activate_supplier_email_ai_prompt_version',{p_version_id:id,p_admin_id:a.user.id});if(activated.error)return fail(activated.error.message,500);invalidateSupplierEmailPromptConfig();return NextResponse.json({active:activated.data})}
 const latest=await a.admin.from('supplier_email_ai_prompt_versions').select('version_number').eq('configuration_key','supplier_email_processing').order('version_number',{ascending:false}).limit(1).maybeSingle();const saved=await a.admin.from('supplier_email_ai_prompt_versions').insert({...config,id:undefined,version_number:Number(latest.data?.version_number??0)+1,status:'draft',created_by:a.user.id,updated_by:a.user.id,created_at:undefined,updated_at:undefined,activated_at:null}).select('*').single();if(saved.error)return fail(saved.error.message,500);return NextResponse.json({draft:saved.data});
}
