import {NextResponse} from 'next/server';
import {requireAdminApi} from '../../../../../../../../lib/auth/require-admin-api';
import {resolveCanonicalSupplierId,isUuid} from '../../../../../../../../lib/suppliers/canonical';

export async function POST(_:Request,{params}:{params:Promise<{supplierId:string;uploadId:string}>}){
 const auth=await requireAdminApi();if('error'in auth)return NextResponse.json({error:auth.error},{status:auth.status});const p=await params;if(!isUuid(p.uploadId))return NextResponse.json({error:'Invalid upload ID.'},{status:400});
 const identity=await resolveCanonicalSupplierId(auth.admin,p.supplierId);if(!identity)return NextResponse.json({error:'Supplier relationship could not be resolved.'},{status:404});
 const upload=await auth.admin.from('supplier_stock_uploads').select('id,original_file_name').eq('id',p.uploadId).eq('supplier_id',identity.canonicalSupplierId).maybeSingle();if(!upload.data)return NextResponse.json({error:'This upload does not belong to the selected supplier.'},{status:404});
 const rows=await auth.admin.from('supplier_stock_upload_items').select('*').eq('upload_id',p.uploadId).eq('validation_status','valid').is('created_product_id',null).order('row_number');if(rows.error){console.error('Import rows query failed:',rows.error);return NextResponse.json({error:'Valid uploaded products could not be loaded.'},{status:500})}
 let imported=0;for(const row of rows.data??[]){const inserted=await auth.admin.from('products').insert({supplier_id:identity.canonicalSupplierId,product_name:row.product_name||row.part_number||row.description||`Uploaded product row ${row.row_number}`,brand_manufacturer:row.manufacturer||null,part_number_mpn:row.part_number||null,sku_internal:row.supplier_sku||null,short_description:row.description||null,packaging_details:row.package_case||null,condition:row.condition||null,stock_quantity:row.available_quantity??null,moq_quantity:row.moq??null,moq_unit:row.unit||null,base_price:row.unit_price??null,base_currency:row.currency||null,compare_at_price:row.compare_at_price??null,lead_time:row.lead_time||null,stock_location:row.stock_location||null,country_of_origin:row.country_of_origin||null,warranty:row.warranty||null,notes:row.notes||null,main_image_url:row.product_image_url_1||null,product_status:'active',is_active:true,review_status:'under_review',is_public:false,source_upload_id:p.uploadId,source_upload_item_id:row.id,source_row_number:row.row_number,source_file_name:upload.data.original_file_name}).select('product_id').single();
  if(inserted.error){console.error('Uploaded product import failed:',inserted.error);return NextResponse.json({error:'A valid product row could not be imported.'},{status:409})}
  const linked=await auth.admin.from('supplier_stock_upload_items').update({created_product_id:inserted.data.product_id,import_status:'imported'}).eq('id',row.id).is('created_product_id',null);if(linked.error){console.error('Imported product link failed:',linked.error);return NextResponse.json({error:'Imported product could not be linked to its source row.'},{status:409})}imported++;
 }
 return NextResponse.json({imported,skipped:(rows.data??[]).length-imported,message:imported?`${imported} product${imported===1?'':'s'} imported for review.`:'Products have already been imported or no valid rows are available.'});
}
