import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {parseProductIntent} from '../lib/product-finder/intent.ts';
import {normalizeNexarIntent,searchNexarProducts} from '../lib/product-finder/nexar-router.ts';
import {runProductFinder} from '../lib/product-finder/orchestrator.ts';
import {scoreCandidate} from '../lib/product-finder/scoring.ts';

const request=`I need an integrated circuit for controlling a three-phase brushless DC motor.
Supply voltage: 8–60 V
Three half-bridge gate-driver outputs
External N-channel MOSFETs
Peak gate-drive current: at least 1 A
PWM: at least 20 kHz
SPI configuration and diagnostics
Current-shunt amplifiers preferred
Protection functions
Industrial temperature
Surface-mount package`;
const specs=(values:Record<string,string>)=>Object.entries(values).map(([shortname,displayValue])=>({attribute:{shortname},displayValue}));
const part=(mpn:string,manufacturer:string,description:string,category='Gate Drivers',values:Record<string,string>={})=>({id:mpn,name:description,mpn,shortDescription:description,manufacturer:{name:manufacturer},category:{name:category},specs:specs(values),bestDatasheet:{url:`https://manufacturer.example/${mpn}.pdf`},octopartUrl:`https://octopart.com/${mpn}`});
const response=(parts:any[])=>({supSearch:{hits:parts.length,results:parts.map(value=>({part:value}))}});

test('BLDC request becomes a structured parametric motor-gate-driver intent',()=>{const intent=parseProductIntent(request),normalized=normalizeNexarIntent(intent);assert.equal(normalized.mode,'parametric');assert.equal(intent.category,'motor gate driver');assert.equal(intent.parameters.interface,'SPI');assert.equal(intent.parameters.externalMosfets,'N-channel');assert.equal(normalized.requiredSpecifications.voltageRange,'8-60 V');assert.equal(normalized.preferredSpecifications.preferredCurrentShuntAmplifiers,'Yes');assert.equal(normalized.preferredSpecifications.preferredMounting,'surface mount')});
test('parametric discovery uses one concise query and records safe counts',async()=>{const intent=parseProductIntent(request),attempts:string[]=[];const found=await searchNexarProducts(intent,{execute:async(_query,variables)=>{attempts.push(String(variables.q));return response([part('TMC6200-LA','Analog Devices / Trinamic','Three-phase BLDC gate driver for external MOSFETs with SPI','Three Phase Gate Drivers',{voltageRange:'8-60 V',gateCurrentMin:'1.4 A',interface:'SPI',halfBridges:'3',externalMosfets:'N-channel'})])}});assert.equal(found.mode,'parametric');assert.equal(found.operation,'supSearch');assert.equal(attempts.length,1);assert.match(attempts[0],/three-phase BLDC gate driver external N-channel MOSFET SPI/);assert.equal(found.diagnostics.rawResultCount,1);assert.equal(found.diagnostics.normalizedCandidateCount,1);assert.equal(found.diagnostics.nexarCalls,1);assert.equal(found.candidates[0]?.partNumber,'TMC6200-LA')});
test('missing preferred attributes do not reject a valid gate driver',()=>{const intent=parseProductIntent(request),candidate={source:'octopart' as const,sourceReference:'tmc6200',manufacturer:'Analog Devices / Trinamic',partNumber:'TMC6200-LA',productName:'Three-phase BLDC gate driver for external N-channel MOSFETs',category:'Three Phase Gate Drivers',technicalParameters:{voltageRange:'8-60 V',gateCurrentMin:'1.4 A',interface:'SPI',halfBridges:'3',externalMosfets:'N-channel'},evidenceUrls:['https://manufacturer.example/tmc6200'],evidenceTitles:[],evidenceExtracts:[],verificationStatus:'verified_from_public_source' as const},score=scoreCandidate(intent,candidate);assert.ok(score.overallScore>0);assert.ok(score.missingParameters.includes('preferredCurrentShuntAmplifiers'));assert.equal(score.categoryMatch,true)});
test('close voltage range remains visible with an explicit difference',()=>{const intent=parseProductIntent(request),candidate={source:'public_manufacturer' as const,sourceReference:'drv8353s',manufacturer:'Texas Instruments',partNumber:'DRV8353S',productName:'Three-phase smart gate driver for external N-channel MOSFETs',category:'Three Phase Gate Drivers',technicalParameters:{voltageRange:'9-100 V',gateCurrentMin:'1 A',interface:'SPI',halfBridges:'3',externalMosfets:'N-channel'},evidenceUrls:['https://manufacturer.example/drv8353s'],evidenceTitles:[],evidenceExtracts:[],verificationStatus:'verified_from_public_source' as const},score=scoreCandidate(intent,candidate);assert.ok(score.overallScore>0);assert.match(score.conflicts.join(' '),/voltageRange/)});
test('wrong-function motor controllers and integrated power stages are excluded',()=>{const intent=parseProductIntent(request);for(const candidate of [{partNumber:'MCU-MOTOR',productName:'Motor controller MCU',category:'Motor Controllers'},{partNumber:'POWER-STAGE',productName:'Integrated power stage',category:'Smart Power Stage'}]){const score=scoreCandidate(intent,{source:'octopart',sourceReference:candidate.partNumber,manufacturer:'Fixture',...candidate,technicalParameters:{},evidenceUrls:[],evidenceTitles:[],evidenceExtracts:[],verificationStatus:'partially_verified'} as any);assert.equal(score.overallScore,0);assert.match(score.conflicts[0],/category/)}});
test('public internet discovery creates Found Positions after zero Nexar results',async()=>{const intent=parseProductIntent(request),webCandidate={source:'public_manufacturer' as const,sourceReference:'https://manufacturer.example/tmc6200',manufacturer:'Analog Devices / Trinamic',partNumber:'TMC6200-LA',productName:'Three-phase BLDC gate driver for external MOSFETs',category:'Three Phase Gate Drivers',technicalParameters:{voltageRange:'8-60 V',interface:'SPI',halfBridges:'3',externalMosfets:'N-channel'},evidenceUrls:['https://manufacturer.example/tmc6200'],evidenceTitles:['Official product page'],evidenceExtracts:['Three-phase external MOSFET gate driver'],verificationStatus:'verified_from_public_source' as const};const result=await runProductFinder(intent,{searchInternalProducts:async()=>[],searchOctopartProducts:async()=>[],researchPublicProductSources:async()=>[webCandidate],discoverPotentialSuppliers:async()=>[]},{candidateFirst:true});assert.equal(result.productCandidates[0]?.partNumber,'TMC6200-LA');assert.ok(result.productCandidates[0]?.compatibility.overallScore>0);assert.doesNotMatch(result.assistantMessage,/supSearch|GraphQL|OAuth|searched/i)});
test('runtime path recognizes motor gate drivers as Nexar-covered and retains web discovery',()=>{const source=fs.readFileSync('lib/product-finder/server-tools.ts','utf8');assert.match(source,/gate\[- \]\?driver/);assert.match(source,/researchPublicProductSources/);assert.match(source,/runWebResearch\(intent,'products'/)});
