import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { validateProductSearchIntent } from '../lib/product-finder/contracts.ts';
import { normalizeNexarIntent, searchNexarProducts } from '../lib/product-finder/nexar-router.ts';
import { equivalentTechnicalValue } from '../lib/product-finder/scoring.ts';

const part=(mpn:string,category='Analog to Digital Converters',manufacturer='Analog Devices',specs:any[]=[])=>( {id:`part-${mpn}`,name:mpn,mpn,shortDescription:`${category} ${mpn}`,manufacturer:{name:manufacturer},category:{name:category},specs,bestDatasheet:{url:`https://manufacturer.example/${mpn}.pdf`},octopartUrl:`https://octopart.com/${mpn}`} );
const result=(operation:string,parts:any[])=>operation==='supMultiMatch'?{supMultiMatch:[{hits:parts.length,parts}]}:{[operation]:{hits:parts.length,results:parts.map(value=>({part:value}))}};

test('complete MPN selects supSearchMpn exact route and ranks exact result first',async()=>{const intent=validateProductSearchIntent({rawQuery:'STM32F407VGT6',partNumber:'STM32F407VGT6',category:'MCU'});let query='';const found=await searchNexarProducts(intent,{execute:async(q)=>{query=q;return result('supSearchMpn',[part('STM32F407VGT6','Microcontrollers','STMicroelectronics'),part('STM32F407VG','Microcontrollers','STMicroelectronics')])}});assert.equal(found.mode,'exact_mpn');assert.match(query,/supSearchMpn/);assert.equal(found.candidates[0]?.partNumber,'STM32F407VGT6');assert.notEqual(found.candidates[0]?.sourceReference,found.candidates[0]?.partNumber)});
test('partial MPN is a distinct mode and excludes other families',async()=>{const intent=validateProductSearchIntent({rawQuery:'Analog Devices ADS8688 series',manufacturer:'Analog Devices',partNumber:'ADS8688',category:'ADC'});const found=await searchNexarProducts(intent,{execute:async()=>result('supSearchMpn',[part('ADS8688IPW'),part('ADS8688IRT'),part('AD7606B')])});assert.equal(found.mode,'partial_mpn');assert.deepEqual(found.candidates.map(row=>row.partNumber),['ADS8688IPW','ADS8688IRT'])});
test('parametric route preserves required and preferred fields and maps Nexar specs',async()=>{const intent=validateProductSearchIntent({rawQuery:'16-bit SAR ADC, 8 channels, 1 MSPS, SPI, surface mount',category:'ADC',parameters:{resolution:'16-bit',channels:'8',sampleRate:'1 MSPS',interface:'SPI'},preferredPackage:'LQFP'});const normalized=normalizeNexarIntent(intent);assert.equal(normalized.mode,'parametric');assert.equal(normalized.requiredSpecifications.resolution,'16-bit');assert.equal(normalized.preferredSpecifications.package,'LQFP');const specs=[['resolution','16 bit'],['channels','8'],['sampleRate','1 MHz'],['interface','SPI']].map(([shortname,displayValue])=>({attribute:{shortname},displayValue}));const found=await searchNexarProducts(intent,{execute:async(q,variables)=>{assert.match(q,/supSearch\(/);assert.doesNotMatch(String(variables.q),/delivery|payment/i);return result('supSearch',[part('ADS8688IPW','ADC','Analog Devices',specs),part('STM32F407VGT6','MCU','STMicroelectronics')])}});assert.equal(found.candidates.length,1);assert.equal(found.candidates[0].partNumber,'ADS8688IPW');assert.equal(found.candidates[0].technicalParameters.sampleRate,'1 MHz')});
test('BOM rows use supMultiMatch and remain mapped to their original rows',async()=>{const intent=validateProductSearchIntent({rawQuery:'STM32F407VGT6\nADS8688IPW\nIRFP4568PBF'});let variables:any;const found=await searchNexarProducts(intent,{execute:async(q,v)=>{variables=v;assert.match(q,/supMultiMatch/);return result('supMultiMatch',[part('IRFP4568PBF','MOSFET','Infineon'),part('STM32F407VGT6','MCU','STMicroelectronics'),part('ADS8688IPW','ADC','Analog Devices')])}});assert.equal(found.mode,'bom_multi_match');assert.equal(variables.queries.length,3);assert.deepEqual(found.bomRows?.map(row=>[row.rowNumber,row.mpn,row.candidate?.partNumber]),[[1,'STM32F407VGT6','STM32F407VGT6'],[2,'ADS8688IPW','ADS8688IPW'],[3,'IRFP4568PBF','IRFP4568PBF']])});
test('duplicate BOM MPNs preserve independent rows without wrong attachment',async()=>{const intent=validateProductSearchIntent({rawQuery:'ADS8688IPW,10\nADS8688IPW,20'});const found=await searchNexarProducts(intent,{execute:async()=>result('supMultiMatch',[part('ADS8688IPW')])});assert.equal(found.bomRows?.length,2);assert.deepEqual(found.bomRows?.map(row=>row.quantity),[10,20]);assert.ok(found.bomRows?.every(row=>row.candidate?.partNumber==='ADS8688IPW'))});
test('Nexar candidates are normalized without a second web verification call',async()=>{const intent=validateProductSearchIntent({rawQuery:'ADS8688',partNumber:'ADS8688',category:'ADC'});let calls=0;const found=await searchNexarProducts(intent,{execute:async()=>{calls++;return result('supSearchMpn',[part('ADS8688IPW')])}});assert.equal(calls,1);assert.equal(found.candidates[0].partNumber,'ADS8688IPW')});
test('single response normalization preserves manufacturer and MPN',async()=>{const intent=validateProductSearchIntent({rawQuery:'ADS8688',partNumber:'ADS8688',category:'ADC'});const found=await searchNexarProducts(intent,{execute:async()=>result('supSearchMpn',[part('ADS8688IPW')])});assert.equal(found.candidates[0].manufacturer,'Analog Devices');assert.equal(found.candidates[0].partNumber,'ADS8688IPW')});
test('router exposes no offers, raw GraphQL payload, token, or credential fields',async()=>{const intent=validateProductSearchIntent({rawQuery:'ADS8688',partNumber:'ADS8688',category:'ADC'});const found=await searchNexarProducts(intent,{execute:async()=>result('supSearchMpn',[{...part('ADS8688IPW'),sellers:[{company:{name:'Private Distributor'}}],secret:'x'}])});const json=JSON.stringify(found);assert.doesNotMatch(json,/Private Distributor|sellers|secret|accessToken|clientSecret/i)});
test('browser-visible code cannot select a Nexar operation or access credentials',()=>{for(const file of['app/components/product-finder/ProductFinderPanel.tsx','app/api/product-finder/sessions/route.ts']){const source=fs.readFileSync(file,'utf8');assert.doesNotMatch(source,/NEXAR_CLIENT_(?:ID|SECRET)|supSearchMpn|supMultiMatch/)}const server=fs.readFileSync('lib/product-finder/server-tools.ts','utf8');assert.doesNotMatch(server,/researchConfiguration\.(?:clientId|clientSecret|graphql)/)});
test('authentication uses a shared OAuth refresh lock and one bounded refresh',()=>{const source=fs.readFileSync('lib/market-data/nexar.ts','utf8');assert.match(source,/tokenRefresh/);assert.match(source,/expiresAt > Date\.now\(\) \+ 60_000/);assert.match(source,/response\.status===401/);assert.match(source,/tokenCache=null/);assert.doesNotMatch(source,/process\.env\.NEXAR_ACCESS_TOKEN|manual_access_token|while\s*\(|attempt === 0/);assert.doesNotMatch(source,/Please set NEXAR_CLIENT_ID/)});
test('Nexar router contains only the four supported server-selected modes',()=>{const source=fs.readFileSync('lib/product-finder/nexar-router.ts','utf8');for(const mode of['exact_mpn','partial_mpn','parametric','bom_multi_match'])assert.match(source,new RegExp(mode));assert.doesNotMatch(source,/mode\s*:\s*intent\./)});
test('industrial niche request is retained for controlled public fallback',()=>{const source=fs.readFileSync('lib/product-finder/server-tools.ts','utf8');assert.match(source,/blade\|cutting wheel\|dicing wheel/);assert.match(source,/if\(!isNexarCategory\(intent\)\)return\[\]/);assert.match(source,/researchPublicProductSources/)});
test('technical comparison normalizes common electrical, frequency, and time units',()=>{assert.equal(equivalentTechnicalValue('1000 mV','1 V','voltage'),true);assert.equal(equivalentTechnicalValue('1000 kHz','1 MHz','frequency'),true);assert.equal(equivalentTechnicalValue('1000 ns','1 us','time'),true)});
test('parametric search performs relaxation locally after one concise category query',async()=>{const intent=validateProductSearchIntent({rawQuery:'16-bit SAR ADC 8 channels SPI',category:'ADC',intendedFunction:'SAR ADC',parameters:{resolution:'16-bit',channels:'8',interface:'SPI'}});const terms:string[]=[];const found=await searchNexarProducts(intent,{execute:async(_query,variables)=>{terms.push(String(variables.q));return result('supSearch',[part('ADS8688AIDB','ADC')])}});assert.equal(terms.length,1);assert.match(terms[0],/ADC/);assert.equal(found.diagnostics.nexarCalls,1);assert.equal(found.candidates[0]?.partNumber,'ADS8688AIDB')});
test('evaluation modules and conflicting unevidenced manufacturer identities are excluded',async()=>{const intent=validateProductSearchIntent({rawQuery:'ADS8688',partNumber:'ADS8688',category:'ADC'});const evm={...part('ADS8688EVM-PDK','Data Conversion IC Development Tools'),name:'ADS8688 evaluation module'};const found=await searchNexarProducts(intent,{execute:async()=>result('supSearchMpn',[evm,part('ADS8688AIDB','ADC')])});assert.deepEqual(found.candidates.map(row=>row.partNumber),['ADS8688AIDB']);const exact=validateProductSearchIntent({rawQuery:'STM32F429ZIT6',partNumber:'STM32F429ZIT6',category:'MCU'}),verified=part('STM32F429ZIT6','Microcontrollers','STMicroelectronics'),unsupported={...part('STM32F429ZIT6','Microcontrollers','Other Vendor'),bestDatasheet:null};const exactFound=await searchNexarProducts(exact,{execute:async()=>result('supSearchMpn',[unsupported,verified])});assert.deepEqual(exactFound.candidates.map(row=>row.manufacturer),['STMicroelectronics'])});
