import test,{afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {NexarApplicationError,NexarQuotaError,NexarSchemaError,nexarGraphqlRequest,resetNexarAuthenticationForTests} from '../lib/market-data/nexar.ts';
import {searchNexarProducts} from '../lib/product-finder/nexar-router.ts';
import {validateProductSearchIntent} from '../lib/product-finder/contracts.ts';

const originalFetch=globalThis.fetch,originalId=process.env.NEXAR_CLIENT_ID,originalSecret=process.env.NEXAR_CLIENT_SECRET;
const response=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}});
afterEach(()=>{globalThis.fetch=originalFetch;if(originalId===undefined)delete process.env.NEXAR_CLIENT_ID;else process.env.NEXAR_CLIENT_ID=originalId;if(originalSecret===undefined)delete process.env.NEXAR_CLIENT_SECRET;else process.env.NEXAR_CLIENT_SECRET=originalSecret;resetNexarAuthenticationForTests()});
const useOAuth=(payload:unknown,status=200)=>{process.env.NEXAR_CLIENT_ID='client';process.env.NEXAR_CLIENT_SECRET='secret';globalThis.fetch=async url=>String(url).includes('/connect/token')?response({access_token:'oauth-fixture-token',expires_in:3600}):response(payload,status)};

test('HTTP 200 with an application GraphQL error is not treated as product success',async()=>{useOAuth({data:{supSearchMpn:null},errors:[{message:'App fetching error: not found'}]});await assert.rejects(()=>nexarGraphqlRequest('query ExactPart { supSearchMpn(q:"X"){hits} }',{}),(error:any)=>error instanceof NexarApplicationError&&error.code==='NEXAR_APPLICATION_NOT_FOUND')});
test('minimal supSearchMpn results part identity is parsed and normalized',async()=>{const intent=validateProductSearchIntent({rawQuery:'STM32F407VGT6',partNumber:'STM32F407VGT6',category:'MCU'});const found=await searchNexarProducts(intent,{execute:async()=>({supSearchMpn:{hits:1,results:[{part:{id:'p1',name:'STM32F407VGT6',mpn:'STM32F407VGT6',manufacturer:{name:'STMicroelectronics'},category:{name:'Microcontrollers'}}}]}})});assert.equal(found.candidates[0]?.manufacturer,'STMicroelectronics');assert.equal(found.candidates[0]?.partNumber,'STM32F407VGT6')});
test('field-level error preserves usable partial GraphQL product data',async()=>{useOAuth({data:{supSearchMpn:{hits:1,results:[{part:{mpn:'STM32F407VGT6',manufacturer:{name:'STMicroelectronics'}}}]}},errors:[{message:'Optional offer field is unavailable',path:['supSearchMpn','results',0,'part','sellers']}]});const data=await nexarGraphqlRequest('query ExactPart { supSearchMpn(q:"X"){hits} }',{});assert.equal(data.supSearchMpn.results[0].part.mpn,'STM32F407VGT6')});
test('PART_LIMIT_EXCEEDED is distinct from an empty result',async()=>{useOAuth({data:null,errors:[{message:'Part limit exceeded',extensions:{code:'PART_LIMIT_EXCEEDED'}}]});await assert.rejects(()=>nexarGraphqlRequest('query ExactPart { supSearchMpn(q:"X"){hits} }',{}),NexarQuotaError);resetNexarAuthenticationForTests();useOAuth({data:{supSearchMpn:{hits:0,results:[]}}});const data=await nexarGraphqlRequest('query ExactPart { supSearchMpn(q:"X"){hits} }',{});assert.equal(data.supSearchMpn.hits,0)});
test('schema errors are distinguished from application and authorization failures',async()=>{useOAuth({data:null,errors:[{message:'Cannot query field "unsupported" on type "SupPart".'}]});await assert.rejects(()=>nexarGraphqlRequest('query Test { unsupported }',{}),NexarSchemaError);resetNexarAuthenticationForTests();useOAuth({data:null,errors:[{message:'App fetching error: not found'}]});await assert.rejects(()=>nexarGraphqlRequest('query Test { supSearchMpn(q:"X"){hits} }',{}),NexarApplicationError)});
test('exact MPN router uses limit one and one Nexar request',async()=>{const intent=validateProductSearchIntent({rawQuery:'STM32F407VGT6',partNumber:'STM32F407VGT6',category:'MCU'});let calls=0,limit=0;await searchNexarProducts(intent,{execute:async(_query,variables)=>{calls++;limit=Number(variables.limit);return{supSearchMpn:{hits:0,results:[]}}}});assert.equal(calls,1);assert.equal(limit,1)});
