import test from 'node:test';import assert from 'node:assert/strict';
import {matchSupplierProduct,normalizeSupplierMpn,summarizeMatchResults} from '../lib/supplier-email/matching.ts';
const rfq=[{id:'1',part_number:'TPS5430DDAR',manufacturer:'Texas Instruments',product_name:'Buck regulator'},{id:'2',part_number:'STM32F103C8T6',manufacturer:'ST',product_name:'Microcontroller'},{id:'3',part_number:'ESP32-WROOM-32E',manufacturer:'Espressif',product_name:'WiFi module'},{id:'4',part_number:'IRF540N',manufacturer:'Infineon',product_name:'N-channel power MOSFET',description:'100 V 33 A TO-220AB'}];
test('normalizes and exactly matches MPNs',()=>{assert.equal(normalizeSupplierMpn(' tps5430-ddar '),normalizeSupplierMpn('TPS5430 DDAR'));const value=matchSupplierProduct({offeredMpn:'TPS5430DDAR'},rfq);assert.equal(value.matchState,'matched_exact');assert.equal(value.matchedRfqItemId,'1')});
test('missing MPN can produce a semantic match or controlled review',()=>{const value=matchSupplierProduct({offeredMpn:null,originalProductName:'N-channel power MOSFET',offeredManufacturer:'Infineon',sourceReference:{sourceText:'100 V 33 A TO-220AB'},technicalParameters:[{name:'Package',value:'TO-220AB'}]},rfq);assert.ok(['matched_semantic','review_required'].includes(value.matchState));assert.ok(value.match||value.candidate)});
test('missing MPN and unknown products are valid unmatched results',()=>{for(const item of [{offeredMpn:null,originalProductName:null},{originalProductName:'Unknown quantum widget',technicalParameters:[]}]){const value=matchSupplierProduct(item,rfq);assert.equal(value.matchState,'unmatched');assert.equal(value.matchedRfqItemId,null);assert.equal(value.reviewRequired,true)}});
test('equally plausible positions are ambiguous without an arbitrary match',()=>{const choices=[{id:'a',product_name:'Ceramic capacitor 10 UF 25 V'},{id:'b',product_name:'Ceramic capacitor 10 UF 25 V'}];const value=matchSupplierProduct({originalProductName:'Ceramic capacitor 10 UF 25 V',technicalParameters:[]},choices);assert.equal(value.matchState,'ambiguous');assert.equal(value.match,null);assert.equal(value.candidateRfqItemIds.length,2)});
test('semantic matcher failures become review results and never throw',()=>{const broken:any={get part_number(){throw new Error('matcher unavailable')}};const value=matchSupplierProduct({originalProductName:'MOSFET 100 V',technicalParameters:[]},[broken]);assert.equal(value.matchState,'review_required');assert.match(value.warnings[0],/unavailable/i)});
test('mixed and all-unmatched email summaries remain successful',()=>{const exact=matchSupplierProduct({offeredMpn:'TPS5430DDAR'},rfq),unknown=matchSupplierProduct({originalProductName:'Unknown'},rfq);assert.deepEqual(summarizeMatchResults([exact,exact,exact,unknown]),{success:true,processingStatus:'parsed_with_review',extractedItems:4,matchedItems:3,reviewItems:0,ambiguousItems:0,unmatchedItems:1,technicalError:null});const all=summarizeMatchResults([unknown,unknown]);assert.equal(all.success,true);assert.equal(all.unmatchedItems,2)});
