'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { createClient } from '../../../lib/supabase/client';
type Supplier = { supplier_id: string; name: string; logo: string | null; country: string | null };
export default function OfficialSuppliersSection() {
  const [suppliers, setSuppliers] = useState<Supplier[]>([]);
  useEffect(() => { let active=true; (async()=>{ const {data}=await createClient().from('suppliers').select('supplier_id, supplier_name, company_name, logo_url, country').eq('official_authorized_distributor',true).eq('supplier_status','active').order('company_name').limit(5); if(active&&data) setSuppliers(data.map(row=>({supplier_id:row.supplier_id,name:row.company_name||row.supplier_name,logo:row.logo_url,country:row.country}))); })(); return()=>{active=false}; },[]);
  return <section className="bg-white py-8 md:py-10"><div className="mx-auto max-w-[1180px] px-4 sm:px-6 lg:px-8"><div className="mb-5"><h2 className="text-2xl font-bold tracking-tight text-slate-950">Official Suppliers and Manufacturers</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Authorized distributors and manufacturers supporting verified sourcing requests.</p></div>{suppliers.length ? <div className="homepage-mobile-horizontal-scroll category-scrollbar grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-5" role="region" aria-label="Official suppliers and manufacturers" tabIndex={0}>{suppliers.map(s=><Link href={`/suppliers/${encodeURIComponent(s.supplier_id)}`} key={s.supplier_id} className="homepage-mobile-horizontal-card flex min-h-[150px] flex-col rounded-lg border border-slate-200 bg-white p-4 shadow-sm hover:border-blue-200 hover:shadow-md"><div className="flex h-10 w-10 items-center justify-center overflow-hidden rounded-lg bg-blue-50 text-sm font-bold text-blue-700">{s.logo?<img src={s.logo} alt="" className="h-8 w-8 object-contain"/>:s.name.slice(0,2).toUpperCase()}</div><h3 className="mt-3 text-sm font-bold text-slate-950">{s.name}</h3>{s.country&&<p className="mt-1 text-xs text-slate-500">{s.country}</p>}</Link>)}</div>:<p className="rounded-xl border border-dashed border-slate-300 p-6 text-sm text-slate-500">No official suppliers are currently available.</p>}</div></section>;
}
