'use client';
import { useMemo, useState } from 'react';
import DocumentConversionModal, { ConversionSuccess } from './DocumentConversionModal';

type Item = { id:string; row_number?:number|null; part_number?:string|null; normalized_part_number?:string|null; manufacturer_part_number?:string|null; manufacturer?:string|null; product_name?:string|null; description?:string|null; quantity?:number|null; unit?:string|null; target_unit_price?:number|null; target_currency?:string|null; notes?:string|null; validation_status?:string|null; part_number_check_status?:string|null };
export default function BomRfqReviewModal({open,upload,items,onClose,onSave}:{open:boolean;upload:any;items:Item[];onClose:()=>void;onSave:(reviewedValues:any)=>Promise<any>}){
 const initial=useMemo(()=>({customer_reference:upload?.customer_reference??'',destination_country:upload?.destination_country??'',required_delivery_date:String(upload?.required_delivery_date??'').slice(0,10),currency:upload?.budget_currency??'USD',notes:upload?.notes??'',items:items.map(x=>({source_bom_item_id:x.id,part_number:x.manufacturer_part_number||x.normalized_part_number||x.part_number||'',manufacturer:x.manufacturer||'',description:x.description||x.product_name||'',requested_quantity:String(x.quantity??''),unit:x.unit||'pcs',target_unit_price:x.target_unit_price==null?'':String(x.target_unit_price),currency:x.target_currency||upload?.budget_currency||'USD',required_date:String(upload?.required_delivery_date??'').slice(0,10),notes:x.notes||''}))}),[upload,items]);
 const[draft,setDraft]=useState(initial),[pending,setPending]=useState(false),[errors,setErrors]=useState<string[]>([]),[success,setSuccess]=useState<ConversionSuccess|null>(null);
 const dirty=JSON.stringify(draft)!==JSON.stringify(initial);const reset=()=>setDraft(initial);
 const save=async()=>{const next:string[]=[];draft.items.forEach((x,i)=>{if(!x.part_number.trim())next.push(`Position ${i+1}: Part Number is required.`);if(!/^\d+(?:\.\d+)?$/.test(x.requested_quantity)||Number(x.requested_quantity)<=0)next.push(`Position ${i+1}: Quantity must be greater than zero.`);if(x.target_unit_price&&(!/^\d+(?:\.\d+)?$/.test(x.target_unit_price)||Number(x.target_unit_price)<0))next.push(`Position ${i+1}: Target price is invalid.`)});if(next.length){setErrors(next);return}setPending(true);setErrors([]);try{const result=await onSave(draft);setSuccess({destinationLabel:'RFQ',destinationNumber:result.rfq?.procurementNumber||result.rfq?.id,procurementNumber:result.rfq?.procurementNumber||upload.procurement_number,convertedPositions:result.eligibleCount,navigationUrl:result.navigationUrl})}catch(e){setErrors([e instanceof Error?e.message:'The Draft RFQ could not be created.'])}finally{setPending(false)}};
 return <DocumentConversionModal open={open} title="Review RFQ Product Data" sourceLabel="BOM" destinationLabel="RFQ" sourceNumber={upload?.original_file_name||upload?.document_name||upload?.id} procurementNumber={upload?.procurement_number||'—'} dirty={dirty} pending={pending} errors={errors} success={success} onClose={onClose} onReset={reset} onConvert={save} convertLabel="Save and Create RFQ"><section><h3 className="font-bold text-blue-950">Product and Commercial Information</h3><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[['Customer reference','customer_reference'],['Destination country','destination_country'],['Currency','currency'],['Notes','notes']].map(([label,key])=><label key={key} className="text-sm font-semibold">{label}<input value={(draft as any)[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2"/></label>)}<label className="text-sm font-semibold">Required delivery date<input type="date" value={draft.required_delivery_date} onChange={e=>setDraft({...draft,required_delivery_date:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2"/></label></div></section><section className="mt-6"><h3 className="font-bold text-blue-950">RFQ Positions</h3><div className="mt-3 overflow-x-auto rounded-xl border"><table className="min-w-[1050px] text-left text-xs"><thead className="sticky top-0 bg-slate-900 text-white"><tr>{['Source row','Part Number','Manufacturer','Description','Quantity','Unit','Target price','Currency','Technical status'].map(x=><th key={x} className="p-2">{x}</th>)}</tr></thead><tbody>{draft.items.map((x,i)=><tr key={x.source_bom_item_id} className="border-t"><td className="bg-slate-100 p-2">{items[i]?.row_number??i+1}<div className="text-[10px] text-slate-500">Read only</div></td>{(['part_number','manufacturer','description','requested_quantity','unit','target_unit_price','currency'] as const).map(key=><td key={key} className="p-1"><input type={key==='requested_quantity'||key==='target_unit_price'?'number':'text'} value={x[key]} onChange={e=>setDraft({...draft,items:draft.items.map((row,index)=>index===i?{...row,[key]:e.target.value}:row)})} className="w-full min-w-24 rounded border px-2 py-1.5"/></td>)}<td className="bg-slate-100 p-2 text-slate-600">{items[i]?.validation_status||'—'} / {items[i]?.part_number_check_status||'—'}<div className="text-[10px]">Read only</div></td></tr>)}</tbody></table></div></section><section className="mt-5 rounded-xl bg-slate-100 p-4 text-sm text-slate-700"><b>Technical and System Information · Read only</b><p className="mt-1">BOM ID, source row IDs, normalization and verification results, Customer ownership, Procurement Chain, RFQ status and numbering cannot be edited.</p></section></DocumentConversionModal>
}
