import {NextRequest,NextResponse} from 'next/server';
import {createClient} from '../../../../../lib/supabase/server';
import {createAdminClient} from '../../../../../lib/supabase/admin';
import {getCanonicalSupplierForAuthenticatedUser} from '../../../../../lib/suppliers/canonical';

const bucket='supplier-company-documents',max=2*1024*1024,allowed=new Set(['image/png','image/jpeg']);
const fail=(error:string,status=400)=>NextResponse.json({error},{status});
const safe=(value:string)=>value.toLowerCase().replace(/[^a-z0-9._-]+/g,'-').replace(/^-+|-+$/g,'')||'image';
async function context(){const session=await createClient(),auth=await session.auth.getUser();if(auth.error||!auth.data.user)return{error:fail('Supplier authentication required.',401)};const admin=createAdminClient();if(!admin)return{error:fail('Image service is unavailable.',503)};const identity=await getCanonicalSupplierForAuthenticatedUser(admin,auth.data.user).catch(()=>null);if(!identity)return{error:fail('Canonical Supplier Company Profile setup is required.',409)};return{admin,user:auth.data.user,identity};}
export async function POST(request:NextRequest){const ctx=await context();if('error'in ctx)return ctx.error;if(ctx.identity.profile.public_profile_status==='suspended')return fail('This public profile is suspended.',403);const form=await request.formData(),kind=String(form.get('kind')||'');if(!['logo','cover'].includes(kind))return fail('Invalid image type.');const file=form.get('file');if(!(file instanceof File)||file.size===0)return fail('Choose a non-empty image.');if(!allowed.has(file.type))return fail('Use a PNG or JPEG image.');if(file.size>max)return fail('Image must be 2 MB or smaller.');const ext=file.type==='image/png'?'png':'jpg',path=`supplier-profile-images/${ctx.user.id}/${ctx.identity.canonicalSupplierId}/${kind}/${crypto.randomUUID()}-${safe(file.name)}.${ext}`;const uploaded=await ctx.admin.storage.from(bucket).upload(path,Buffer.from(await file.arrayBuffer()),{contentType:file.type,upsert:false});if(uploaded.error)return fail('Image could not be uploaded.',500);const column=kind==='logo'?'logo_url':'cover_image_url';const old=ctx.identity.profile[column];const saved=await ctx.admin.from('supplier_company_profiles').update({[column]:path,public_profile_status:'draft',pending_review_at:null}).eq('profile_id',ctx.identity.sourceProfileId).eq('user_id',ctx.user.id);if(saved.error){await ctx.admin.storage.from(bucket).remove([path]);return fail('Image reference could not be saved.',500)}if(typeof old==='string'&&old.startsWith(`supplier-profile-images/${ctx.user.id}/`))await ctx.admin.storage.from(bucket).remove([old]);const signed=await ctx.admin.storage.from(bucket).createSignedUrl(path,3600);return NextResponse.json({path,previewUrl:signed.data?.signedUrl||null});}
export async function DELETE(request:NextRequest){const ctx=await context();if('error'in ctx)return ctx.error;if(ctx.identity.profile.public_profile_status==='suspended')return fail('This public profile is suspended.',403);const kind=request.nextUrl.searchParams.get('kind');if(!kind||!['logo','cover'].includes(kind))return fail('Invalid image type.');const column=kind==='logo'?'logo_url':'cover_image_url',old=ctx.identity.profile[column];const saved=await ctx.admin.from('supplier_company_profiles').update({[column]:null,public_profile_status:'draft',pending_review_at:null}).eq('profile_id',ctx.identity.sourceProfileId).eq('user_id',ctx.user.id);if(saved.error)return fail('Image could not be removed.',500);if(typeof old==='string'&&old.startsWith(`supplier-profile-images/${ctx.user.id}/`))await ctx.admin.storage.from(bucket).remove([old]);return NextResponse.json({removed:true});}
