import {NextRequest,NextResponse} from 'next/server';
import {createClient} from '../../../../lib/supabase/server';
import {createAdminClient} from '../../../../lib/supabase/admin';
import {getCanonicalSupplierForAuthenticatedUser} from '../../../../lib/suppliers/canonical';
import {derivePublicProfileCompletion,mapSupplierProfile,toSupplierProfileColumns,validateSupplierProfile,type SupplierCompanyProfileEditableData} from '../../../../lib/suppliers/profile-contract';

export const dynamic='force-dynamic';
const fail=(message:string,status=400,errors?:string[])=>NextResponse.json({error:message,errors},{status});
const string=(value:unknown,max=10000)=>typeof value==='string'?value.trim().slice(0,max):'';
const nullableNumber=(value:unknown)=>value===''||value===null||value===undefined?null:Number(value);
const strings=(value:unknown)=>Array.isArray(value)?value.filter((item):item is string=>typeof item==='string').map(item=>item.trim()).filter(Boolean):[];

const privateColumns=['company_name','business_registration_number','tax_vat_number','country_iso2','country_name','legal_address','office_address','website','company_phone','company_email','main_contact_name','main_contact_position','main_contact_email','main_contact_phone','company_description','product_categories_text','years_in_business','bank_account_holder_name','bank_name','bank_country_iso2','bank_country_name','bank_address','account_number','iban','swift_bic','payment_currency','payment_notes'] as const;
const responseColumns=[...privateColumns,'public_display_name','public_short_description','public_detailed_description','public_city','public_supplier_type','public_brands','public_categories','logo_url','cover_image_url','regions_served','delivery_countries','preferred_currencies','employee_count','supported_languages','minimum_order_value','minimum_order_currency','typical_lead_time_min_days','typical_lead_time_max_days','response_time_hours','public_incoterms','public_payment_terms','manufacturing_capabilities','engineering_capabilities','testing_capabilities','quality_control_capabilities','custom_sourcing_capabilities','additional_capabilities','public_profile_status','pending_review_at','updated_at','decision_reason'] as const;

function publicInput(value:any):SupplierCompanyProfileEditableData{return{
 publicDisplayName:string(value?.publicDisplayName,200),publicShortDescription:string(value?.publicShortDescription,500),publicDetailedDescription:string(value?.publicDetailedDescription,10000),country:string(value?.country,120),city:string(value?.city,120),supplierType:string(value?.supplierType,120),brands:string(value?.brands,2000),categories:string(value?.categories,2000),logoUrl:string(value?.logoUrl,1000),coverImageUrl:string(value?.coverImageUrl,1000),regionsServed:string(value?.regionsServed,2000),deliveryCountries:string(value?.deliveryCountries,2000),preferredCurrencies:string(value?.preferredCurrencies,200),website:string(value?.website,1000),employeeCount:nullableNumber(value?.employeeCount),supportedLanguages:strings(value?.supportedLanguages),minimumOrderValue:nullableNumber(value?.minimumOrderValue),minimumOrderCurrency:string(value?.minimumOrderCurrency,3).toUpperCase(),typicalLeadTimeMinDays:nullableNumber(value?.typicalLeadTimeMinDays),typicalLeadTimeMaxDays:nullableNumber(value?.typicalLeadTimeMaxDays),responseTimeHours:nullableNumber(value?.responseTimeHours),publicIncoterms:strings(value?.publicIncoterms).map(item=>item.toUpperCase()),publicPaymentTerms:string(value?.publicPaymentTerms,2000),manufacturingCapabilities:strings(value?.manufacturingCapabilities),engineeringCapabilities:strings(value?.engineeringCapabilities),testingCapabilities:strings(value?.testingCapabilities),qualityControlCapabilities:strings(value?.qualityControlCapabilities),customSourcingCapabilities:strings(value?.customSourcingCapabilities),additionalCapabilities:strings(value?.additionalCapabilities),
};}

function sanitized(row:any){const profile=Object.fromEntries(responseColumns.filter(key=>key!=='decision_reason'||row.public_profile_status==='rejected').map(key=>[key,row[key]??null]));const editable=mapSupplierProfile(row);return{profileKey:row.profile_id,profile,publicProfile:editable,completionPercent:derivePublicProfileCompletion(editable),missingRequiredFields:missing(editable)};}
function missing(value:SupplierCompanyProfileEditableData){const fields:[keyof SupplierCompanyProfileEditableData,string][]=[['publicDisplayName','Public display name'],['publicShortDescription','Public short description'],['publicDetailedDescription','Public full description'],['country','Country'],['supplierType','Supplier type'],['categories','Product category or specialization'],['supportedLanguages','Supported language']];const absent=fields.filter(([key])=>Array.isArray(value[key])?(value[key] as string[]).length===0:!value[key]).map(([,label])=>label);if(!value.regionsServed&&!value.deliveryCountries)absent.push('Delivery region or country');return absent;}

async function context(){const session=await createClient();const auth=await session.auth.getUser();if(auth.error||!auth.data.user)return{error:fail('Supplier authentication required.',401)};const admin=createAdminClient();if(!admin)return{error:fail('Supplier profile service is unavailable.',503)};const identity=await getCanonicalSupplierForAuthenticatedUser(admin,auth.data.user).catch(()=>null);if(!identity)return{error:fail('Complete or repair your Supplier Company Profile canonical registration before continuing.',409)};return{admin,user:auth.data.user,identity};}

export async function GET(){const ctx=await context();if('error'in ctx)return ctx.error;const result=await ctx.admin.from('supplier_company_profiles').select('*').eq('profile_id',ctx.identity.sourceProfileId).eq('user_id',ctx.user.id).single();if(result.error)return fail('Supplier Company Profile could not be loaded.',500);const previews:any={};for(const [kind,column] of [['logo','logo_url'],['cover','cover_image_url']] as const){const path=result.data[column];if(typeof path==='string'&&path.startsWith('supplier-profile-images/')){const signed=await ctx.admin.storage.from('supplier-company-documents').createSignedUrl(path,3600);previews[kind]=signed.data?.signedUrl||null}else previews[kind]=path||null}return NextResponse.json({...sanitized(result.data),imagePreviews:previews});}

export async function PATCH(request:NextRequest){const ctx=await context();if('error'in ctx)return ctx.error;const body=await request.json().catch(()=>null);if(!body||!['draft','submit'].includes(body.action))return fail('Invalid profile action.');const current=await ctx.admin.from('supplier_company_profiles').select('*').eq('profile_id',ctx.identity.sourceProfileId).eq('user_id',ctx.user.id).single();if(current.error)return fail('Supplier Company Profile could not be loaded.',404);if(current.data.public_profile_status==='suspended')return fail('This public profile is suspended and cannot be changed by the Supplier.',403);
 const editable=publicInput(body.publicProfile);editable.logoUrl=current.data.logo_url||'';editable.coverImageUrl=current.data.cover_image_url||'';const validation=validateSupplierProfile(editable);if('errors' in validation)return fail('Please correct the highlighted public profile fields.',422,validation.errors);const missingFields=missing(editable);if(body.action==='submit'&&missingFields.length)return fail('Complete the required public profile fields before submitting.',422,missingFields);if(body.action==='submit'&&current.data.public_profile_status==='pending_review')return fail('This profile is already pending review.',409);
 const privateInput=body.privateProfile&&typeof body.privateProfile==='object'?body.privateProfile:{};const update:any={...toSupplierProfileColumns(validation.value)};for(const key of privateColumns){if(!Object.hasOwn(privateInput,key))continue;const value=privateInput[key];if(key==='years_in_business')update[key]=nullableNumber(value);else update[key]=string(value,key==='company_description'||key==='payment_notes'||key.endsWith('address')?5000:1000)||null}update.public_profile_status=body.action==='submit'?'pending_review':'draft';if(body.action==='submit')update.pending_review_at=new Date().toISOString();else if(current.data.public_profile_status!=='pending_review')update.pending_review_at=null;
 const saved=await ctx.admin.from('supplier_company_profiles').update(update).eq('profile_id',ctx.identity.sourceProfileId).eq('user_id',ctx.user.id).select('*').single();if(saved.error)return fail('Supplier Company Profile could not be saved.',409);
 if(Array.isArray(body.contacts)){const contacts=body.contacts.slice(0,3).map((item:any,index:number)=>({profile_id:ctx.identity.sourceProfileId,user_id:ctx.user.id,canonical_supplier_id:ctx.identity.canonicalSupplierId,contact_index:index+1,contact_name:string(item?.contact_name,200)||null,contact_position:string(item?.contact_position,200)||null,contact_email:string(item?.contact_email,320)||null,contact_phone:string(item?.contact_phone,100)||null,contact_whatsapp:string(item?.contact_whatsapp,100)||null,contact_notes:string(item?.contact_notes,2000)||null}));const contactsSave=await ctx.admin.from('supplier_company_contacts').upsert(contacts,{onConflict:'profile_id,contact_index'});if(contactsSave.error)return fail('Profile was saved, but contacts could not be saved.',409)}
 return NextResponse.json({...sanitized(saved.data),message:body.action==='submit'?'Profile submitted for Admin review.':'Profile draft saved.'});}
