import {NextRequest,NextResponse} from 'next/server';
import {createAdminClient} from '../../../../lib/supabase/admin';
import {DIRECTORY_PUBLIC_COLUMNS,parseDirectoryQuery,publicDirectorySupplier} from '../../../../lib/suppliers/public-directory';

export const dynamic='force-dynamic';
const safeError=()=>NextResponse.json({error:'Supplier directory is temporarily unavailable.'},{status:500});
const searchable=(value:string)=>value.replace(/[%_,()]/g,' ').replace(/\s+/g,' ').trim();

export async function GET(request:NextRequest){
 const database=createAdminClient();if(!database)return NextResponse.json({error:'Supplier directory is temporarily unavailable.'},{status:503});
 const scope=request.nextUrl.searchParams.get('scope')==='homepage'?'homepage':'directory';
 if(scope==='homepage'){
  const result=await database.from('verified_supplier').select('supplier_id,canonical_supplier_id,public_slug,name,pic,public_short_description,public_country,homepage_sort_order,suppliers!inner(supplier_status)').eq('is_active',true).eq('is_public',true).eq('show_on_homepage',true).not('canonical_supplier_id','is',null).eq('suppliers.supplier_status','active').order('homepage_sort_order',{ascending:true}).order('name',{ascending:true}).order('supplier_id',{ascending:true}).limit(4);
  if(result.error){console.error({operation:'public_homepage_suppliers',diagnosticCode:'PUBLIC_SUPPLIER_QUERY_FAILED'});return safeError()}
  return NextResponse.json({suppliers:(result.data??[]).map(row=>({slug:row.public_slug,name:row.name||'Verified Supplier',logoUrl:row.pic||null,description:row.public_short_description||null,country:row.public_country||null,verified:true}))},{headers:{'Cache-Control':'no-store'}});
 }
 const input=parseDirectoryQuery(request.nextUrl.searchParams);let productSupplierIds:string[]=[];const q=searchable(input.q);
 if(q){const products=await database.from('products').select('supplier_id').eq('is_public',true).eq('review_status','approved').eq('product_status','active').or(`brand_manufacturer.ilike.%${q}%,part_number_mpn.ilike.%${q}%,product_name.ilike.%${q}%`).limit(500);if(!products.error)productSupplierIds=[...new Set((products.data??[]).map(row=>row.supplier_id).filter(Boolean))]}
 let query=database.from('verified_supplier').select(DIRECTORY_PUBLIC_COLUMNS,{count:'exact'}).eq('is_active',true).eq('is_public',true).not('canonical_supplier_id','is',null).eq('show_public_website',true).eq('suppliers.supplier_status','active');
 if(q){const fields=['name','public_display_name','public_short_description','public_country','public_city','public_supplier_type','public_categories','public_brands','regions_served','delivery_countries'].map(field=>`${field}.ilike.%${q}%`);if(productSupplierIds.length)fields.push(`canonical_supplier_id.in.(${productSupplierIds.join(',')})`);query=query.or(fields.join(','))}
 if(input.country)query=query.ilike('public_country',input.country);if(input.supplierType)query=query.ilike('public_supplier_type',input.supplierType);if(input.category)query=query.ilike('public_categories',`%${searchable(input.category)}%`);if(input.brand)query=query.ilike('public_brands',`%${searchable(input.brand)}%`);if(input.language)query=query.contains('supported_languages',[input.language]);if(input.currency)query=query.or(`minimum_order_currency.eq.${input.currency},preferred_currencies.ilike.%${input.currency}%`);if(input.deliveryRegion)query=query.or(`regions_served.ilike.%${searchable(input.deliveryRegion)}%,delivery_countries.ilike.%${searchable(input.deliveryRegion)}%`);if(input.capability){const value=`%${searchable(input.capability)}%`;query=query.or(['manufacturing_capabilities','engineering_capabilities','testing_capabilities','quality_control_capabilities','custom_sourcing_capabilities','additional_capabilities'].map(field=>`${field}.cs.{${value.replace(/%/g,'')}}`).join(','))}if(input.minOrderMax>=0)query=query.lte('minimum_order_value',input.minOrderMax);if(input.leadTimeMax>=0)query=query.lte('typical_lead_time_max_days',input.leadTimeMax);
 const orders:Record<string,[string,boolean,boolean?][]>={recommended:[['public_directory_sort_order',true,true],['public_profile_updated_at',false,true],['name',true]],verified:[['is_public',false],['public_directory_sort_order',true,true],['name',true]],response:[['response_time_hours',true,true],['name',true]],'minimum-order':[['minimum_order_value',true,true],['name',true]],'lead-time':[['typical_lead_time_max_days',true,true],['name',true]],newest:[['public_profile_updated_at',false,true],['name',true]],'name-asc':[['name',true]],'name-desc':[['name',false]]};for(const[field,ascending,nullsFirst]of orders[input.sort])query=query.order(field,{ascending,nullsFirst});query=query.order('supplier_id',{ascending:true});
 const from=(input.page-1)*input.pageSize,result=await query.range(from,from+input.pageSize-1);if(result.error){console.error({operation:'public_supplier_directory',diagnosticCode:'PUBLIC_SUPPLIER_QUERY_FAILED'});return safeError()}
 const total=result.count??0,totalPages=Math.max(1,Math.ceil(total/input.pageSize));if(input.page>totalPages&&total>0)return NextResponse.json({items:[],page:input.page,pageSize:input.pageSize,total,totalPages});
 const rows=result.data??[],canonicalIds=rows.map((row:any)=>row.canonical_supplier_id).filter(Boolean),counts=new Map<string,number>();if(canonicalIds.length){const products=await database.from('products').select('supplier_id').in('supplier_id',canonicalIds).eq('is_public',true).eq('review_status','approved').eq('product_status','active').limit(5000);if(products.error)console.error({operation:'public_supplier_product_counts',diagnosticCode:'PUBLIC_PRODUCT_COUNT_FAILED'});for(const row of products.data??[])counts.set(row.supplier_id,(counts.get(row.supplier_id)??0)+1)}
 return NextResponse.json({items:rows.map((row:any)=>publicDirectorySupplier(row,counts.get(row.canonical_supplier_id)??0)),page:input.page,pageSize:input.pageSize,total,totalPages},{headers:{'Cache-Control':'no-store'}});
}
