import{NextResponse}from'next/server';import{requireInternalApi}from'../../../../../../../lib/auth/require-internal-api';
import{resolveCanonicalSupplierId}from'../../../../../../../lib/suppliers/canonical';
const statuses=new Set(['submitted','under_review','approved','rejected','public','inactive']);
export async function PATCH(request:Request,{params}:{params:Promise<{supplierId:string;productId:string}>}){
 const auth=await requireInternalApi();if('error'in auth)return NextResponse.json({error:auth.error},{status:auth.status});const{supplierId,productId}=await params,body=await request.json().catch(()=>null);if(!body)return NextResponse.json({error:'Invalid JSON body.'},{status:400});
 const canonical=await resolveCanonicalSupplierId(auth.admin,supplierId);if(!canonical)return NextResponse.json({error:'Supplier relationship could not be resolved.'},{status:409});
 const allowed=['product_name','brand_manufacturer','part_number_mpn','category','product_type','short_description','main_image_url','moq_quantity','lead_time','availability','condition','product_status','is_public','public_sort_order','review_reason'];const update:any={};for(const key of allowed)if(Object.hasOwn(body,key))update[key]=body[key];
 if(Object.hasOwn(body,'review_status')){if(!statuses.has(body.review_status))return NextResponse.json({error:'Invalid review status.'},{status:400});update.review_status=body.review_status}if(update.review_status==='rejected'&&!String(update.review_reason??'').trim())return NextResponse.json({error:'A rejection reason is required.'},{status:400});if(update.is_public===true&&!['approved','public'].includes(update.review_status??''))return NextResponse.json({error:'Only approved products can be published.'},{status:400});
 update.reviewed_by=auth.user.id;update.reviewed_at=new Date().toISOString();const before=await auth.admin.from('products').select('*').eq('product_id',productId).eq('supplier_id',canonical.canonicalSupplierId).maybeSingle();if(!before.data)return NextResponse.json({error:'Supplier product was not found.'},{status:404});const saved=await auth.admin.from('products').update(update).eq('product_id',productId).eq('supplier_id',canonical.canonicalSupplierId).select('*').single();if(saved.error){console.error('Product save failed:',saved.error);return NextResponse.json({error:'Product could not be saved.'},{status:409})}await auth.admin.from('supplier_verification_audit_log').insert({profile_id:canonical.sourceProfileId,canonical_supplier_id:canonical.canonicalSupplierId,product_id:productId,action:`product_${saved.data.review_status}`,previous_values:before.data,new_values:saved.data,reason:saved.data.review_reason,performed_by:auth.user.id});return NextResponse.json({product:saved.data});
}
