import 'server-only';
import {createOpenAIClient,loadAiConfig,resolveOpenAIKey} from '../ai/config';
import {sendSmtp} from '../email/smtp';
import {clarificationIdempotencyKey,clarificationToken,needsSupplierClarification} from './clarification-policy';
import {loadSupplierEmailPromptConfig} from './prompt-config';
const schema={type:'object',additionalProperties:false,properties:{subject:{type:'string'},body:{type:'string'}},required:['subject','body']};
const output=(r:any)=>r.output_text||(r.output??[]).flatMap((x:any)=>(x.content??[]).filter((p:any)=>p.type==='output_text').map((p:any)=>p.text)).join('');
export async function ensureSupplierClarification(database:any,input:{supplierItem:any;rfqItem:any;match:any;recipientEmail:string;procurementNumber:string;quotationReference?:string|null}){
 if(!needsSupplierClarification(input.match,input.supplierItem.offeredMpn,input.rfqItem.part_number))return{required:false};const version=1,token=clarificationToken(input.supplierItem.id,input.rfqItem.rfq_item_id,version),key=clarificationIdempotencyKey(input.supplierItem.id,input.rfqItem.rfq_item_id,version),config:any=await loadSupplierEmailPromptConfig();
 const existing=await database.from('supplier_part_clarifications').select('*').eq('idempotency_key',key).maybeSingle();if(existing.data)return{required:true,clarification:existing.data,created:false};
 const inserted=await database.from('supplier_part_clarifications').insert({supplier_response_item_id:input.supplierItem.id,candidate_rfq_item_id:input.rfqItem.rfq_item_id,clarification_version:version,clarification_token:token,idempotency_key:key,status:'clarification_draft',original_supplier_part_number:input.supplierItem.offeredMpn??null,candidate_part_number:input.rfqItem.part_number??null,candidate_manufacturer:input.rfqItem.manufacturer??null,recipient_email:input.recipientEmail,prompt_version_id:config.id??null}).select('*').single();if(inserted.error)throw new Error(inserted.error.message);if(!config.clarification_enabled)return{required:true,clarification:inserted.data,created:true};
 try{const {config:ai}=await loadAiConfig(),client=createOpenAIClient(resolveOpenAIKey(ai)),response=await client.responses.create({model:config.clarification_model||ai.default_model,instructions:config.clarification_system_prompt,input:JSON.stringify({procurementNumber:input.procurementNumber,rfqPosition:input.rfqItem.line_number,requestedPartNumber:input.rfqItem.part_number,supplierOfferedPartNumber:input.supplierItem.offeredMpn??null,candidatePartNumber:input.rfqItem.part_number,candidateManufacturer:input.rfqItem.manufacturer,productDescription:input.rfqItem.description,technicalParameters:input.supplierItem.technicalParameters??[],quotationReference:input.quotationReference??null,clarificationToken:token}),text:{format:{type:'json_schema',name:'supplier_part_clarification_email',strict:true,schema}}} as any),generated=JSON.parse(output(response));let state='clarification_pending_send',messageId=null,sentAt=null;if(config.clarification_automatic_send){const sent=await sendSmtp({to:input.recipientEmail,subject:`${generated.subject} / ${token}`,text:generated.body,html:`<p>${String(generated.body).replace(/\n/g,'<br>')}</p>`});messageId=sent.messageId;sentAt=new Date().toISOString();state='supplier_confirmation_pending'}const saved=await database.from('supplier_part_clarifications').update({outbound_subject:generated.subject,outbound_body:generated.body,outbound_message_id:messageId,sent_at:sentAt,status:state}).eq('id',inserted.data.id).select('*').single();return{required:true,clarification:saved.data,created:true}}catch{await database.from('supplier_part_clarifications').update({status:'clarification_delivery_failed',safe_error:'Clarification generation or delivery failed.'}).eq('id',inserted.data.id);return{required:true,clarification:inserted.data,created:true,error:true}}
}

const noCandidate='00000000-0000-0000-0000-000000000000';
const safeHtml=(value:string)=>value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\n/g,'<br>');
export async function draftAdminSupplierClarification(database:any,input:{supplierItem:any;rfqItem?:any|null;recipientEmail:string;procurementNumber:string;warning?:string|null;technicalDifferences?:unknown;missingFields?:unknown;quotationReference?:string|null;adminId:string}){
 const candidateId=input.rfqItem?.rfq_item_id??noCandidate,version=1,token=clarificationToken(input.supplierItem.id,candidateId,version),key=clarificationIdempotencyKey(input.supplierItem.id,candidateId,version),config:any=await loadSupplierEmailPromptConfig();
 const existing=await database.from('supplier_part_clarifications').select('*').eq('idempotency_key',key).maybeSingle();if(existing.data?.outbound_subject&&existing.data?.outbound_body)return{clarification:existing.data,created:false};
 let row=existing.data;if(!row){const inserted=await database.from('supplier_part_clarifications').insert({supplier_response_item_id:input.supplierItem.id,candidate_rfq_item_id:input.rfqItem?.rfq_item_id??null,clarification_version:version,clarification_token:token,idempotency_key:key,status:'clarification_draft',original_supplier_part_number:input.supplierItem.offered_mpn??null,candidate_part_number:input.rfqItem?.part_number??null,candidate_manufacturer:input.rfqItem?.manufacturer??null,recipient_email:input.recipientEmail,prompt_version_id:config.id??null,created_by:input.adminId,updated_by:input.adminId}).select('*').single();if(inserted.error)throw new Error(inserted.error.message);row=inserted.data}
 try{const{config:ai}=await loadAiConfig(),client=createOpenAIClient(resolveOpenAIKey(ai)),context={procurementNumber:input.procurementNumber,rfqPositionNumber:input.rfqItem?.line_number??null,requestedPartNumber:input.rfqItem?.part_number??null,requestedDescription:input.rfqItem?.description??null,supplierPositionReference:input.supplierItem.source_row_number??input.supplierItem.id,offeredPartNumber:input.supplierItem.offered_mpn??null,supplierDescription:input.supplierItem.original_product_name??input.supplierItem.description??null,supplierManufacturer:input.supplierItem.offered_manufacturer??null,package:input.supplierItem.package_quantity??null,quantity:input.supplierItem.offered_quantity??null,unitPrice:input.supplierItem.calculated_unit_price??null,currency:input.supplierItem.currency??null,matchMethod:input.supplierItem.match_method??null,matchConfidence:input.supplierItem.matching_confidence??null,currentWarning:input.warning??null,technicalDifferences:input.technicalDifferences??[],missingFields:input.missingFields??[],proposedPartNumber:input.rfqItem?.part_number??null,clarificationReference:token,quotationReference:input.quotationReference??null},response=await client.responses.create({model:config.clarification_model||ai.default_model,instructions:config.clarification_system_prompt,input:JSON.stringify(context),text:{format:{type:'json_schema',name:'supplier_part_clarification_email',strict:true,schema}}}as any),generated=JSON.parse(output(response)),saved=await database.from('supplier_part_clarifications').update({outbound_subject:String(generated.subject).trim(),outbound_body:String(generated.body).trim(),status:'clarification_pending_send',updated_by:input.adminId,updated_at:new Date().toISOString(),safe_error:null}).eq('id',row.id).select('*').single();if(saved.error)throw new Error(saved.error.message);return{clarification:saved.data,created:true}}catch(error){await database.from('supplier_part_clarifications').update({status:'clarification_delivery_failed',safe_error:'Clarification draft could not be generated.',updated_by:input.adminId,updated_at:new Date().toISOString()}).eq('id',row.id);throw error}
}
export async function sendAdminSupplierClarification(database:any,input:{clarificationId:string;subject:string;body:string;adminId:string;resend?:boolean}){
 const existing=await database.from('supplier_part_clarifications').select('*').eq('id',input.clarificationId).single();if(existing.error||!existing.data)throw new Error('Clarification draft was not found.');const row=existing.data;if(row.sent_at&&!input.resend)return{clarification:row,result:'already_sent'};
 const subject=input.subject.trim(),body=input.body.trim();if(!subject||!body)throw new Error('Clarification subject and body are required.');
 try{const sent=await sendSmtp({to:row.recipient_email,subject:`${subject} / ${row.clarification_token}`,text:body,html:`<p>${safeHtml(body)}</p>`}),now=new Date().toISOString(),saved=await database.from('supplier_part_clarifications').update({outbound_subject:subject,outbound_body:body,outbound_message_id:sent.messageId,sent_at:now,status:'supplier_confirmation_pending',safe_error:null,updated_by:input.adminId,updated_at:now}).eq('id',row.id).select('*').single();if(saved.error)throw new Error(saved.error.message);return{clarification:saved.data,result:'sent'}}catch(error){await database.from('supplier_part_clarifications').update({outbound_subject:subject,outbound_body:body,status:'clarification_delivery_failed',safe_error:'Clarification email delivery failed.',updated_by:input.adminId,updated_at:new Date().toISOString()}).eq('id',row.id);throw error}
}
