import {supplierEmailResponseSchema,type ParsedSupplierEmail} from './schema.ts';
const blank=(node:any,key=''):any=>node.type==='object'?Object.fromEntries(Object.entries(node.properties).map(([child,value])=>[child,blank(value,child)])):node.type==='array'?[]:node.enum?node.enum[0]:node.anyOf?null:node.type==='number'?(key==='extractionConfidence'?0.45:null):null;
const productSignal=/\b(?:MPN|P\/N|PART(?:\s+NUMBER)?|PRODUCT|MOSFET|TRANSISTOR|CAPACITOR|RESISTOR|DIODE|CONTROLLER|REGULATOR|MODULE|IC)\b/i;
const likelyMpn=(line:string)=>line.match(/^(?:\d+[.)]\s*)?(?:MPN|P\/N|PART(?:\s+NUMBER)?)?\s*[:=]?\s*((?=[A-Z0-9._/-]{5,}(?:[,;]|\s|$))(?=[A-Z0-9._/-]*[A-Z])(?=[A-Z0-9._/-]*\d)[A-Z0-9]+(?:[-._/][A-Z0-9]+)*)/i)?.[1]??null;
const decimal=(value:string)=>Number(value.replace(/\s/g,'').replace(/,(?=\d{1,2}\b)/,'.').replace(/,/g,''));
export function deterministicSupplierEmailExtraction(preparedText:string):ParsedSupplierEmail|null{
 const schema:any=supplierEmailResponseSchema,result:any=blank(schema),currency=preparedText.match(/\b(USD|EUR|GBP|ILS|CAD|AUD|JPY)\b/i)?.[1]?.toUpperCase()??null;result.procurementNumber=preparedText.match(/\bPR-\d{4}-\d{6,}\b/i)?.[0]?.toUpperCase()??null;result.responseType='other';result.responseRelationship='unknown';result.remainingItemsStatus='unknown';result.defaultCurrency=currency;result.generalWarnings=['Deterministic fallback extraction was used; Admin review is required.'];
 for(const [index,raw] of preparedText.split(/\r?\n/).entries()){const line=raw.replace(/\s+/g,' ').trim();const mpn=likelyMpn(line);if(!line||(!mpn&&!productSignal.test(line)))continue;const item:any=blank(schema.properties.items.items);item.sourceReference.sourceRowNumber=index+1;item.sourceReference.sourceText=line;item.offeredMpn=mpn;item.originalProductName=mpn?line.replace(mpn,'').replace(/^[\s,;:#.-]+|[\s,;:#.-]+$/g,'')||null:line;item.responseStatus='offered';item.extractionConfidence=.45;item.extractionWarnings=['Extracted by deterministic fallback; verify this position.'];const quantity=line.match(/(?:QTY|QUANTITY|AVAILABLE)?\s*[:=]?\s*(\d[\d ,.]*)\s*(?:PCS|PIECES|EA|UNITS?)\b/i);if(quantity){const parsed=decimal(quantity[1]);if(Number.isFinite(parsed))item.offeredQuantityNormalized=parsed;item.offeredQuantityRaw=quantity[0]}const price=line.match(/(?:USD|EUR|GBP|ILS|CAD|AUD|JPY|[$€£])\s*(\d[\d ,.]*\d|\d)/i);if(price){const parsed=decimal(price[1]);if(Number.isFinite(parsed))item.priceAmount=parsed;item.priceRaw=price[0];item.currency=line.match(/\b(USD|EUR|GBP|ILS|CAD|AUD|JPY)\b/i)?.[1]?.toUpperCase()??currency}result.items.push(item)}
 return result.items.length?result:null;
}
