export type SupplierItemMatchState='matched_exact'|'matched_normalized'|'matched_semantic'|'review_required'|'ambiguous'|'unmatched';
export type SupplierItemMatchResult={matchState:SupplierItemMatchState;matchedRfqItemId:string|null;candidateRfqItemId:string|null;candidateRfqItemIds:string[];confidence:number;reviewRequired:boolean;reasons:string[];warnings:string[];match:any|null;candidate:any|null;candidates:any[];method:string;similarities:string[];differences:string[]};
export const normalizeSupplierMpn=(value:unknown)=>String(value??'').normalize('NFKC').replace(/[‐‑‒–—−]/g,'-').trim().replace(/^[\s"'`()\[\]{},;:]+|[\s"'`()\[\]{},;:]+$/g,'').toUpperCase().replace(/[\s._/-]+/g,'');
const aliases:Record<string,string>={ST:'STMICROELECTRONICS',STMICRO:'STMICROELECTRONICS',TI:'TEXASINSTRUMENTS',ADI:'ANALOGDEVICES'};
const maker=(value:unknown)=>{const key=String(value??'').toUpperCase().replace(/[^A-Z0-9]/g,'');return aliases[key]??key};
const tokens=(value:unknown)=>new Set(String(value??'').normalize('NFKC').toUpperCase().match(/[A-Z0-9]+(?:\.[0-9]+)?(?:KOHM|MOHM|OHM|UF|NF|PF|V|A|W|HZ|BIT|PIN)?/g)??[]);
const id=(row:any)=>String(row?.rfq_item_id??row?.id??'')||null;
export const createMatchResult=(state:SupplierItemMatchState,match:any|null,candidate:any|null,candidates:any[],confidence:number,reasons:string[],warnings:string[],method:string=state):SupplierItemMatchResult=>({matchState:state,matchedRfqItemId:id(match),candidateRfqItemId:id(candidate),candidateRfqItemIds:candidates.map(id).filter(Boolean) as string[],confidence,reviewRequired:!['matched_exact','matched_normalized','matched_semantic'].includes(state),reasons,warnings,match,candidate,candidates,method,similarities:reasons,differences:warnings});
export const createUnmatchedResult=(warning='No suitable RFQ position was identified.')=>createMatchResult('unmatched',null,null,[],0,[],[warning]);
export function matchSupplierPartNumber(item:any,rfqItems:any[]):SupplierItemMatchResult|null{
 try{const raw=String(item.offeredMpn||item.requestedMpn||'').trim().toUpperCase(),mpn=normalizeSupplierMpn(raw),manufacturer=maker(item.offeredManufacturer||item.requestedManufacturer);if(!mpn)return null;const exact=rfqItems.filter(row=>normalizeSupplierMpn(row.normalized_part_number||row.manufacturer_part_number||row.part_number)===mpn),compatible=manufacturer?exact.filter(row=>!maker(row.manufacturer)||maker(row.manufacturer)===manufacturer):exact;if(compatible.length===1){const target=String(compatible[0].part_number??compatible[0].manufacturer_part_number??'').trim().toUpperCase(),state:SupplierItemMatchState=raw===target?'matched_exact':'matched_normalized';return createMatchResult(state,compatible[0],compatible[0],compatible,1,[state==='matched_exact'?'Part number matched exactly.':'Normalized MPN matched exactly.'],[])}if(exact.length)return createMatchResult('ambiguous',null,null,exact,.75,['Normalized MPN matched multiple or manufacturer-conflicting positions.'],['Several RFQ positions may match this supplier item.']);return null}catch{return createMatchResult('review_required',null,null,[],0,[],['Deterministic Part Number matching was unavailable. Manual review is required.'])}}
export function matchSupplierSemantically(item:any,rfqItems:any[]):SupplierItemMatchResult{
 try{const parameters=(Array.isArray(item.technicalParameters)?item.technicalParameters:[]).flatMap((p:any)=>[p.name,p.value,p.unit,p.sourceText]),source=tokens([item.originalProductName,item.productType,item.sourceReference?.sourceText,item.offeredManufacturer,...parameters].join(' '));if(source.size<2)return createUnmatchedResult();const scored=rfqItems.map(row=>{const target=tokens([row.product_name,row.description,row.specification,row.technical_requirements,row.manufacturer,row.part_number,row.manufacturer_part_number].join(' ')),common=[...source].filter(token=>target.has(token)),score=common.length/Math.max(source.size,target.size,1);return{row,score,common}}).filter(x=>x.score>=.25).sort((a,b)=>b.score-a.score);if(scored[0]&&(!scored[1]||scored[0].score-scored[1].score>=.15)){const best=scored[0],confidence=Math.min(.94,.6+best.score*.35),high=confidence>=.85;return high?createMatchResult('matched_semantic',best.row,best.row,scored.slice(0,10).map(x=>x.row),confidence,best.common,[]):createMatchResult('review_required',null,best.row,scored.slice(0,10).map(x=>x.row),confidence,best.common,['Possible RFQ match requires confirmation.'])}if(scored.length)return createMatchResult('ambiguous',null,null,scored.slice(0,10).map(x=>x.row),scored[0].score,scored[0].common,['Several RFQ positions may match this supplier item.']);return createUnmatchedResult()}catch{return createMatchResult('review_required',null,null,[],0,[],['Automatic semantic matching was unavailable. Manual review is required.'])}}
export function matchSupplierProduct(item:any,rfqItems:any[]):SupplierItemMatchResult{return matchSupplierPartNumber(item,rfqItems)??matchSupplierSemantically(item,rfqItems)}
export function summarizeMatchResults(results:SupplierItemMatchResult[]){const matchedItems=results.filter(r=>['matched_exact','matched_normalized','matched_semantic'].includes(r.matchState)).length,reviewItems=results.filter(r=>r.matchState==='review_required').length,ambiguousItems=results.filter(r=>r.matchState==='ambiguous').length,unmatchedItems=results.filter(r=>r.matchState==='unmatched').length;return{success:true,processingStatus:reviewItems||ambiguousItems||unmatchedItems?'parsed_with_review':'parsed',extractedItems:results.length,matchedItems,reviewItems,ambiguousItems,unmatchedItems,technicalError:null}}
