import {createAdminClient} from '../supabase/admin';

export const extractionSystemPrompt=`You are an electronic-component supplier quotation extraction engine.

Analyze the complete supplier email and extract every distinct commercial product position and all explicitly supplied commercial conditions.

The email may contain plain text, HTML tables, copied spreadsheet rows, inconsistent formatting, missing labels, general terms written only once, multiple products in one paragraph, alternative products, abbreviations and incomplete information.

Extract only information present in the source email. Never invent a Part Number, manufacturer, price, quantity, availability, equivalence claim or commercial condition.

Preserve every usable product position, including positions without a Part Number. When a value is absent, return null or an empty array according to the required schema. General commercial terms explicitly stated for the complete quotation may be inherited by individual product positions. Missing fields must create warnings, not deletion of the position. Return all positions using the required strict structured-output schema.`;
export const semanticSystemPrompt=`You are matching one supplier quotation position against positions belonging only to the current RFQ.

Compare the supplier position using its original and normalized Part Number, manufacturer, product name, description, package, technical parameters and available Nexar evidence.

Never select a position outside the supplied current-RFQ candidate list. Do not override an existing exact deterministic Part Number match. Do not claim that two different electronic components are interchangeable based only on a similar description, package or category.

When one candidate is strongly supported, return matched_semantic. When one candidate is probable but not sufficiently certain, return review_required. When several candidates are plausible, return ambiguous. When no suitable candidate exists, return unmatched. No match is a valid result and must never cause an application error. Never invent a supplier Part Number. Return only the required strict structured matching result.`;
export const extractionVariables=['email_subject','email_sender','email_body','procurement_number','supplier_context_json'];
export const semanticVariables=['supplier_item_json','normalized_item_json','nexar_evidence_json','rfq_candidates_json','alternative_parts_allowed'];
export const clarificationVariables=['procurement_number','rfq_position','requested_part_number','supplier_offered_part_number','candidate_part_number','candidate_manufacturer','product_name','product_description','technical_parameters_json','supplier_quotation_reference','supplier_contact_name_or_team','clarification_token'];
export const promptDefaults={configuration_key:'supplier_email_processing',version_number:0,status:'active',extraction_system_prompt:extractionSystemPrompt,extraction_user_template:'Subject: {{email_subject}}\nSender: {{email_sender}}\nProcurement: {{procurement_number}}\n{{email_body}}\nSupplier context: {{supplier_context_json}}',extraction_model:'gpt-5.5',extraction_max_output_tokens:null,extraction_timeout_ms:60000,extraction_retry_count:1,extraction_enabled:true,deterministic_fallback_enabled:true,semantic_system_prompt:semanticSystemPrompt,semantic_user_template:'Supplier: {{supplier_item_json}}\nNormalized: {{normalized_item_json}}\nNexar: {{nexar_evidence_json}}\nCandidates: {{rfq_candidates_json}}\nAlternatives: {{alternative_parts_allowed}}',semantic_model:'gpt-5.5',semantic_max_output_tokens:null,semantic_timeout_ms:60000,semantic_retry_count:1,semantic_auto_match_threshold:.9,semantic_review_threshold:.6,semantic_enabled:true,nexar_enabled:true,nexar_timeout_ms:8000,nexar_retry_count:1,nexar_use_aliases:true,nexar_use_technical_specs:true,nexar_skip_exact_matches:true,clarification_system_prompt:'Write a short professional English email asking a supplier to confirm one provisionally identified electronic component. Use only supplied facts, never invent equivalence or specifications, and include the clarification token.',clarification_user_template:'RFQ {{procurement_number}}, position {{rfq_position}}, requested {{requested_part_number}}, offered {{supplier_offered_part_number}}, candidate {{candidate_part_number}} by {{candidate_manufacturer}}. Technical data: {{technical_parameters_json}}. Reference {{clarification_token}}.',clarification_model:'gpt-5.5',clarification_max_output_tokens:700,clarification_timeout_ms:60000,clarification_retry_count:1,clarification_enabled:true,clarification_automatic_send:false,supplier_confirmation_required:true,schema_version:'supplier-email-v1'} as const;
export function validatePromptTemplate(template:string,allowed:string[],required:string[]){const malformed=/{{(?![a-z_]+}})|(?<!{{)[a-z_]+}}/.test(template),found=[...template.matchAll(/{{([^}]+)}}/g)].map(m=>m[1]),unknown=found.filter(v=>!allowed.includes(v)),missing=required.filter(v=>!found.includes(v));return{valid:!malformed&&!unknown.length&&!missing.length,unknown,missing,errors:[...(malformed?['Malformed template placeholder syntax.']:[]),...(unknown.length?[`Unknown placeholders: ${unknown.join(', ')}`]:[]),...(missing.length?[`Required placeholders missing: ${missing.join(', ')}`]:[])]}}
let cached:any=null;
export async function loadSupplierEmailPromptConfig(){if(cached)return cached;const db=createAdminClient();if(!db)return promptDefaults;const row=await db.from('supplier_email_ai_prompt_versions').select('*').eq('configuration_key','supplier_email_processing').eq('status','active').order('version_number',{ascending:false}).limit(1).maybeSingle();cached=row.data??promptDefaults;return cached}
export const invalidateSupplierEmailPromptConfig=()=>{cached=null};
