'use client';
import { useState } from 'react';
import type { ProcurementPreferences } from '../../../lib/procurement-preferences';

export type CountryOption={iso2:string;name:string};
const input='mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100';
export default function OrderPreferencesForm({value,onChange,countries=[]}:{value:ProcurementPreferences;onChange:(value:ProcurementPreferences)=>void;countries?:CountryOption[]}){
 const [countrySearch,setCountrySearch]=useState('');
 const set=<K extends keyof ProcurementPreferences>(key:K,next:ProcurementPreferences[K])=>onChange({...value,[key]:next});
 const toggleCountry=(code:string)=>set('supplier_countries',value.supplier_countries.includes(code)?value.supplier_countries.filter(x=>x!==code):[...value.supplier_countries,code]);
 return <div className="grid gap-5 md:grid-cols-2">
  <fieldset><legend className="text-sm font-semibold text-slate-700">Priority</legend><div className="mt-2 grid grid-cols-3 gap-2">{[['price','Lowest price'],['delivery_time','Fastest delivery'],['balanced','Balanced']].map(([code,label])=><label key={code} className={`cursor-pointer rounded-xl border p-2 text-center text-xs font-semibold ${value.search_priority===code?'border-blue-600 bg-blue-50 text-blue-800':'border-slate-200 bg-white text-slate-600'}`}><input className="sr-only" type="radio" checked={value.search_priority===code} onChange={()=>set('search_priority',code as ProcurementPreferences['search_priority'])}/>{label}</label>)}</div></fieldset>
  <label className="text-sm font-semibold text-slate-700">Maximum acceptable lead time<div className="flex items-center gap-2"><input className={input} type="number" min="1" step="1" value={value.max_lead_time_days??''} onChange={e=>set('max_lead_time_days',e.target.value?Number(e.target.value):null)}/><span className="mt-1 text-sm">days</span></div></label>
  <div className="md:col-span-2"><label className="text-sm font-semibold text-slate-700">Allowed supplier countries</label><input className={input} value={countrySearch} onChange={e=>setCountrySearch(e.target.value)} placeholder="Search countries…"/><select className={input} value="" onChange={e=>{if(e.target.value){toggleCountry(e.target.value);setCountrySearch('')}}}><option value="">{value.supplier_countries.length?'Add another country':'Any country'}</option>{countries.filter(c=>!value.supplier_countries.includes(c.iso2)&&`${c.name} ${c.iso2}`.toLowerCase().includes(countrySearch.toLowerCase())).map(c=><option key={c.iso2} value={c.iso2}>{c.name} ({c.iso2})</option>)}</select><div className="mt-2 flex flex-wrap gap-2">{value.supplier_countries.map(code=><button type="button" key={code} onClick={()=>toggleCountry(code)} className="hub-unstyled rounded-full bg-blue-100 px-3 py-1 text-xs font-semibold text-blue-800">{countries.find(c=>c.iso2===code)?.name||code} ×</button>)}</div><p className="mt-1 text-xs text-slate-500">No selection means Any country.</p></div>
  <label className="flex items-start gap-3 rounded-xl border border-slate-200 bg-white p-3"><input className="mt-1" type="checkbox" checked={value.allow_independent_suppliers} onChange={e=>set('allow_independent_suppliers',e.target.checked)}/><span><b className="text-sm">Allow independent suppliers</b><small className="mt-1 block text-slate-500">Include verified independent distributors in addition to manufacturers and authorized distributors.</small></span></label>
  <label className="flex items-start gap-3 rounded-xl border border-slate-200 bg-white p-3"><input className="mt-1" type="checkbox" checked={value.allow_alternatives} onChange={e=>set('allow_alternatives',e.target.checked)}/><span className="text-sm font-semibold">Allow alternative part numbers</span></label>
  <label className="flex items-start gap-3 rounded-xl border border-slate-200 bg-white p-3"><input className="mt-1" type="checkbox" checked={value.allow_split_delivery} onChange={e=>set('allow_split_delivery',e.target.checked)}/><span><b className="text-sm">Allow split delivery</b><small className="mt-1 block text-slate-500">Components may arrive in several shipments when this improves availability or delivery time.</small></span></label>
  <div><label className="text-sm font-semibold text-slate-700">Maximum order budget</label><div className="grid grid-cols-[1fr_100px] gap-2"><input className={input} type="number" min="0" step="0.01" value={value.budget_amount??''} onChange={e=>set('budget_amount',e.target.value?Number(e.target.value):null)}/><input className={input} maxLength={3} value={value.budget_currency||''} onChange={e=>set('budget_currency',e.target.value.toUpperCase())} placeholder="USD"/></div></div>
  <label className="text-sm font-semibold text-slate-700 md:col-span-2">Certificate requirements<textarea rows={3} className={input} value={value.certificate_requirements} onChange={e=>set('certificate_requirements',e.target.value)} placeholder="Certificate of Conformity, RoHS, REACH, manufacturer traceability…"/></label>
 </div>;
}
