'use client';

import {ChangeEvent,FormEvent,ReactNode,useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import HubButton from '../../components/ui/HubButton';
import SupplierDetailsModal from './SupplierDetailsModal';

type SupplierRow={supplier_id:string;canonical_supplier_id:string|null;canonical_diagnostic?:string|null;name:string|null;pic:string|null;delivery_product:string|null;show_on_homepage:boolean;homepage_sort_order:number;show_public_website:boolean;public_directory_sort_order:number;is_public:boolean;is_active:boolean};
type PendingProfile={profile_id:string;canonical_supplier_id:string|null;company_name:string|null;public_display_name:string|null;country_name:string|null;pending_review_at:string|null;completion_percent:number;snapshot_status:string;directory_visible:boolean;homepage_visible:boolean};
type CanonicalCandidate={supplier_id:string;name:string;source_profile_id:string|null};
type SupplierForm={canonical_supplier_id:string;name:string;pic:string;delivery_product:string;show_on_homepage:boolean;homepage_sort_order:string;show_public_website:boolean;public_directory_sort_order:string;is_public:boolean;is_active:boolean};
const emptyForm:SupplierForm={canonical_supplier_id:'',name:'',pic:'',delivery_product:'',show_on_homepage:false,homepage_sort_order:'0',show_public_website:false,public_directory_sort_order:'0',is_public:false,is_active:true};
const imageTypes=['image/png','image/jpeg','image/webp'];const maxImageSize=2*1024*1024;
const input='mt-1 w-full rounded-md border border-slate-300 px-3 py-2 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100';
const formFrom=(s:SupplierRow):SupplierForm=>({canonical_supplier_id:s.canonical_supplier_id??'',name:s.name??'',pic:s.pic??'',delivery_product:s.delivery_product??'',show_on_homepage:Boolean(s.show_on_homepage),homepage_sort_order:String(s.homepage_sort_order??0),show_public_website:Boolean(s.show_public_website),public_directory_sort_order:String(s.public_directory_sort_order??0),is_public:Boolean(s.is_public),is_active:Boolean(s.is_active)});
const addFields=(body:FormData,form:SupplierForm)=>{for(const key of ['canonical_supplier_id','name','pic','delivery_product','homepage_sort_order','public_directory_sort_order'] as const)body.set(key,form[key]);for(const key of ['show_on_homepage','show_public_website','is_public','is_active'] as const)body.set(key,String(form[key]));};
const validImage=(value:string)=>value.startsWith('http://')||value.startsWith('https://')||value.startsWith('/')||value.startsWith('blob:');

export default function AdminVerifiedSuppliersPage(){
 const[pendingProfiles,setPendingProfiles]=useState<PendingProfile[]>([]);
 const router=useRouter();const[suppliers,setSuppliers]=useState<SupplierRow[]>([]),[canonicalSuppliers,setCanonicalSuppliers]=useState<CanonicalCandidate[]>([]),[newSupplier,setNewSupplier]=useState<SupplierForm>(emptyForm),[editForm,setEditForm]=useState<SupplierForm>(emptyForm),[editingId,setEditingId]=useState<string|null>(null),[createFile,setCreateFile]=useState<File|null>(null),[editFile,setEditFile]=useState<File|null>(null),[createPreview,setCreatePreview]=useState(''),[editPreview,setEditPreview]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[detailsSupplierId,setDetailsSupplierId]=useState<string|null>(null),[deleteCandidate,setDeleteCandidate]=useState<string|null>(null);
 const load=async()=>{setLoading(true);setError('');try{const response=await fetch('/api/admin/verified-suppliers',{cache:'no-store'}),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.message||body.error||'Verified suppliers could not be loaded.');setSuppliers(body.suppliers??[]);setPendingProfiles(body.pendingProfiles??[]);setCanonicalSuppliers(body.canonicalSuppliers??[])}catch(e){setError(e instanceof Error?e.message:'Verified suppliers could not be loaded.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);useEffect(()=>()=>{if(createPreview.startsWith('blob:'))URL.revokeObjectURL(createPreview);if(editPreview.startsWith('blob:'))URL.revokeObjectURL(editPreview)},[createPreview,editPreview]);
 const selectFile=(kind:'create'|'edit')=>(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;if(!imageTypes.includes(file.type)||file.size>maxImageSize){setError(!imageTypes.includes(file.type)?'Please select a PNG, JPEG, or WebP image.':'Image must be 2 MB or smaller.');event.target.value='';return}const preview=URL.createObjectURL(file);if(kind==='create'){if(createPreview.startsWith('blob:'))URL.revokeObjectURL(createPreview);setCreateFile(file);setCreatePreview(preview)}else{if(editPreview.startsWith('blob:'))URL.revokeObjectURL(editPreview);setEditFile(file);setEditPreview(preview)}};
 const create=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setError('');setSuccess('');try{const data=new FormData();addFields(data,newSupplier);if(createFile)data.set('file',createFile);const response=await fetch('/api/admin/verified-suppliers',{method:'POST',body:data}),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.message||body.error||'Verified supplier could not be created.');setSuppliers(rows=>[...rows,body.supplier].sort((a,b)=>(a.name??'').localeCompare(b.name??'')));setNewSupplier(emptyForm);setCreateFile(null);setCreatePreview('');setSuccess('Verified supplier created successfully.')}catch(e){setError(e instanceof Error?e.message:'Verified supplier could not be created.')}finally{setSaving(false)}};
 const save=async(id:string)=>{setSaving(true);setError('');setSuccess('');try{const payload={canonical_supplier_id:editForm.canonical_supplier_id,name:editForm.name,pic:editForm.pic,delivery_product:editForm.delivery_product,show_on_homepage:Boolean(editForm.show_on_homepage),homepage_sort_order:Number(editForm.homepage_sort_order)||0,show_public_website:Boolean(editForm.show_public_website),public_directory_sort_order:Number(editForm.public_directory_sort_order)||0,is_public:Boolean(editForm.is_public),is_active:Boolean(editForm.is_active)};let request:RequestInit;if(editFile){const data=new FormData();for(const[key,value]of Object.entries(payload))data.set(key,String(value));data.set('file',editFile);request={method:'PUT',body:data}}else request={method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(payload)};const response=await fetch(`/api/admin/verified-suppliers/${encodeURIComponent(id)}`,request),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.message||body.error||'Verified supplier could not be updated.');const saved=body.supplier as SupplierRow;if(!saved||saved.supplier_id!==id)throw new Error('The database did not return the updated Verified Supplier.');if(saved.show_on_homepage!==payload.show_on_homepage||saved.is_public!==payload.is_public||saved.show_public_website!==payload.show_public_website||saved.is_active!==payload.is_active)throw new Error('The database did not persist all visibility settings.');setSuppliers(rows=>rows.map(row=>row.supplier_id===saved.supplier_id?saved:row));setEditingId(null);setEditFile(null);setEditPreview('');setSuccess('Verified supplier updated successfully.')}catch(e){setError(e instanceof Error?e.message:'Verified supplier could not be updated.')}finally{setSaving(false)}};
 const remove=async(id:string)=>{setDeleteCandidate(null);setSaving(true);setError('');const response=await fetch(`/api/admin/verified-suppliers/${encodeURIComponent(id)}`,{method:'DELETE'}),body=await response.json().catch(()=>({}));if(response.ok){setSuppliers(rows=>rows.filter(row=>row.supplier_id!==id));setSuccess('Verified supplier deleted successfully.')}else setError(body.message||body.error||'Verified supplier could not be deleted.');setSaving(false)};
 const startEdit=(row:SupplierRow)=>{setEditingId(row.supplier_id);setEditForm(formFrom(row));setEditFile(null);setEditPreview('');setError('')};
 const goBack=()=>{if(typeof window!=='undefined'&&window.history.length>1)router.back();else router.push('/admin')};
 return <main className="min-h-screen bg-[radial-gradient(circle_at_top_right,rgba(37,99,235,0.35),transparent_30%),linear-gradient(135deg,#061b3f_0%,#082a63_48%,#071632_100%)] py-10 text-white"><div className="mx-auto max-w-[1200px] px-4 sm:px-6 lg:px-8">
  <header className="mb-8 flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="mb-3 inline-flex rounded-full bg-blue-100 px-3 py-1 text-sm font-semibold text-blue-800">Administrator access required</p><h1 className="text-3xl font-bold">Verified Suppliers Admin</h1><p className="mt-2 text-blue-100">Manage public profiles, homepage placement, and supplier-directory visibility.</p></div><div className="flex gap-3"><NavButton href="/">Home</NavButton><NavButton onClick={goBack}>Back</NavButton></div></header>
  {error&&<Notice error>{error}</Notice>}{success&&<Notice>{success}</Notice>}
  {suppliers.filter(row=>row.canonical_diagnostic).map(row=><div key={`diagnostic-${row.supplier_id}`} className="mb-3 rounded-lg border border-amber-300 bg-amber-50 px-4 py-3 text-sm font-semibold text-amber-900">{row.name||'Verified Supplier'}: {row.canonical_diagnostic}</div>)}
  <section className="mb-8 overflow-hidden rounded-xl border border-slate-200 bg-white text-slate-950 shadow-xl"><div className="border-b p-6"><h2 className="text-xl font-bold">Public Profiles Awaiting Review</h2><p className="mt-1 text-sm text-slate-500">Server-filtered Supplier submissions. Approval, Directory publication, and Homepage promotion remain separate decisions.</p></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead><tr className="bg-slate-50"><th className="p-3">Company</th><th className="p-3">Country</th><th className="p-3">Submitted</th><th className="p-3">Completion</th><th className="p-3">Approved snapshot</th><th className="p-3">Directory</th><th className="p-3">Homepage</th><th className="p-3">Review</th></tr></thead><tbody>{pendingProfiles.length?pendingProfiles.map(row=><tr key={row.profile_id} className="border-t"><td className="p-3 font-semibold">{row.public_display_name||row.company_name||'Unnamed supplier'}</td><td className="p-3">{row.country_name||'—'}</td><td className="p-3">{row.pending_review_at?new Date(row.pending_review_at).toLocaleDateString():'—'}</td><td className="p-3">{row.completion_percent}%</td><td className="p-3">{row.snapshot_status}</td><td className="p-3">{row.directory_visible?'Published':'Hidden'}</td><td className="p-3">{row.homepage_visible?'Shown':'Hidden'}</td><td className="p-3">{row.canonical_supplier_id?<Link href={`/admin/suppliers/${row.canonical_supplier_id}`} className="font-bold text-blue-700">Review public profile</Link>:<span className="font-semibold text-amber-700">No canonical supplier is linked</span>}</td></tr>):<tr><td colSpan={8} className="p-8 text-center text-slate-500">No public profiles are awaiting review.</td></tr>}</tbody></table></div></section>
  <section className="mb-8 rounded-xl border border-slate-200 bg-white p-6 text-slate-950 shadow-xl"><h2 className="text-xl font-bold">Create Verified Supplier</h2><p className="mt-1 text-sm text-slate-500">Select an existing canonical supplier. New records remain hidden until explicitly enabled.</p><form onSubmit={create} className="mt-5"><SupplierFields form={newSupplier} set={setNewSupplier} preview={createPreview} fileChange={selectFile('create')} canonicalSuppliers={canonicalSuppliers}/><div className="mt-5"><HubButton type="submit" loading={saving} loadingText="Saving...">Create Verified Supplier</HubButton></div></form></section>
  <section className="rounded-xl border border-slate-200 bg-white text-slate-950 shadow-xl"><div className="flex items-center justify-between border-b p-6"><div><h2 className="text-xl font-bold">Existing Verified Suppliers</h2><p className="mt-1 text-sm text-slate-500">Visibility controls are independent and saved on each existing record.</p></div><HubButton onClick={load} loading={loading}>Refresh</HubButton></div><div className="divide-y">{loading?<p className="p-8 text-center text-slate-500">Loading verified suppliers...</p>:suppliers.length===0?<p className="p-8 text-center text-slate-500">No verified suppliers found.</p>:suppliers.map(row=><SupplierListRow key={row.supplier_id} row={row} editing={editingId===row.supplier_id} editForm={editForm} setEditForm={setEditForm} editPreview={editPreview} fileChange={selectFile('edit')} saving={saving} startEdit={startEdit} save={save} cancel={()=>{setEditingId(null);setEditForm(emptyForm);setEditFile(null);setEditPreview('')}} details={()=>setDetailsSupplierId(row.supplier_id)} remove={()=>setDeleteCandidate(row.supplier_id)}/>)}</div></section>
 </div>{detailsSupplierId&&<SupplierDetailsModal supplierId={detailsSupplierId} onClose={()=>setDetailsSupplierId(null)} onSaved={load}/>} {deleteCandidate&&<Confirm cancel={()=>setDeleteCandidate(null)} confirm={()=>remove(deleteCandidate)}/>}</main>;
}

function SupplierListRow({row,editing,editForm,setEditForm,editPreview,fileChange,saving,startEdit,save,cancel,details,remove}:{row:SupplierRow;editing:boolean;editForm:SupplierForm;setEditForm:(value:SupplierForm|((current:SupplierForm)=>SupplierForm))=>void;editPreview:string;fileChange:(event:ChangeEvent<HTMLInputElement>)=>void;saving:boolean;startEdit:(row:SupplierRow)=>void;save:(id:string)=>void;cancel:()=>void;details:()=>void;remove:()=>void}){return <article className="p-6" data-supplier-id={row.supplier_id}><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex min-w-0 gap-4"><Logo src={row.pic??''}/><div><h3 className="text-lg font-bold">{row.name||'Unnamed supplier'}</h3><p className="mt-1 text-xs text-slate-400">Verified Supplier ID: {row.supplier_id}</p><p className="mt-1 text-sm text-slate-600">{row.delivery_product||'No delivery/product summary'}</p><div className="mt-3 flex flex-wrap gap-2 text-xs"><Badge on={row.show_on_homepage}>Homepage · {row.homepage_sort_order}</Badge><Badge on={row.show_public_website}>Directory · {row.public_directory_sort_order}</Badge><Badge on={row.is_public}>Public profile</Badge><Badge on={row.is_active}>Active</Badge></div></div></div>{!editing&&<div className="flex flex-wrap gap-2"><button type="button" onClick={details} className="rounded-md border border-blue-200 px-3 py-2 text-sm font-semibold text-blue-700">Supplier details</button><button type="button" onClick={()=>startEdit(row)} className="rounded-md border border-blue-200 px-3 py-2 text-sm font-semibold text-blue-700">Edit</button><button type="button" onClick={remove} className="rounded-md border border-red-200 px-3 py-2 text-sm font-semibold text-red-700">Delete</button></div>}</div>{editing&&<div className="mt-6 rounded-xl border border-blue-200 bg-blue-50/40 p-5"><h4 className="mb-4 font-bold text-blue-950">Editing {row.name||'Verified Supplier'}</h4><SupplierFields form={editForm} set={setEditForm} preview={editPreview} fileChange={fileChange}/><div className="mt-5 flex gap-2"><HubButton onClick={()=>save(row.supplier_id)} loading={saving}>Save</HubButton><button type="button" onClick={cancel} disabled={saving} className="rounded-md border bg-white px-4 py-2 text-sm font-semibold disabled:opacity-50">Cancel</button></div></div>}</article>}

function SupplierFields({form,set,preview,fileChange,canonicalSuppliers=[]}:{form:SupplierForm;set:(value:SupplierForm|((current:SupplierForm)=>SupplierForm))=>void;preview:string;fileChange:(event:ChangeEvent<HTMLInputElement>)=>void;canonicalSuppliers?:CanonicalCandidate[]}){const change=(key:keyof SupplierForm,value:string|boolean)=>set(current=>({...current,[key]:value}));return <div className="grid gap-5 md:grid-cols-2"><Field label="Canonical supplier"><input required list="canonical-supplier-options" value={form.canonical_supplier_id} onChange={e=>change('canonical_supplier_id',e.target.value)} placeholder="Select or enter confirmed canonical UUID" className={input}/><datalist id="canonical-supplier-options">{canonicalSuppliers.map(row=><option key={row.supplier_id} value={row.supplier_id}>{row.name}{row.source_profile_id?'':' — no HUB profile'}</option>)}</datalist></Field><Field label="Name"><input required value={form.name} onChange={e=>change('name',e.target.value)} className={input}/></Field><Field label="Image/logo URL"><input value={form.pic} onChange={e=>change('pic',e.target.value)} className={input}/><label className="mt-2 inline-flex cursor-pointer rounded-md border border-blue-200 px-3 py-2 text-sm font-semibold text-blue-700 hover:bg-blue-50">Upload image/logo<input type="file" accept={imageTypes.join(',')} onChange={fileChange} className="sr-only"/></label><Logo src={preview||form.pic}/></Field><Field label="Delivery / product summary" wide><textarea value={form.delivery_product} onChange={e=>change('delivery_product',e.target.value)} className={`${input} min-h-24`}/></Field><Visibility label="Show on homepage" help="Display this supplier in the homepage Top Verified Suppliers section." checked={form.show_on_homepage} onChange={value=>change('show_on_homepage',value)} orderLabel="Homepage display order" order={form.homepage_sort_order} setOrder={value=>change('homepage_sort_order',value)}/><Visibility label="Show in all verified suppliers" help="Display this supplier in the public list of all verified suppliers." checked={form.show_public_website} onChange={value=>change('show_public_website',value)} orderLabel="Supplier directory display order" order={form.public_directory_sort_order} setOrder={value=>change('public_directory_sort_order',value)}/><Check label="Public profile active" help="Allow this verified supplier profile to be published." checked={form.is_public} onChange={value=>change('is_public',value)}/><Check label="Active" help="Keep this Verified Supplier record active." checked={form.is_active} onChange={value=>change('is_active',value)}/></div>}
function Visibility({label,help,checked,onChange,orderLabel,order,setOrder}:{label:string;help:string;checked:boolean;onChange:(v:boolean)=>void;orderLabel:string;order:string;setOrder:(v:string)=>void}){return <div className="rounded-lg border p-4"><Check label={label} help={help} checked={checked} onChange={onChange}/><label className="mt-4 block text-sm font-semibold">{orderLabel}<input type="number" value={order} onChange={e=>setOrder(e.target.value)} className={input}/><span className="mt-1 block text-xs font-normal text-slate-500">Lower values appear first.</span></label></div>}
function Check({label,help,checked,onChange}:{label:string;help:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="flex items-start gap-3"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="mt-1 h-4 w-4"/><span><span className="block font-semibold">{label}</span><span className="block text-sm text-slate-500">{help}</span></span></label>}
function Field({label,wide=false,children}:{label:string;wide?:boolean;children:ReactNode}){return <label className={wide?'md:col-span-2':''}><span className="text-sm font-semibold text-slate-700">{label}</span>{children}</label>}
function Logo({src}:{src:string}){return <div className="mt-2 flex h-20 w-24 items-center justify-center overflow-hidden rounded-lg border bg-slate-50">{src&&validImage(src)?<img src={src} alt="" className="h-full w-full object-contain p-2"/>:<span className="text-xs text-slate-400">No image</span>}</div>}
function Badge({on,children}:{on:boolean;children:ReactNode}){return <span className={`rounded-full px-2 py-1 font-semibold ${on?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{on?'Shown':'Hidden'} · {children}</span>}
function NavButton({href,onClick,children}:{href?:string;onClick?:()=>void;children:ReactNode}){return <HubButton href={href} onClick={onClick} className="border border-white bg-indigo-700 text-white shadow-lg hover:bg-blue-200 hover:text-slate-950">{children}</HubButton>}
function Notice({children,error=false}:{children:ReactNode;error?:boolean}){return <div className={`mb-6 rounded-lg border px-4 py-3 text-sm ${error?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{children}</div>}
function Confirm({cancel,confirm}:{cancel:()=>void;confirm:()=>void}){return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/70 p-4"><div className="rounded-xl bg-white p-6 text-slate-950"><h2 className="text-xl font-bold">Delete Verified Supplier?</h2><p className="mt-2 text-sm text-slate-600">This action cannot be undone.</p><div className="mt-5 flex justify-end gap-2"><button onClick={cancel} className="rounded-md border px-4 py-2">Cancel</button><button onClick={confirm} className="rounded-md bg-red-700 px-4 py-2 font-bold text-white">Delete</button></div></div></div>}
