'use client';
import {useCallback,useEffect,useState} from 'react';

const input='w-full min-w-28 rounded-md border border-slate-300 px-2 py-2 text-sm focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100';
const blankContact={contact_name:'',contact_position:'',department:'',contact_email:'',contact_phone:'',mobile_phone:'',contact_whatsapp:'',contact_notes:'',is_primary:false,is_active:true};
const blankEmail={email:'',email_type:'quotes',contact_id:'',contact_name:'',contact_role:'',is_active:true,is_verified:false,consented:false,can_send_quotes:false};
const blankEvidence={evidence_reference:'',evidence_type:'supplier_email',confirmation_date:new Date().toISOString().slice(0,10),admin_note:''};
type Props={supplierId:string|null;onClose:()=>void;onSaved:()=>void};

const authorization=(row:any)=>!row.is_active?'Inactive':!row.is_verified?'Verification required':!row.consented?'Consent required':!row.can_send_quotes?'Quote permission required':'Authorized for inbound Quotes';
const json=async(response:Response)=>{const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error([body.error,body.detail].filter(Boolean).join(' ')||'Request failed.');return body};

export default function SupplierDetailsModal({supplierId,onClose,onSaved}:Props){
 const [data,setData]=useState<any>(null),[tab,setTab]=useState('company'),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');
 const [newContact,setNewContact]=useState<any>(blankContact),[newEmail,setNewEmail]=useState<any>(blankEmail),[contactDraft,setContactDraft]=useState<any>(null),[emailDraft,setEmailDraft]=useState<any>(null);
 const [evidence,setEvidence]=useState<any>(null),[confirmAction,setConfirmAction]=useState<any>(null);
 const load=useCallback(async()=>{if(!supplierId)return;setLoading(true);setError('');setSuccess('');setData(null);setContactDraft(null);setEmailDraft(null);try{const body=await json(await fetch(`/api/admin/verified-suppliers/${encodeURIComponent(supplierId)}`,{cache:'no-store'}));setData({...body,details:body.details||{},supplier:body.supplier||{},contacts:body.contacts||[],emailAddresses:body.emailAddresses||body.emails||[],audit:body.audit||[],quarantinedMessages:body.quarantinedMessages||[]})}catch(e){setError(e instanceof Error?e.message:'Unable to load supplier details.')}finally{setLoading(false)}},[supplierId]);
 useEffect(()=>{if(supplierId){setNewContact(blankContact);setNewEmail(blankEmail);void load()}else{setData(null);setError('');setSuccess('')}},[supplierId,load]);
 if(!supplierId)return null;
 const change=(group:string,key:string,value:any)=>setData((d:any)=>({...d,[group]:{...d[group],[key]:value}}));
 const mutate=async(url:string,method:string,payload?:any)=>json(await fetch(url,{method,headers:payload?{'content-type':'application/json'}:undefined,body:payload?JSON.stringify(payload):undefined}));
 const saveProfile=async()=>{setSaving(true);setError('');try{await mutate(`/api/admin/verified-suppliers/${encodeURIComponent(supplierId)}`,'PATCH',{supplier:data.supplier,details:data.details});setSuccess('Supplier profile saved.');onSaved()}catch(e){setError(e instanceof Error?e.message:'Save failed.')}finally{setSaving(false)}};
 const addContact=async()=>{if(saving)return;setSaving(true);setError('');try{const body=await mutate(`/api/admin/verified-suppliers/${encodeURIComponent(supplierId)}/contacts`,'POST',newContact);setData((d:any)=>({...d,contacts:[...d.contacts,body.contact]}));setNewContact(blankContact);setSuccess('Contact added successfully.')}catch(e){setError(e instanceof Error?e.message:'Contact could not be added.')}finally{setSaving(false)}};
 const saveContact=async()=>{if(!contactDraft||saving)return;setSaving(true);setError('');try{const body=await mutate(`/api/admin/verified-suppliers/${encodeURIComponent(supplierId)}/contacts/${contactDraft.contact_id}`,'PATCH',contactDraft);setData((d:any)=>({...d,contacts:d.contacts.map((r:any)=>r.contact_id===body.contact.contact_id?body.contact:r)}));setContactDraft(null);setSuccess('Contact updated successfully.')}catch(e){setError(e instanceof Error?e.message:'Contact could not be updated.')}finally{setSaving(false)}};
 const removeContactNow=async(row:any)=>{setConfirmAction(null);setSaving(true);try{const body=await mutate(`/api/admin/verified-suppliers/${encodeURIComponent(supplierId)}/contacts/${row.contact_id}`,'DELETE');if(body.softDeactivated)setData((d:any)=>({...d,contacts:d.contacts.map((r:any)=>r.contact_id===row.contact_id?{...r,is_active:false}:r)}));else setData((d:any)=>({...d,contacts:d.contacts.filter((r:any)=>r.contact_id!==row.contact_id)}));setSuccess(body.softDeactivated?'Contact deactivated because linked records exist.':'Contact removed.')}catch(e){setError(e instanceof Error?e.message:'Contact could not be removed.')}finally{setSaving(false)}};
 const removeContact=(row:any)=>setConfirmAction({message:'Remove this contact? Contacts with linked history will be deactivated instead of deleted.',run:()=>removeContactNow(row)});
 const addEmail=async()=>{if(saving)return;setSaving(true);setError('');try{const body=await mutate(`/api/admin/verified-suppliers/${encodeURIComponent(supplierId)}/emails`,'POST',newEmail);setData((d:any)=>({...d,emailAddresses:[...d.emailAddresses,body.email]}));setNewEmail(blankEmail);setSuccess('Email address added successfully.')}catch(e){setError(e instanceof Error?e.message:'Email could not be added.')}finally{setSaving(false)}};
 const persistEmail=async(payload:any)=>{if(!emailDraft||saving)return;setSaving(true);setError('');try{const body=await mutate(`/api/admin/verified-suppliers/${encodeURIComponent(supplierId)}/emails/${emailDraft.id}`,'PATCH',{...emailDraft,...payload});setData((d:any)=>({...d,emailAddresses:d.emailAddresses.map((r:any)=>r.id===body.email.id?body.email:r)}));setEmailDraft(null);setEvidence(null);setSuccess('Email address updated successfully.')}catch(e){setError(e instanceof Error?e.message:'Email could not be updated.')}finally{setSaving(false)}};
 const saveEmail=()=>{if(!emailDraft||saving)return;const saved=data.emailAddresses.find((r:any)=>r.id===emailDraft.id);if((emailDraft.is_verified&&!saved.is_verified)||(emailDraft.consented&&!saved.consented)){setEvidence({...blankEvidence});return}void persistEmail({})};
 const confirmEvidence=()=>{if(!evidence?.evidence_reference.trim()||!evidence?.admin_note.trim()||!evidence?.confirmation_date){setError('Evidence reference, confirmation date, and Admin note are required.');return}void persistEmail(evidence)};
 const removeEmailNow=async(row:any)=>{setConfirmAction(null);setSaving(true);try{await mutate(`/api/admin/verified-suppliers/${encodeURIComponent(supplierId)}/emails/${row.id}`,'DELETE');setData((d:any)=>({...d,emailAddresses:d.emailAddresses.filter((r:any)=>r.id!==row.id)}));setSuccess('Email address removed.')}catch(e){setError(e instanceof Error?e.message:'Email could not be removed.')}finally{setSaving(false)}};
 const removeEmail=(row:any)=>setConfirmAction({message:'Remove this email address?',run:()=>removeEmailNow(row)});
 const tabs=[['company','Company profile'],['public','Public profile'],['contacts','Contacts'],['emails','Email authorization'],['admin','Administration']];
 return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/70 p-3" role="dialog" aria-modal="true"><div className="relative flex max-h-[92vh] w-full max-w-[1180px] flex-col overflow-hidden rounded-2xl bg-white text-slate-900 shadow-2xl">
  <header className="flex items-start justify-between border-b p-5"><div><h2 className="text-2xl font-bold">Supplier details</h2><p className="mt-1 font-mono text-xs text-slate-500">{supplierId}</p></div><button onClick={onClose} className="rounded-md px-3 py-2 text-xl hover:bg-slate-100" aria-label="Close">×</button></header>
  <nav className="flex gap-1 overflow-x-auto border-b bg-slate-50 px-4 py-2">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`whitespace-nowrap rounded-md px-3 py-2 text-sm font-semibold ${tab===id?'bg-blue-600 text-white':'text-slate-600 hover:bg-white'}`}>{label}</button>)}</nav>
  <div className="overflow-y-auto p-5">{error&&<div className="mb-4 flex items-center justify-between rounded-md bg-red-50 p-3 text-sm text-red-700"><span>{error}</span>{!data&&<button onClick={load} className="font-bold underline">Retry</button>}</div>}{success&&<div className="mb-4 rounded-md bg-emerald-50 p-3 text-sm text-emerald-700">{success}</div>}{loading?<p>Loading supplier details…</p>:data&&<>
   {tab==='company'&&<Profile details={data.details} change={change}/>} {tab==='public'&&<Public supplier={data.supplier} change={change}/>} 
   {tab==='contacts'&&<Contacts rows={data.contacts} draft={contactDraft} setDraft={setContactDraft} add={newContact} setAdd={setNewContact} addRow={addContact} save={saveContact} remove={removeContact} saving={saving} refresh={load}/>} 
   {tab==='emails'&&<Emails rows={data.emailAddresses} contacts={data.contacts} draft={emailDraft} setDraft={setEmailDraft} add={newEmail} setAdd={setNewEmail} addRow={addEmail} save={saveEmail} remove={removeEmail} saving={saving} refresh={load}/>} 
   {tab==='admin'&&<Admin data={data} change={change}/>} </>}</div>
  <footer className="flex justify-end gap-2 border-t p-4"><button onClick={onClose} className="rounded-md border px-4 py-2">Close</button><button onClick={saveProfile} disabled={saving||loading||!data} className="rounded-md bg-blue-600 px-4 py-2 font-semibold text-white disabled:opacity-50">{saving?'Saving…':'Save profile'}</button></footer>
  {evidence&&<div className="absolute inset-0 z-20 flex items-center justify-center bg-slate-950/50 p-4"><div className="w-full max-w-lg rounded-xl bg-white p-5 shadow-2xl"><h3 className="text-lg font-bold">Confirm authorization evidence</h3><p className="mt-1 text-sm text-slate-600">Required for manual verification or supplier consent.</p><div className="mt-4 grid gap-3"><label><span className="text-sm font-semibold">Evidence reference *</span><input className={input} value={evidence.evidence_reference} onChange={e=>setEvidence({...evidence,evidence_reference:e.target.value})}/></label><label><span className="text-sm font-semibold">Evidence type *</span><select className={input} value={evidence.evidence_type} onChange={e=>setEvidence({...evidence,evidence_type:e.target.value})}><option value="supplier_email">Supplier email</option><option value="signed_agreement">Signed agreement</option><option value="supplier_portal_confirmation">Supplier portal confirmation</option><option value="other">Other</option></select></label><label><span className="text-sm font-semibold">Confirmation date *</span><input type="date" className={input} value={evidence.confirmation_date} onChange={e=>setEvidence({...evidence,confirmation_date:e.target.value})}/></label><label><span className="text-sm font-semibold">Admin reason or note *</span><textarea className={input} value={evidence.admin_note} onChange={e=>setEvidence({...evidence,admin_note:e.target.value})}/></label></div><div className="mt-5 flex justify-end gap-2"><button onClick={()=>{setEvidence(null);setEmailDraft(null)}} className="rounded-md border px-4 py-2">Cancel</button><button onClick={confirmEvidence} disabled={saving} className="rounded-md bg-blue-600 px-4 py-2 font-semibold text-white disabled:opacity-50">Confirm</button></div></div></div>}
  {confirmAction&&<div className="absolute inset-0 z-20 flex items-center justify-center bg-slate-950/50 p-4"><div className="w-full max-w-md rounded-xl bg-white p-5 shadow-2xl"><h3 className="text-lg font-bold">Please confirm</h3><p className="mt-2 text-sm text-slate-600">{confirmAction.message}</p><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setConfirmAction(null)} className="rounded-md border px-4 py-2">Cancel</button><button onClick={confirmAction.run} className="rounded-md bg-red-600 px-4 py-2 font-semibold text-white">Confirm</button></div></div></div>}
 </div></div>
}

function Profile({details,change}:any){const fields=['legal_company_name','display_name','detailed_description','product_categories','country','city','company_address','postal_code','website','phone','secondary_phone','whatsapp','registration_number','tax_number','primary_company_email','correspondence_email','supplier_user_id'];return <div className="grid gap-4 sm:grid-cols-2">{fields.map(k=><label key={k} className={['detailed_description','product_categories','company_address'].includes(k)?'sm:col-span-2':''}><span className="text-sm font-semibold">{k.replaceAll('_',' ')}</span><input className={input} value={details[k]||''} onChange={e=>change('details',k,e.target.value)}/></label>)}</div>}
function Public({supplier,change}:any){return <div className="grid gap-4 sm:grid-cols-2">{['name','pic','delivery_product','public_short_description','public_country'].map(k=><label key={k}><span className="text-sm font-semibold">{k.replaceAll('_',' ')}</span><input className={input} value={supplier[k]||''} onChange={e=>change('supplier',k,e.target.value)}/></label>)}{[['show_on_homepage','Show on homepage'],['show_public_website','Show in all verified suppliers'],['is_public','Public profile active'],['is_active','Active']].map(([k,l])=><label key={k} className="flex items-center gap-2"><input type="checkbox" checked={!!supplier[k]} onChange={e=>change('supplier',k,e.target.checked)}/>{l}</label>)}<label><span className="text-sm font-semibold">Homepage display order</span><input type="number" className={input} value={supplier.homepage_sort_order??0} onChange={e=>change('supplier','homepage_sort_order',e.target.value)}/></label><label><span className="text-sm font-semibold">Supplier directory display order</span><input type="number" className={input} value={supplier.public_directory_sort_order??0} onChange={e=>change('supplier','public_directory_sort_order',e.target.value)}/></label></div>}
const cell=(draft:any,setDraft:any,key:string,type='text')=>type==='checkbox'?<input type="checkbox" checked={!!draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.checked})}/>:<input className={input} value={draft[key]||''} onChange={e=>setDraft({...draft,[key]:e.target.value})}/>;
function Contacts({rows,draft,setDraft,add,setAdd,addRow,save,remove,saving,refresh}:any){const f=(k:string,type='text')=>cell(add,setAdd,k,type);return <section><div className="mb-3 flex items-center justify-between"><h3 className="text-lg font-bold">Existing contacts</h3><button onClick={refresh} className="rounded-md border px-3 py-2 text-sm">Refresh contacts</button></div>{rows.length===0?<p className="rounded-md bg-slate-50 p-4 text-sm text-slate-600">No contacts have been added for this supplier.</p>:<div className="overflow-x-auto"><table className="min-w-[1400px] w-full text-left text-xs"><thead><tr className="bg-slate-50">{['Contact name','Job title','Department','Phone','Mobile phone','WhatsApp','Primary email','Contact type','Primary contact','Active','Actions'].map(x=><th key={x} className="border-b p-2">{x}</th>)}</tr></thead><tbody>{rows.map((r:any)=>{const edit=draft?.contact_id===r.contact_id,d=edit?draft:r;return <tr key={r.contact_id} className={!r.is_active?'bg-slate-100 text-slate-500':''}>{['contact_name','contact_position','department','contact_phone','mobile_phone','contact_whatsapp','contact_email'].map(k=><td key={k} className="border-b p-2">{edit?cell(d,setDraft,k):d[k]||'—'}</td>)}<td className="border-b p-2">Company contact</td><td className="border-b p-2">{edit?cell(d,setDraft,'is_primary','checkbox'):(d.is_primary?'Yes':'No')}</td><td className="border-b p-2">{edit?cell(d,setDraft,'is_active','checkbox'):<Badge good={d.is_active} text={d.is_active?'Active':'Inactive'}/>}</td><td className="border-b p-2"><div className="flex gap-1">{edit?<><button onClick={save} className="text-blue-700">Save</button><button onClick={()=>setDraft(null)}>Cancel</button></>:<><button onClick={()=>setDraft({...r})} className="text-blue-700">Edit</button><button onClick={()=>setDraft({...r,is_active:!r.is_active})}>{r.is_active?'Deactivate':'Activate'}</button><button onClick={()=>remove(r)} className="text-red-700">Remove</button></>}</div></td></tr>})}</tbody></table></div>}
 <h3 className="mb-3 mt-6 text-lg font-bold">Add new contact</h3><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{['contact_name','contact_position','department','contact_phone','mobile_phone','contact_whatsapp','contact_email'].map(k=><label key={k}><span className="text-xs font-semibold">{k.replaceAll('_',' ')}</span>{f(k)}</label>)}<label className="flex items-center gap-2">{f('is_primary','checkbox')} Primary contact</label><button disabled={saving} onClick={addRow} className="rounded-md bg-blue-600 px-3 py-2 font-semibold text-white disabled:opacity-50">Add contact</button></div></section>}
function Emails({rows,contacts,draft,setDraft,add,setAdd,addRow,save,remove,saving,refresh}:any){const renderSelect=(d:any,set:any,k:string,values:any[])=><select className={input} value={d[k]||''} onChange={e=>set({...d,[k]:e.target.value})}>{values.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>;return <section><div className="mb-3 flex items-center justify-between"><h3 className="text-lg font-bold">Existing email addresses</h3><button onClick={refresh} className="rounded-md border px-3 py-2 text-sm">Refresh</button></div>{rows.length===0?<p className="rounded-md bg-slate-50 p-4 text-sm text-slate-600">No email addresses have been added for this supplier.</p>:<div className="overflow-x-auto"><table className="min-w-[1320px] w-full text-left text-xs"><thead><tr className="bg-slate-50">{['Email','Email type','Related contact','Active','Verified','Consent','Can send Quotes','Authorized for inbound Quotes','Last updated','Actions'].map(x=><th key={x} className="border-b p-2">{x}</th>)}</tr></thead><tbody>{rows.map((r:any)=>{const edit=draft?.id===r.id,d=edit?draft:r,status=authorization(r),dirty=edit&&JSON.stringify(d)!==JSON.stringify(r);return <tr key={r.id} className={!r.is_active?'bg-slate-100 text-slate-500':''}><td className="border-b p-2">{edit?cell(d,setDraft,'email'):d.email}</td><td className="border-b p-2">{edit?renderSelect(d,setDraft,'email_type',['primary','correspondence','quotes','manager','accounting','logistics','support','alternative'].map(x=>[x,x])):d.email_type}</td><td className="border-b p-2">{edit?renderSelect(d,setDraft,'contact_id',[['','None'],...contacts.map((c:any)=>[c.contact_id,c.contact_name||c.contact_id])]):contacts.find((c:any)=>c.contact_id===d.contact_id)?.contact_name||d.contact_name||'—'}</td>{['is_active','is_verified','consented','can_send_quotes'].map(k=><td key={k} className="border-b p-2">{edit?cell(d,setDraft,k,'checkbox'):(d[k]?'Yes':'No')}</td>)}<td className="border-b p-2"><Badge good={status==='Authorized for inbound Quotes'} text={status}/>{dirty&&<div className="mt-1 font-semibold text-blue-700">Unsaved changes</div>}</td><td className="border-b p-2">{r.updated_at?new Date(r.updated_at).toLocaleString():'—'}</td><td className="border-b p-2"><div className="flex gap-1">{edit?<><button onClick={save} className="text-blue-700">Save</button><button onClick={()=>setDraft(null)}>Cancel</button></>:<><button onClick={()=>setDraft({...r})} className="text-blue-700">Edit</button><button onClick={()=>remove(r)} className="text-red-700">Remove</button></>}</div></td></tr>})}</tbody></table></div>}
 <h3 className="mb-3 mt-6 text-lg font-bold">Add new email</h3><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><input className={input} placeholder="Email" value={add.email} onChange={e=>setAdd({...add,email:e.target.value})}/>{renderSelect(add,setAdd,'email_type',['primary','correspondence','quotes','manager','accounting','logistics','support','alternative'].map(x=>[x,x]))}{renderSelect(add,setAdd,'contact_id',[['','Related contact (optional)'],...contacts.map((c:any)=>[c.contact_id,c.contact_name||c.contact_id])])}<button disabled={saving} onClick={addRow} className="rounded-md bg-blue-600 px-3 py-2 font-semibold text-white disabled:opacity-50">Add email</button></div></section>}
function Badge({good,text}:any){return <span className={`inline-flex rounded-full px-2 py-1 font-semibold ${good?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-800'}`}>{text}</span>}
function Admin({data,change}:any){return <div className="grid gap-4"><label><span className="text-sm font-semibold">Internal supplier status</span><select className={input} value={data.details.administrative_status||'active'} onChange={e=>change('details','administrative_status',e.target.value)}>{['active','inactive','pending_review','suspended'].map(x=><option key={x}>{x}</option>)}</select></label><label><span className="text-sm font-semibold">Internal admin notes</span><textarea className={input} value={data.details.internal_admin_notes||''} onChange={e=>change('details','internal_admin_notes',e.target.value)}/></label><h3 className="font-bold">Authorization audit</h3>{data.audit.map((a:any)=><div key={a.id} className="border-b py-2 text-xs">{new Date(a.created_at).toLocaleString()} — {a.action}</div>)}</div>}
