import { NextRequest, NextResponse } from 'next/server';
import { createAdminClient } from '../../../../../lib/supabase/admin';
import { createClient } from '../../../../../lib/supabase/server';
import {buildCanonicalAllocationViews} from '../../../../../lib/rfqs/canonical-allocation-view';

const fail=(error:string,status:number)=>NextResponse.json({error},{status});
const safeMatchState=(row:any)=>row.review_status==='pending'||row.normalization_status==='needs_review'?'Offer requires review':row.rfq_item_id||row.bom_item_id?'Matched':'Unmatched';

export async function GET(_request:NextRequest,{params}:{params:Promise<{rfqId:string}>}){
  const {rfqId}=await params;const userClient=await createClient();const {data:{user}}=await userClient.auth.getUser();
  if(!user)return fail('You must be signed in to view this RFQ.',401);
  const database=createAdminClient();if(!database)return fail('RFQ details are temporarily unavailable.',503);
  const header=await database.from('rfq_orders0').select('*').eq('rfq_id',rfqId).maybeSingle();
  if(header.error)return fail('The RFQ could not be loaded.',500);if(!header.data||header.data.customer_id!==user.id)return fail('RFQ not found.',404);
  const chainId=header.data.procurement_chain_id;
  const [items,preferences,bom,progress,responses,allocations,invoicedItems]=await Promise.all([
    database.from('rfq_order_items0').select('rfq_item_id,rfq_id,line_number,part_number,manufacturer,description,requested_quantity,quantity_unit,target_unit_price,currency,validation_status,verification_result,source_bom_item_id').eq('rfq_id',rfqId).order('line_number'),
    chainId?database.from('procurement_order_preferences').select('search_priority,max_lead_time_days,supplier_countries,allow_independent_suppliers,allow_alternatives,allow_split_delivery,budget_amount,budget_currency,certificate_requirements').eq('procurement_chain_id',chainId).eq('customer_user_id',user.id).maybeSingle():Promise.resolve({data:null,error:null}),
    header.data.source_bom_upload_id?database.from('customer_bom_uploads').select('id,original_file_name,document_name,status').eq('id',header.data.source_bom_upload_id).eq('user_id',user.id).maybeSingle():Promise.resolve({data:null,error:null}),
    chainId?database.from('procurement_progress').select('current_stage,current_stage_label').eq('procurement_chain_id',chainId).eq('customer_user_id',user.id).maybeSingle():Promise.resolve({data:null,error:null}),
    chainId?database.from('supplier_responses').select('id,rfq_id,supplier_id,status,needs_review,is_current').eq('procurement_chain_id',chainId):Promise.resolve({data:[],error:null}),
    database.from('procurement_supplier_allocations').select('id,procurement_chain_id,rfq_id,rfq_item_id,supplier_response_item_id,allocated_quantity,selected_unit_price,currency,price_basis_quantity,price_basis_unit,selected_by,selected_at,is_active').eq('rfq_id',rfqId).eq('is_active',true),
    database.from('procurement_invoice_items').select('invoice_id,source_allocation_id,source_rfq_item_id,source_supplier_response_item_id,quantity').not('source_allocation_id','is',null),
  ]);
  if(items.error||responses.error)return fail('RFQ positions could not be loaded.',500);
  const responseRows=(responses.data??[]).filter((row:any)=>!row.rfq_id||row.rfq_id===rfqId),responseIds=responseRows.map((row:any)=>row.id),supplierIds=[...new Set(responseRows.map((row:any)=>String(row.supplier_id)).filter(Boolean))].sort();
  const aliases=new Map(supplierIds.map((id,index)=>[id,`Supplier ${String.fromCharCode(65+index)}`]));
  const positions=responseIds.length?await database.from('supplier_response_items').select('id,supplier_response_id,rfq_item_id,bom_item_id,offered_mpn,offered_manufacturer,offered_quantity,available_quantity,calculated_unit_price,price_amount,price_basis_quantity,price_basis_unit,currency,moq,lead_time_days,package_quantity,condition,date_code_raw,date_code_normalized,certificate_available,response_status,review_status,normalization_status').in('supplier_response_id',responseIds).eq('is_current',true):{data:[],error:null};
  if(positions.error)return fail('Supplier offers could not be loaded.',500);
  const responseSupplier=new Map(responseRows.map((row:any)=>[row.id,String(row.supplier_id)]));
  const itemByBom=new Map((items.data??[]).filter((row:any)=>row.source_bom_item_id).map((row:any)=>[row.source_bom_item_id,row.rfq_item_id]));
  const allocationByOffer=buildCanonicalAllocationViews({allocations:allocations.data??[],invoiceItems:invoicedItems.data??[],rfqId,procurementChainId:chainId,customerId:user.id});
  const safeOffers=(positions.data??[]).map((row:any)=>{const linkedRfqItemId=row.rfq_item_id||itemByBom.get(row.bom_item_id)||null,allocation=allocationByOffer.get(row.id),approved=Boolean(allocation&&allocation.rfqItemId===linkedRfqItemId);return {offerPositionId:row.id,rfqItemId:linkedRfqItemId,supplierAlias:aliases.get(responseSupplier.get(row.supplier_response_id))||'Supplier',offeredMpn:row.offered_mpn,manufacturer:row.offered_manufacturer,offeredQuantity:row.offered_quantity,availableQuantity:row.available_quantity,unitPrice:allocation?.selectedUnitPrice??row.calculated_unit_price??row.price_amount,priceBasisQuantity:row.price_basis_quantity,priceBasisUnit:row.price_basis_unit,currency:allocation?.currency??row.currency,moq:row.moq,leadTimeDays:row.lead_time_days,packaging:row.package_quantity,condition:row.condition,dateCode:row.date_code_normalized||row.date_code_raw,certificateAvailable:row.certificate_available,responseStatus:row.response_status,matchState:safeMatchState({...row,rfq_item_id:linkedRfqItemId}),approved,isApproved:approved,approvalStatus:allocation?.isInvoiced?'invoiced':approved?'approved':'not_approved',allocationId:allocation?.allocationId??null,approvedQuantity:allocation?.approvedQuantity??null,approvedAt:allocation?.approvedAt??null,approvedByRole:allocation?.approvedByRole??null,isInvoiceEligible:approved&&!allocation?.isInvoiced,isInvoiced:Boolean(allocation?.isInvoiced),invoiceId:allocation?.invoiceId??null}});
  const offersByItem=new Map<string,any[]>();for(const offer of safeOffers)if(offer.rfqItemId)offersByItem.set(offer.rfqItemId,[...(offersByItem.get(offer.rfqItemId)??[]),offer]);
  const requestedItems=(items.data??[]).map((item:any)=>{const offers=offersByItem.get(item.rfq_item_id)??[],review=offers.some((offer:any)=>offer.matchState==='Offer requires review'),approved=offers.find((offer:any)=>offer.isApproved),approvedQuantity=Number(approved?.approvedQuantity??0);return {...item,offers,hasApprovedOffer:Boolean(approved),approvedOfferItemId:approved?.offerPositionId??null,approvedSupplierAlias:approved?.supplierAlias??null,totalApprovedQuantity:approvedQuantity,remainingQuantity:Math.max(0,Number(item.requested_quantity??0)-approvedQuantity),isInvoiceEligible:Boolean(approved?.isInvoiceEligible),sourcingState:review?'Offer requires review':offers.length===0?'No supplier offer yet':offers.length===1?'One supplier offer':'Multiple supplier offers'}});
  return NextResponse.json({rfq:{id:header.data.rfq_id,procurementNumber:header.data.procurement_number||header.data.order_number,status:header.data.rfq_status,customerReference:header.data.customer_reference,createdAt:header.data.created_at,requiredDeliveryDate:header.data.deadline_at,currentStage:progress.data?.current_stage||'rfq',currentStageLabel:progress.data?.current_stage_label||'RFQ'},bom:bom.data?{id:bom.data.id,fileName:bom.data.original_file_name||bom.data.document_name,status:bom.data.status}:null,preferences:preferences.data,items:requestedItems,unmatchedOffers:safeOffers.filter((offer:any)=>!offer.rfqItemId).map((offer:any)=>({...offer,matchState:'Offer requires review'})),offerSummary:{supplierCount:supplierIds.length,positionCount:safeOffers.length,matchedCount:safeOffers.filter((offer:any)=>offer.rfqItemId).length,unmatchedCount:safeOffers.filter((offer:any)=>!offer.rfqItemId).length}},{headers:{'cache-control':'private, no-store'}});
}
