-- Manual Supabase SQL Editor migration. Do not run automatically.
-- Phase 10: durable guided search, private supplier discovery, approval-gated outreach and reply linkage.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS public.product_search_sessions (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), reference_number text GENERATED ALWAYS AS ('PS-'||upper(substr(replace(id::text,'-',''),1,10))) STORED UNIQUE,
 owner_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, title text NOT NULL, state text NOT NULL DEFAULT 'interpreting', intent jsonb NOT NULL DEFAULT '{}'::jsonb, customer_progress jsonb NOT NULL DEFAULT '{}'::jsonb,
 selected_candidate_id uuid NULL, preliminary_order_id uuid NULL, bom_upload_id uuid NULL, rfq_id uuid NULL, turn_count integer NOT NULL DEFAULT 1 CHECK(turn_count BETWEEN 0 AND 30), tool_call_count integer NOT NULL DEFAULT 0 CHECK(tool_call_count BETWEEN 0 AND 100), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CHECK(state IN ('interpreting','needs_clarification','searching_internal','internal_candidates_found','searching_octopart','octopart_candidates_found','researching_internet','identifying_potential_products','discovering_suppliers','verifying_supplier_contacts','preparing_outreach','awaiting_admin_approval','sending_outreach','awaiting_supplier_responses','comparing_candidates','awaiting_customer_selection','product_confirmed','sourcing_request_ready','completed','failed'))
); CREATE INDEX IF NOT EXISTS product_search_sessions_owner_updated_idx ON public.product_search_sessions(owner_user_id,updated_at DESC);
CREATE TABLE IF NOT EXISTS public.product_search_candidates (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), session_id uuid NOT NULL REFERENCES public.product_search_sessions(id) ON DELETE CASCADE, source text NOT NULL CHECK(source IN ('internal','octopart','public_manufacturer','public_distributor','ai_unverified')), source_reference text NULL,
 manufacturer text NULL, part_number text NULL, product_name text NOT NULL, category text NULL, technical_parameters jsonb NOT NULL DEFAULT '{}'::jsonb, evidence jsonb NOT NULL DEFAULT '{}'::jsonb, verification_status text NOT NULL CHECK(verification_status IN ('verified_from_public_source','partially_verified','unverified_ai_suggestion','rejected_conflict')), compatibility jsonb NOT NULL DEFAULT '{}'::jsonb,
 review_status text NOT NULL DEFAULT 'pending' CHECK(review_status IN ('pending','approved','rejected')), reviewed_by uuid NULL REFERENCES auth.users(id), reviewed_at timestamptz NULL, created_at timestamptz NOT NULL DEFAULT now()
); CREATE UNIQUE INDEX IF NOT EXISTS product_search_candidates_source_uidx ON public.product_search_candidates(session_id,source,coalesce(source_reference,''));
DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='product_search_sessions_selected_candidate_fk' AND conrelid='public.product_search_sessions'::regclass) THEN ALTER TABLE public.product_search_sessions ADD CONSTRAINT product_search_sessions_selected_candidate_fk FOREIGN KEY(selected_candidate_id) REFERENCES public.product_search_candidates(id) ON DELETE SET NULL; END IF; END $$;
CREATE TABLE IF NOT EXISTS public.product_supplier_candidates (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), session_id uuid NOT NULL REFERENCES public.product_search_sessions(id) ON DELETE CASCADE, product_candidate_id uuid NULL REFERENCES public.product_search_candidates(id) ON DELETE SET NULL, canonical_supplier_id uuid NULL REFERENCES public.suppliers(supplier_id) ON DELETE SET NULL,
 normalized_domain text NULL, company_name text NOT NULL, company_website text NULL, supplier_type text NOT NULL, country text NULL, public_contact_page text NULL, public_sales_email text NULL, public_general_email text NULL, public_phone text NULL, source_urls jsonb NOT NULL DEFAULT '[]'::jsonb, product_evidence jsonb NOT NULL DEFAULT '[]'::jsonb,
 contact_verification_status text NOT NULL DEFAULT 'unverified' CHECK(contact_verification_status IN ('verified_public','verified_existing','unverified','rejected')), discovery_confidence numeric NOT NULL DEFAULT 0 CHECK(discovery_confidence BETWEEN 0 AND 1), decision_status text NOT NULL DEFAULT 'pending' CHECK(decision_status IN ('pending','approved','rejected','excluded')), do_not_contact boolean NOT NULL DEFAULT false, suppression_reason text NULL, reviewed_by uuid NULL REFERENCES auth.users(id), reviewed_at timestamptz NULL, created_at timestamptz NOT NULL DEFAULT now()
); CREATE UNIQUE INDEX IF NOT EXISTS product_supplier_candidates_domain_uidx ON public.product_supplier_candidates(session_id,normalized_domain) WHERE normalized_domain IS NOT NULL;
CREATE TABLE IF NOT EXISTS public.product_sourcing_outreach (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), session_id uuid NOT NULL REFERENCES public.product_search_sessions(id) ON DELETE CASCADE, supplier_candidate_id uuid NOT NULL REFERENCES public.product_supplier_candidates(id) ON DELETE RESTRICT, round_number integer NOT NULL DEFAULT 1 CHECK(round_number BETWEEN 1 AND 20), idempotency_key text NOT NULL UNIQUE, normalized_domain text NULL, recipient_email text NOT NULL,
 subject text NOT NULL, body_text text NOT NULL, status text NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','approved','sending','sent','failed','cancelled','bounced','suppressed')), approved_by uuid NULL REFERENCES auth.users(id), approved_at timestamptz NULL, provider_message_id text NULL, sent_at timestamptz NULL, retry_count integer NOT NULL DEFAULT 0 CHECK(retry_count BETWEEN 0 AND 3), safe_error text NULL, inbound_message_id uuid NULL REFERENCES public.supplier_inbound_messages(id) ON DELETE SET NULL, created_by uuid NOT NULL REFERENCES auth.users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
); CREATE INDEX IF NOT EXISTS product_sourcing_outreach_round_idx ON public.product_sourcing_outreach(session_id,round_number,status); CREATE INDEX IF NOT EXISTS product_sourcing_outreach_cooldown_idx ON public.product_sourcing_outreach(normalized_domain,sent_at DESC) WHERE status='sent';
CREATE TABLE IF NOT EXISTS public.product_search_events (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,session_id uuid NOT NULL REFERENCES public.product_search_sessions(id) ON DELETE CASCADE,actor_user_id uuid NULL REFERENCES auth.users(id),event_type text NOT NULL,from_state text NULL,to_state text NULL,safe_payload jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS product_search_events_session_idx ON public.product_search_events(session_id,created_at DESC);
CREATE TABLE IF NOT EXISTS public.product_finder_internal_authorizations (user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,can_access_discovery boolean NOT NULL DEFAULT false,granted_by uuid NOT NULL REFERENCES auth.users(id),granted_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public.supplier_inbound_messages ADD COLUMN IF NOT EXISTS product_search_session_id uuid NULL REFERENCES public.product_search_sessions(id) ON DELETE SET NULL; ALTER TABLE public.supplier_inbound_messages ADD COLUMN IF NOT EXISTS product_sourcing_outreach_id uuid NULL REFERENCES public.product_sourcing_outreach(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS supplier_inbound_product_search_idx ON public.supplier_inbound_messages(product_search_session_id) WHERE product_search_session_id IS NOT NULL;
ALTER TABLE public.product_search_sessions ENABLE ROW LEVEL SECURITY; ALTER TABLE public.product_search_candidates ENABLE ROW LEVEL SECURITY; ALTER TABLE public.product_supplier_candidates ENABLE ROW LEVEL SECURITY; ALTER TABLE public.product_sourcing_outreach ENABLE ROW LEVEL SECURITY; ALTER TABLE public.product_search_events ENABLE ROW LEVEL SECURITY; ALTER TABLE public.product_finder_internal_authorizations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Customers manage own product searches" ON public.product_search_sessions FOR ALL TO authenticated USING(owner_user_id=auth.uid()) WITH CHECK(owner_user_id=auth.uid());
CREATE POLICY "Customers read own product candidates" ON public.product_search_candidates FOR SELECT TO authenticated USING(EXISTS(SELECT 1 FROM public.product_search_sessions s WHERE s.id=session_id AND s.owner_user_id=auth.uid()));
-- Deliberately no Customer policies on supplier candidates, outreach, private events, or support authorizations.
CREATE POLICY "Internal users read product searches" ON public.product_search_sessions FOR SELECT TO authenticated USING(EXISTS(SELECT 1 FROM public.user_profiles p WHERE p.id=auth.uid() AND (p.role IN ('admin','procurement') OR (p.role='support' AND EXISTS(SELECT 1 FROM public.product_finder_internal_authorizations a WHERE a.user_id=auth.uid() AND a.can_access_discovery)))));
CREATE POLICY "Internal users manage product candidates" ON public.product_search_candidates FOR ALL TO authenticated USING(EXISTS(SELECT 1 FROM public.user_profiles p WHERE p.id=auth.uid() AND p.role IN ('admin','procurement'))) WITH CHECK(EXISTS(SELECT 1 FROM public.user_profiles p WHERE p.id=auth.uid() AND p.role IN ('admin','procurement')));
CREATE POLICY "Authorized internal users manage supplier discovery" ON public.product_supplier_candidates FOR ALL TO authenticated USING(EXISTS(SELECT 1 FROM public.user_profiles p WHERE p.id=auth.uid() AND (p.role IN ('admin','procurement') OR (p.role='support' AND EXISTS(SELECT 1 FROM public.product_finder_internal_authorizations a WHERE a.user_id=auth.uid() AND a.can_access_discovery))))) WITH CHECK(EXISTS(SELECT 1 FROM public.user_profiles p WHERE p.id=auth.uid() AND p.role IN ('admin','procurement')));
CREATE POLICY "Internal users manage sourcing outreach" ON public.product_sourcing_outreach FOR ALL TO authenticated USING(EXISTS(SELECT 1 FROM public.user_profiles p WHERE p.id=auth.uid() AND p.role IN ('admin','procurement'))) WITH CHECK(EXISTS(SELECT 1 FROM public.user_profiles p WHERE p.id=auth.uid() AND p.role IN ('admin','procurement')));
CREATE POLICY "Authorized internal users read product search audit" ON public.product_search_events FOR SELECT TO authenticated USING(EXISTS(SELECT 1 FROM public.user_profiles p WHERE p.id=auth.uid() AND (p.role IN ('admin','procurement') OR (p.role='support' AND EXISTS(SELECT 1 FROM public.product_finder_internal_authorizations a WHERE a.user_id=auth.uid() AND a.can_access_discovery)))));
CREATE POLICY "Admins manage Product Finder support authorization" ON public.product_finder_internal_authorizations FOR ALL TO authenticated USING(EXISTS(SELECT 1 FROM public.user_profiles p WHERE p.id=auth.uid() AND p.role='admin')) WITH CHECK(EXISTS(SELECT 1 FROM public.user_profiles p WHERE p.id=auth.uid() AND p.role='admin'));
NOTIFY pgrst,'reload schema';
