CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Electron Market - AI procurement chat history.
-- Chat history uses exactly two tables: ai_chat_sessions and ai_chat_messages.

CREATE TABLE IF NOT EXISTS public.ai_chat_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  chat_number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  user_id uuid REFERENCES public.user_profiles(id) ON DELETE SET NULL,
  guest_session_id text,
  title text,
  chat_type text NOT NULL DEFAULT 'procurement',
  status text NOT NULL DEFAULT 'active',
  model text NOT NULL DEFAULT 'gpt-5.5',
  api_provider text NOT NULL DEFAULT 'openai',
  first_response_id text,
  latest_response_id text,
  openai_conversation_id text,
  system_prompt_snapshot text,
  model_parameters_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  message_count integer NOT NULL DEFAULT 0,
  total_input_tokens integer NOT NULL DEFAULT 0,
  total_output_tokens integer NOT NULL DEFAULT 0,
  total_tokens integer NOT NULL DEFAULT 0,
  related_entity_type text,
  related_entity_id uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  last_message_at timestamptz
);

CREATE TABLE IF NOT EXISTS public.ai_chat_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  chat_session_id uuid NOT NULL REFERENCES public.ai_chat_sessions(id) ON DELETE CASCADE,
  chat_number bigint,
  user_id uuid REFERENCES public.user_profiles(id) ON DELETE SET NULL,
  guest_session_id text,
  message_order integer NOT NULL,
  turn_number integer NOT NULL,
  role text NOT NULL,
  content text NOT NULL,
  content_json jsonb,
  openai_response_id text,
  previous_response_id text,
  openai_output_item_id text,
  model text,
  request_payload_json jsonb,
  response_payload_json jsonb,
  status text NOT NULL DEFAULT 'completed',
  error_message text,
  input_tokens integer NOT NULL DEFAULT 0,
  output_tokens integer NOT NULL DEFAULT 0,
  total_tokens integer NOT NULL DEFAULT 0,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ai_chat_sessions_user_id_idx ON public.ai_chat_sessions(user_id);
CREATE INDEX IF NOT EXISTS ai_chat_sessions_guest_session_id_idx ON public.ai_chat_sessions(guest_session_id);
CREATE INDEX IF NOT EXISTS ai_chat_sessions_latest_response_id_idx ON public.ai_chat_sessions(latest_response_id);
CREATE INDEX IF NOT EXISTS ai_chat_messages_chat_session_id_idx ON public.ai_chat_messages(chat_session_id);
CREATE INDEX IF NOT EXISTS ai_chat_messages_openai_response_id_idx ON public.ai_chat_messages(openai_response_id);
CREATE UNIQUE INDEX IF NOT EXISTS ai_chat_messages_session_order_unique ON public.ai_chat_messages(chat_session_id, message_order);

ALTER TABLE public.ai_chat_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_chat_messages ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.set_ai_chat_sessions_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS ai_chat_sessions_set_updated_at ON public.ai_chat_sessions;
CREATE TRIGGER ai_chat_sessions_set_updated_at
BEFORE UPDATE ON public.ai_chat_sessions
FOR EACH ROW
EXECUTE FUNCTION public.set_ai_chat_sessions_updated_at();

DROP POLICY IF EXISTS "Users can select own ai chat sessions" ON public.ai_chat_sessions;
CREATE POLICY "Users can select own ai chat sessions"
  ON public.ai_chat_sessions
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own ai chat sessions" ON public.ai_chat_sessions;
CREATE POLICY "Users can insert own ai chat sessions"
  ON public.ai_chat_sessions
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own ai chat sessions" ON public.ai_chat_sessions;
CREATE POLICY "Users can update own ai chat sessions"
  ON public.ai_chat_sessions
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can select own ai chat messages" ON public.ai_chat_messages;
CREATE POLICY "Users can select own ai chat messages"
  ON public.ai_chat_messages
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own ai chat messages" ON public.ai_chat_messages;
CREATE POLICY "Users can insert own ai chat messages"
  ON public.ai_chat_messages
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admins can select ai chat sessions" ON public.ai_chat_sessions;
CREATE POLICY "Admins can select ai chat sessions"
  ON public.ai_chat_sessions
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_profiles
      WHERE user_profiles.id = auth.uid()
        AND user_profiles.role = 'admin'
    )
  );

DROP POLICY IF EXISTS "Admins can select ai chat messages" ON public.ai_chat_messages;
CREATE POLICY "Admins can select ai chat messages"
  ON public.ai_chat_messages
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_profiles
      WHERE user_profiles.id = auth.uid()
        AND user_profiles.role = 'admin'
    )
  );

DROP POLICY IF EXISTS "Guests can select own ai chat sessions" ON public.ai_chat_sessions;
CREATE POLICY "Guests can select own ai chat sessions"
  ON public.ai_chat_sessions
  FOR SELECT
  TO anon
  USING (
    guest_session_id IS NOT NULL
    AND EXISTS (
      SELECT 1 FROM public.ai_api_config
      WHERE ai_api_config.is_enabled = true
        AND ai_api_config.allow_guest_chat = true
    )
  );

DROP POLICY IF EXISTS "Guests can insert ai chat sessions" ON public.ai_chat_sessions;
CREATE POLICY "Guests can insert ai chat sessions"
  ON public.ai_chat_sessions
  FOR INSERT
  TO anon
  WITH CHECK (
    user_id IS NULL
    AND guest_session_id IS NOT NULL
    AND EXISTS (
      SELECT 1 FROM public.ai_api_config
      WHERE ai_api_config.is_enabled = true
        AND ai_api_config.allow_guest_chat = true
    )
  );

DROP POLICY IF EXISTS "Guests can update own ai chat sessions" ON public.ai_chat_sessions;
CREATE POLICY "Guests can update own ai chat sessions"
  ON public.ai_chat_sessions
  FOR UPDATE
  TO anon
  USING (
    user_id IS NULL
    AND guest_session_id IS NOT NULL
    AND EXISTS (
      SELECT 1 FROM public.ai_api_config
      WHERE ai_api_config.is_enabled = true
        AND ai_api_config.allow_guest_chat = true
    )
  )
  WITH CHECK (
    user_id IS NULL
    AND guest_session_id IS NOT NULL
    AND EXISTS (
      SELECT 1 FROM public.ai_api_config
      WHERE ai_api_config.is_enabled = true
        AND ai_api_config.allow_guest_chat = true
    )
  );

DROP POLICY IF EXISTS "Guests can select own ai chat messages" ON public.ai_chat_messages;
CREATE POLICY "Guests can select own ai chat messages"
  ON public.ai_chat_messages
  FOR SELECT
  TO anon
  USING (
    guest_session_id IS NOT NULL
    AND EXISTS (
      SELECT 1 FROM public.ai_api_config
      WHERE ai_api_config.is_enabled = true
        AND ai_api_config.allow_guest_chat = true
    )
  );

DROP POLICY IF EXISTS "Guests can insert ai chat messages" ON public.ai_chat_messages;
CREATE POLICY "Guests can insert ai chat messages"
  ON public.ai_chat_messages
  FOR INSERT
  TO anon
  WITH CHECK (
    user_id IS NULL
    AND guest_session_id IS NOT NULL
    AND EXISTS (
      SELECT 1 FROM public.ai_api_config
      WHERE ai_api_config.is_enabled = true
        AND ai_api_config.allow_guest_chat = true
    )
  );

NOTIFY pgrst, 'reload schema';
