CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Electron Market - Nexar / Octopart request history.
-- Run manually in Supabase SQL Editor before using Octopart request history.

CREATE TABLE IF NOT EXISTS public.octopart_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  request_number bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) UNIQUE,
  user_id uuid NULL REFERENCES auth.users(id) ON DELETE SET NULL,
  chat_session_id uuid NULL,
  source_provider text NOT NULL DEFAULT 'nexar_octopart',
  query_type text NOT NULL DEFAULT 'part_number',
  part_number text NOT NULL,
  normalized_part_number text,
  request_status text NOT NULL DEFAULT 'pending',
  request_payload_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  response_summary_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  raw_response_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  error_message text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.octopart_request_offers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  octopart_request_id uuid NOT NULL REFERENCES public.octopart_requests(id) ON DELETE CASCADE,
  seller_name text,
  part_number text,
  manufacturer text,
  description text,
  available_quantity integer,
  unit_price numeric,
  currency text,
  lead_time_days integer,
  datasheet_url text,
  product_url text,
  source_url text,
  raw_offer_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_octopart_requests_request_number
  ON public.octopart_requests(request_number DESC);
CREATE INDEX IF NOT EXISTS idx_octopart_requests_created_at
  ON public.octopart_requests(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_octopart_requests_user_id
  ON public.octopart_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_octopart_request_offers_request_id
  ON public.octopart_request_offers(octopart_request_id);

CREATE OR REPLACE FUNCTION public.set_octopart_requests_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS octopart_requests_set_updated_at ON public.octopart_requests;
CREATE TRIGGER octopart_requests_set_updated_at
BEFORE UPDATE ON public.octopart_requests
FOR EACH ROW
EXECUTE FUNCTION public.set_octopart_requests_updated_at();

ALTER TABLE public.octopart_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.octopart_request_offers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can select own octopart requests" ON public.octopart_requests;
CREATE POLICY "Users can select own octopart requests"
  ON public.octopart_requests
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own octopart requests" ON public.octopart_requests;
CREATE POLICY "Users can insert own octopart requests"
  ON public.octopart_requests
  FOR INSERT
  TO authenticated
  WITH CHECK (user_id IS NULL OR auth.uid() = user_id);

DROP POLICY IF EXISTS "Admins can select octopart requests" ON public.octopart_requests;
CREATE POLICY "Admins can select octopart requests"
  ON public.octopart_requests
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.user_profiles
      WHERE user_profiles.id = auth.uid()
        AND user_profiles.role = 'admin'
    )
  );

DROP POLICY IF EXISTS "Users can select own octopart request offers" ON public.octopart_request_offers;
CREATE POLICY "Users can select own octopart request offers"
  ON public.octopart_request_offers
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.octopart_requests
      WHERE octopart_requests.id = octopart_request_offers.octopart_request_id
        AND octopart_requests.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Admins can select octopart request offers" ON public.octopart_request_offers;
CREATE POLICY "Admins can select octopart request offers"
  ON public.octopart_request_offers
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.user_profiles
      WHERE user_profiles.id = auth.uid()
        AND user_profiles.role = 'admin'
    )
  );

NOTIFY pgrst, 'reload schema';
