'use client';

import Link from 'next/link';
import ApprovedOfferIndicator from '../../../components/rfq/ApprovedOfferIndicator';
import {useParams,useRouter} from 'next/navigation';
import {useCallback,useEffect,useMemo,useState} from 'react';
import DeleteRfqButton from '../DeleteRfqButton';

const show=(v:unknown)=>v===null||v===undefined||v===''?'—':Array.isArray(v)?v.join(', '):String(v);
const human=(v:unknown)=>show(v).replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const btn='rounded-lg bg-blue-700 px-3 py-2 text-xs font-bold text-white shadow-sm hover:bg-blue-600 disabled:bg-slate-400';

export default function AdminRfqDetailPage(){
  const {rfqId}=useParams<{rfqId:string}>(),router=useRouter();
  const [data,setData]=useState<any>(null),[readiness,setReadiness]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(''),[invoiceModal,setInvoiceModal]=useState(false),[selectedOffer,setSelectedOffer]=useState<any>(null),[selectedItem,setSelectedItem]=useState<any>(null),[allOffers,setAllOffers]=useState<any[]|null>(null),[selectionModal,setSelectionModal]=useState<{offer:any;item:any;quantity:string}|null>(null);
  const load=useCallback(async()=>{setError('');const [a,b]=await Promise.all([fetch(`/api/admin/rfqs/${rfqId}`,{cache:'no-store'}),fetch(`/api/admin/rfqs/${rfqId}/invoice-readiness`,{cache:'no-store'})]);const details=await a.json().catch(()=>({})),ready=await b.json().catch(()=>({}));if(!a.ok)throw new Error(details.error||'RFQ could not be loaded.');setData(details);setReadiness(b.ok?ready:null)},[rfqId]);
  useEffect(()=>{load().catch(e=>setError(e instanceof Error?e.message:'RFQ could not be loaded.'))},[load]);
  const allocationByOffer=useMemo(()=>new Map<string,any>((data?.allocations??[]).map((x:any)=>[x.supplier_response_item_id,x])),[data]);
  const offersByItem=useMemo(()=>{const map=new Map<string,any[]>();for(const offer of data?.offers??[])if(offer.rfq_item_id)map.set(offer.rfq_item_id,[...(map.get(offer.rfq_item_id)??[]),offer]);return map},[data]);
  const openOffer=(offer:any,item?:any)=>{setSelectedOffer(offer);setSelectedItem(item??data?.items?.find((x:any)=>x.rfq_item_id===offer.rfq_item_id)??null)};
  const select=(offer:any,item:any)=>setSelectionModal({offer,item,quantity:String(Math.min(Number(item.requested_quantity),Number(offer.offered_quantity??offer.available_quantity??0),Number(offer.available_quantity??offer.offered_quantity??0)))});
  const confirmSelection=async()=>{if(!selectionModal)return;const amount=Number(selectionModal.quantity);if(!Number.isFinite(amount)||amount<=0){setError('Approved quantity must be greater than zero.');return}setBusy(selectionModal.offer.id);setError('');try{const response=await fetch(`/api/admin/rfqs/${rfqId}/allocations`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({rfqItemId:selectionModal.item.rfq_item_id,supplierResponseItemId:selectionModal.offer.id,allocatedQuantity:amount})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'Selection failed.');setSelectionModal(null);setSelectedOffer(null);await load();router.refresh()}catch(e){setError(e instanceof Error?e.message:'Allocation failed.')}finally{setBusy('')}};
  const deselect=async(id:string)=>{setBusy(id);try{const response=await fetch(`/api/admin/rfqs/${rfqId}/allocations`,{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({allocationId:id})});if(!response.ok)throw new Error((await response.json()).error);await load()}catch(e){setError(e instanceof Error?e.message:'Deselection failed.')}finally{setBusy('')}};
  const createInvoice=async()=>{setBusy('invoice');try{const response=await fetch(`/api/admin/rfqs/${rfqId}/create-invoice`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({idempotencyKey:`manual:${rfqId}`})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error);router.push(result.navigationUrl);router.refresh()}catch(e){setError(e instanceof Error?e.message:'Invoice creation failed.')}finally{setBusy('');setInvoiceModal(false)}};
  if(error&&!data)return <main className="p-8 text-red-700">{error}</main>;if(!data)return <main className="p-8">Loading RFQ…</main>;
  return <main className="min-h-screen bg-slate-100 p-3 sm:p-6"><div className="mx-auto max-w-[1700px] space-y-5">
    <header className="sticky top-3 z-30 rounded-2xl bg-blue-950 p-4 text-white shadow-xl sm:top-4 sm:p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-cyan-300">Admin RFQ</p><h1 className="mt-1 text-2xl font-bold">{data.rfq.procurement_number||data.rfq.order_number}</h1><p className="mt-1 text-xs text-blue-200 sm:text-sm">Canonical RFQ: {data.rfq.rfq_id}</p></div><div className="flex flex-wrap gap-2"><Link href="/admin" className={btn}>Admin HUB</Link>{data.chain?.id&&<Link href={`/admin/procurement-progress/${data.chain.id}`} className={btn}>Procurement chain</Link>}</div></div></header>
    {error&&<div className="rounded-lg bg-red-50 p-3 text-red-700">{error}</div>}
    <Section title="Consolidated RFQ Sourcing Matrix"><div className="overflow-x-auto rounded-xl border"><table className="w-[1380px] table-fixed text-left text-xs"><colgroup>{[50,170,230,110,120,95,140,155,155,155].map((w,i)=><col key={i} style={{width:w}}/>)}</colgroup><thead className="bg-slate-900 text-white"><tr>{['№','Part Num','Name','Requested pcs','Requested price','Responses','Approved','Offer 1','Offer 2','Offer 3'].map(h=><th key={h} className="px-3 py-3 font-bold uppercase tracking-wide">{h}</th>)}</tr></thead><tbody className="divide-y bg-white">{data.items.map((item:any)=>{const offers=offersByItem.get(item.rfq_item_id)??[],approvedIndex=offers.findIndex((offer:any)=>allocationByOffer.get(offer.id)?.buyer_approved),approved=approvedIndex>=0?allocationByOffer.get(offers[approvedIndex].id):null;return <tr key={item.rfq_item_id} className="align-top hover:bg-slate-50"><td className="px-3 py-3 font-bold">{show(item.bom_row??item.line_number)}</td><td className="px-3 py-3 font-semibold text-blue-950">{show(item.part_number)}</td><td className="px-3 py-3"><span className="block truncate" title={item.description||''}>{show(item.description)}</span></td><td className="px-3 py-3">{show(item.requested_quantity)} {show(item.quantity_unit)}</td><td className="px-3 py-3">{item.target_unit_price!=null?`${show(item.currency)} ${show(item.target_unit_price)}`:'—'}</td><td className="px-3 py-3"><ResponseBadge count={offers.length}/><div className="mt-1 text-[10px] text-slate-600">{coverageLabel(offers)}</div>{offers.length>3&&<button onClick={()=>setAllOffers(offers)} className="mt-1 font-bold text-blue-700 underline">+{offers.length-3} more</button>}</td><td className="px-2 py-3 text-center">{approved?<ApprovedOfferIndicator detail={`Offer ${approvedIndex+1} · ${approved.allocated_quantity}${approved.included_in_invoice?' · Invoiced':''}`}/>:<span className="text-slate-400">—</span>}</td>{[0,1,2].map(index=><td key={index} className="px-2 py-2"><OfferCell offer={offers[index]} selected={Boolean(offers[index]&&allocationByOffer.get(offers[index].id)?.buyer_approved)} onOpen={()=>openOffer(offers[index],item)} emptyLabel={index===0?'No offer':'—'}/></td>)}</tr>})}</tbody></table></div></Section>
    {(data.unmatchedOffers??[]).length>0&&<Section title="Unmatched / Review Required Supplier Positions"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.unmatchedOffers.map((offer:any)=><button key={offer.id} onClick={()=>openOffer(offer)} className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-left shadow-sm hover:border-amber-400"><div className="font-bold text-slate-950">{show(offer.supplier_name)}</div><div className="mt-1 truncate text-sm">{show(offer.original_product_name||offer.offered_mpn)}</div><div className="mt-2 text-xs text-amber-900">{show(offer.match_state)} · {offer.matching_confidence!=null?`${Math.round(offer.matching_confidence*100)}%`:'Confidence —'}</div><div className="mt-2 text-xs font-bold text-blue-700">View details</div></button>)}</div></Section>}
    <Section title="RFQ and Invoice Status"><Grid values={[["Customer",data.rfq.customer_company_name],["Status",human(data.rfq.rfq_status)],["BOM",data.bom?.original_file_name||data.bom?.document_name],["Positions",data.items.length],["Mode",human(data.workflow?.execution_mode)],["Fully covered",`${readiness?.coverage?.fullyCoveredItems??0} / ${readiness?.coverage?.rfqItems??data.items.length}`],["Quantity coverage",`${readiness?.coverage?.quantityCoveragePercent??0}%`],["Ready",readiness?.ready?'Yes':'No']]}/>{readiness?.blockers?.length>0&&<ul className="mt-4 list-disc pl-5 text-sm text-red-700">{readiness.blockers.map((x:any,i:number)=><li key={i}>{x.message}</li>)}</ul>}<div className="mt-4 flex flex-wrap gap-3">{data.invoice?<Link href={`/admin/procurement-progress/${data.invoice.procurement_chain_id}#invoice`} className={btn}>Open Invoice</Link>:<button onClick={()=>setInvoiceModal(true)} disabled={!readiness?.ready} className={btn}>Create Invoice from RFQ</button>}<DeleteRfqButton rfqId={rfqId}/></div></Section>
    {selectedOffer&&<OfferModal offer={selectedOffer} item={selectedItem} allocation={allocationByOffer.get(selectedOffer.id)} busy={busy} onClose={()=>setSelectedOffer(null)} onSelect={()=>select(selectedOffer,selectedItem)} onDeselect={(id)=>deselect(id)}/>} 
    {allOffers&&<Modal title={`All ${allOffers.length} supplier offers`} onClose={()=>setAllOffers(null)}><div className="space-y-2">{allOffers.map((offer:any)=><button key={offer.id} onClick={()=>{setAllOffers(null);openOffer(offer)}} className="flex w-full items-center justify-between rounded-lg border p-3 text-left hover:bg-blue-50"><span className="font-semibold">{show(offer.supplier_name)}</span><span>{offerPrice(offer)}</span></button>)}</div></Modal>}
    {invoiceModal&&<Modal title="Create Draft Invoice" onClose={()=>setInvoiceModal(false)}><Grid values={[["Total RFQ positions",readiness.coverage.rfqItems],["Fully covered",readiness.coverage.fullyCoveredItems],["Partially covered",readiness.coverage.partiallyCoveredItems],["Uncovered",readiness.coverage.uncoveredItems],["Invoice mode",readiness.coverage.fullyCoveredItems===readiness.coverage.rfqItems?'Full':'Partial']]}/>{readiness.warnings?.map((x:any,i:number)=><p key={i} className="mt-3 rounded-lg bg-amber-50 p-3 text-amber-800">{x.message}</p>)}<div className="mt-6 flex justify-end gap-3"><button onClick={()=>setInvoiceModal(false)} className="rounded-lg border px-4 py-2">Cancel</button><button onClick={createInvoice} disabled={busy==='invoice'} className="rounded-lg bg-emerald-700 px-4 py-2 font-bold text-white">{busy==='invoice'?'Creating…':'Create Draft Invoice'}</button></div></Modal>}
    {selectionModal&&<SelectionConfirmation value={selectionModal} busy={busy===selectionModal.offer.id} onQuantity={quantity=>setSelectionModal({...selectionModal,quantity})} onCancel={()=>setSelectionModal(null)} onConfirm={confirmSelection}/>} 
  </div></main>;
}

function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border bg-white p-4 shadow-sm sm:p-5"><h2 className="mb-4 text-xl font-bold text-blue-950">{title}</h2>{children}</section>}
function Grid({values}:{values:Array<[string,unknown]>}){return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{values.map(([k,v])=><div key={k} className="rounded-lg bg-slate-50 p-3"><div className="text-xs font-bold uppercase text-slate-500">{k}</div><div className="mt-1 font-semibold">{show(v)}</div></div>)}</div>}
function ResponseBadge({count}:{count:number}){return <span className={`inline-flex rounded-full px-2 py-1 font-bold ${count===0?'bg-slate-100 text-slate-600':count===1?'bg-blue-100 text-blue-800':'bg-emerald-100 text-emerald-800'}`}>{count} {count===1?'offer':'offers'}</span>}
function offerPrice(offer:any){if(!offer)return '—';if(offer.calculated_unit_price==null)return 'Price missing';if(!offer.currency)return 'Currency missing';return `${offer.currency} ${offer.calculated_unit_price} / ${offer.price_basis_unit||'unit'}`}
function coverageLabel(offers:any[]){if(!offers.length)return 'No offers';if(offers.some(o=>o.quantity_coverage_status==='full'))return 'Full coverage';if(offers.some(o=>o.quantity_coverage_status==='partial'))return 'Partial · More sourcing';if(offers.some(o=>o.review_status==='pending'))return 'Review required';return 'Quantity unknown'}
function OfferCell({offer,selected,onOpen,emptyLabel}:{offer:any;selected:boolean;onOpen:()=>void;emptyLabel:string}){if(!offer)return <div className="py-3 text-center text-slate-400">{emptyLabel}</div>;return <button type="button" onClick={onOpen} aria-label={`View offer from ${show(offer.supplier_name)}`} className={`min-h-16 w-full rounded-lg border p-2 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-blue-500 ${selected?'border-emerald-500 bg-emerald-50':'border-blue-200 bg-blue-50'}`}><span className="block font-bold text-blue-950">{offerPrice(offer)}</span><span className="mt-1 block truncate text-[10px] text-slate-600">{show(offer.supplier_name)}</span>{selected&&<span className="mt-1 block"><ApprovedOfferIndicator/></span>}{offer.commercial_review_required&&<span className="mt-1 block text-[10px] font-bold text-amber-700">Review required</span>}</button>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/70 p-4" role="dialog" aria-modal="true"><div className="max-h-[90vh] w-full max-w-5xl overflow-auto rounded-2xl bg-white p-5 shadow-2xl"><div className="mb-5 flex items-center justify-between gap-3"><h2 className="text-2xl font-bold text-blue-950">{title}</h2><button onClick={onClose} className="rounded-lg border px-3 py-2 font-bold">Close</button></div>{children}</div></div>}
function SelectionConfirmation({value,busy,onQuantity,onCancel,onConfirm}:{value:{offer:any;item:any;quantity:string};busy:boolean;onQuantity:(value:string)=>void;onCancel:()=>void;onConfirm:()=>void}){const {offer,item}=value,total=Number(value.quantity||0)*Number(offer.calculated_unit_price||0)/Number(offer.price_basis_quantity||1);return <Modal title="Confirm supplier selection" onClose={onCancel}><Grid values={[["RFQ position",item.line_number],["Requested MPN",item.part_number],["Requested quantity",`${item.requested_quantity} ${item.quantity_unit||''}`],["Supplier",offer.supplier_name],["Offered MPN",offer.offered_mpn],["Offered quantity",offer.offered_quantity],["Available quantity",offer.available_quantity],["Unit price",offer.calculated_unit_price],["Currency",offer.currency],["Price basis",`${show(offer.price_basis_quantity)} / ${show(offer.price_basis_unit)}`],["Line total",`${show(offer.currency)} ${total.toFixed(2)}`],["MOQ",offer.moq],["Lead time",offer.lead_time_days!=null?`${offer.lead_time_days} days`:null],["Commercial conditions",offer.commercial_review_state],["Matching warning",offer.rfq_item_id===item.rfq_item_id?'Existing match confirmed':'This offer will be manually associated with the selected RFQ position.']]}/><label className="mt-5 block max-w-sm text-sm font-bold text-slate-700">Approved quantity<input type="number" min="0" step="any" value={value.quantity} onChange={event=>onQuantity(event.target.value)} className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2"/></label><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onCancel} disabled={busy} className="rounded-lg border px-4 py-2">Cancel</button><button type="button" onClick={onConfirm} disabled={busy} className="rounded-lg bg-blue-700 px-4 py-2 font-bold text-white disabled:opacity-60">{busy?'Saving…':'Confirm selection'}</button></div></Modal>}
function OfferModal({offer,item,allocation,busy,onClose,onSelect,onDeselect}:{offer:any;item:any;allocation:any;busy:string;onClose:()=>void;onSelect:()=>void;onDeselect:(id:string)=>void}){const total=allocation?Number(allocation.allocated_quantity)*Number(allocation.selected_unit_price)/Number(allocation.price_basis_quantity):null;const fields:Array<[string,unknown]>=[['Supplier',offer.supplier_name],['Requested MPN',item?.part_number||offer.requested_mpn],['Offered MPN',offer.offered_mpn],['Manufacturer',offer.offered_manufacturer||offer.requested_manufacturer],['Offered quantity',offer.offered_quantity],['Available quantity',offer.available_quantity],['Selected quantity',allocation?.allocated_quantity],['Unit price',offer.calculated_unit_price],['Currency',offer.currency],['Price basis',`${show(offer.price_basis_quantity)} / ${show(offer.price_basis_unit)}`],['Line total',total],['MOQ',offer.moq],['Lead time',offer.lead_time_days!=null?`${offer.lead_time_days} days`:null],['Packaging',offer.package_quantity],['Condition',offer.condition],['Date code',offer.date_code_normalized||offer.date_code_raw],['Incoterms',offer.commercial_terms?.incoterms||allocation?.delivery_terms],['Payment terms',offer.commercial_terms?.payment_terms],['Validity',offer.quote_valid_until],['Match status',offer.match_state],['Match method',offer.match_method],['Confidence',offer.matching_confidence!=null?`${Math.round(offer.matching_confidence*100)}%`:null],['Warning',offer.review_reason||offer.commercial_review_state],['Quantity coverage',offer.quantity_coverage_status],['Uncovered quantity',offer.uncovered_quantity],['Technical differences',offer.technical_differences],['Source',offer.source_message_id?'Supplier email':'Supplier HUB']];return <Modal title="Supplier Offer Details" onClose={onClose}><Grid values={fields}/>{offer.source_message_id&&<Link href={`/admin/supplier-inbox?messageId=${offer.source_message_id}`} className="mt-4 inline-block font-bold text-blue-700 underline">Open source email and AI processing details</Link>}<div className="mt-6 flex justify-end gap-3">{allocation?<><span className="rounded-lg bg-emerald-50 px-4 py-2 font-bold text-emerald-700">✓ Selected</span><button disabled={busy===allocation.id} onClick={()=>onDeselect(allocation.id)} className="rounded-lg bg-red-700 px-4 py-2 font-bold text-white">Remove selection</button></>:item?<button disabled={busy===offer.id} onClick={onSelect} className="rounded-lg bg-blue-700 px-4 py-2 font-bold text-white">Select this offer</button>:null}</div></Modal>}
