'use client';
import Link from 'next/link';
import {FormEvent,useEffect,useRef,useState} from 'react';
import {usePathname,useRouter,useSearchParams} from 'next/navigation';
import SupplierRequestQuoteButton from '../components/public-request/SupplierRequestQuoteButton';

type Supplier={publicSlug:string;displayName:string;logoUrl:string|null;shortDescription:string|null;country:string|null;city:string|null;supplierType:string|null;categories:string|null;brands:string|null;languages:string[];minimumOrder:number|null;minimumOrderCurrency:string|null;leadTimeMinDays:number|null;leadTimeMaxDays:number|null;responseTimeHours:number|null;incoterms:string[];currencies:string|null;deliveryCoverage:string|null;capabilities:string[];verified:boolean;publicProductCount:number};
type Result={items:Supplier[];page:number;pageSize:number;total:number;totalPages:number};
const filterKeys=['country','supplierType','category','brand','capability','language','currency','deliveryRegion','minOrderMax','leadTimeMax'] as const;
const labels:Record<string,string>={country:'Country',supplierType:'Supplier type',category:'Category',brand:'Brand',capability:'Capability',language:'Language',currency:'Currency',deliveryRegion:'Delivery region',minOrderMax:'Maximum minimum order',leadTimeMax:'Maximum lead time'};
const validImage=(value:string|null)=>Boolean(value&&(/^(https?:\/\/|\/)/.test(value))&&!value.startsWith('blob:'));
const split=(value:string|null)=>value?value.split(',').map(item=>item.trim()).filter(Boolean):[];

export default function SuppliersDirectory(){
 const router=useRouter(),pathname=usePathname(),params=useSearchParams(),drawer=useRef<HTMLDivElement>(null),searchInput=useRef<HTMLInputElement>(null);
 const[data,setData]=useState<Result>({items:[],page:1,pageSize:24,total:0,totalPages:1}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[mobileFilters,setMobileFilters]=useState(false),[query,setQuery]=useState(params.get('q')??''),[draft,setDraft]=useState<Record<string,string>>(()=>Object.fromEntries(filterKeys.map(key=>[key,params.get(key)??''])));
 const activeFilters=filterKeys.filter(key=>params.get(key));
 const navigate=(changes:Record<string,string|null>)=>{const next=new URLSearchParams(params.toString());for(const[key,value]of Object.entries(changes)){if(value)next.set(key,value);else next.delete(key)}if(!Object.hasOwn(changes,'page'))next.set('page','1');router.push(`${pathname}${next.size?`?${next}`:''}`)};
 const load=()=>{setLoading(true);setError('');fetch(`/api/public/suppliers?${params.toString()}`,{cache:'no-store'}).then(async response=>{const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Supplier directory is temporarily unavailable.');setData(body)}).catch(value=>setError(value instanceof Error?value.message:'Supplier directory is temporarily unavailable.')).finally(()=>setLoading(false))};
 useEffect(load,[params]);useEffect(()=>{setQuery(params.get('q')??'');setDraft(Object.fromEntries(filterKeys.map(key=>[key,params.get(key)??''])))},[params]);
 useEffect(()=>{if(!mobileFilters)return;const previous=document.activeElement as HTMLElement;drawer.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape')setMobileFilters(false);if(event.key==='Tab'){const nodes=drawer.current?.querySelectorAll<HTMLElement>('button,input,select,[href],[tabindex]:not([tabindex="-1"])');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus()}},[mobileFilters]);
 const search=(event:FormEvent)=>{event.preventDefault();navigate({q:query.trim()||null})};const apply=()=>{navigate(Object.fromEntries(filterKeys.map(key=>[key,draft[key]||null])));setMobileFilters(false)};const clear=()=>{setQuery('');setDraft(Object.fromEntries(filterKeys.map(key=>[key,''])));setMobileFilters(false);router.push(pathname);searchInput.current?.focus()};
 return <div className="mx-auto w-full max-w-[1440px] px-4 py-10 sm:px-6 lg:px-8"><header className="rounded-3xl bg-gradient-to-br from-[#061b3f] to-[#0b3a7a] px-6 py-10 text-white shadow-xl sm:px-10"><h1 className="text-3xl font-bold sm:text-4xl">Global Supplier Network</h1><p className="mt-3 max-w-3xl text-blue-100">Find verified manufacturers, distributors and sourcing partners from around the world.</p><form onSubmit={search} className="mt-7 flex flex-col gap-3 sm:flex-row"><label htmlFor="supplier-search" className="sr-only">Search suppliers</label><input ref={searchInput} id="supplier-search" type="search" value={query} onChange={event=>setQuery(event.target.value)} maxLength={80} placeholder="Search suppliers, brands, products or capabilities" className="min-w-0 flex-1 rounded-xl border border-white/20 bg-white px-4 py-3 text-slate-950 outline-none focus:ring-2 focus:ring-cyan-300"/><button className="rounded-xl bg-cyan-400 px-6 py-3 font-bold text-blue-950 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white">Search</button>{(params.size>0||query)&&<button type="button" onClick={clear} className="rounded-xl border border-white/30 px-5 py-3 font-semibold">Clear</button>}</form></header>
 <div className="mt-6 flex items-center justify-between gap-3 lg:hidden"><button onClick={()=>setMobileFilters(true)} className="rounded-lg border bg-white px-4 py-2 font-bold">Filters{activeFilters.length?` (${activeFilters.length})`:''}</button><Sort value={params.get('sort')??'recommended'} change={value=>navigate({sort:value})}/></div>
 <div className="mt-8 grid min-w-0 gap-8 lg:grid-cols-[260px_minmax(0,1fr)]"><aside className="hidden lg:block"><div className="sticky top-20 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Filter suppliers</h2><Filters values={draft} change={(key,value)=>setDraft(current=>({...current,[key]:value}))}/><div className="mt-5 flex gap-2"><button onClick={apply} className="flex-1 rounded-lg bg-blue-700 px-3 py-2 font-bold text-white">Apply</button><button onClick={clear} className="rounded-lg border px-3 py-2 font-bold">Clear</button></div></div></aside>
 <section aria-labelledby="supplier-results" className="min-w-0"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 id="supplier-results" className="text-xl font-bold">{loading?'Loading suppliers…':`${data.total} supplier${data.total===1?'':'s'}`}</h2>{activeFilters.length>0&&<div className="mt-2 flex flex-wrap gap-2">{activeFilters.map(key=><button key={key} onClick={()=>navigate({[key]:null})} className="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-800">{labels[key]}: {params.get(key)} ×</button>)}<button onClick={clear} className="text-xs font-bold text-blue-700">Clear all</button></div>}</div><div className="hidden lg:block"><Sort value={params.get('sort')??'recommended'} change={value=>navigate({sort:value})}/></div></div>
 <div aria-live="polite" aria-busy={loading}>{loading?<Skeletons/>:error?<State title="Supplier directory is temporarily unavailable." action="Retry" onClick={load}/>:data.items.length===0?<State title="No suppliers match these filters." action="Clear filters" onClick={clear}/>:<div className="mt-6 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{data.items.map(supplier=><SupplierCard key={supplier.publicSlug} supplier={supplier}/>)}</div>}</div>{!loading&&!error&&data.totalPages>1&&<Pagination data={data} go={page=>navigate({page:String(page)})}/>}</section></div>
 {mobileFilters&&<div className="fixed inset-0 z-[100] bg-slate-950/60" onMouseDown={event=>event.target===event.currentTarget&&setMobileFilters(false)}><div ref={drawer} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="mobile-filter-title" className="ml-auto h-full w-full max-w-sm overflow-y-auto bg-white p-5 outline-none"><div className="flex items-center justify-between"><h2 id="mobile-filter-title" className="text-xl font-bold">Filter suppliers</h2><button onClick={()=>setMobileFilters(false)} aria-label="Close filters" className="rounded p-2 text-2xl">×</button></div><Filters values={draft} change={(key,value)=>setDraft(current=>({...current,[key]:value}))}/><div className="sticky bottom-0 mt-6 flex gap-3 border-t bg-white py-4"><button onClick={clear} className="flex-1 rounded-lg border px-4 py-3 font-bold">Clear</button><button onClick={apply} className="flex-1 rounded-lg bg-blue-700 px-4 py-3 font-bold text-white">Apply</button></div></div></div>}</div>;
}

function Filters({values,change}:{values:Record<string,string>;change:(key:string,value:string)=>void}){return <div className="mt-4 space-y-4">{filterKeys.map(key=><label key={key} className="block text-sm font-semibold">{labels[key]}<input type={key==='minOrderMax'||key==='leadTimeMax'?'number':'text'} min="0" value={values[key]} onChange={event=>change(key,event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 font-normal outline-none focus:border-blue-600 focus:ring-2 focus:ring-blue-100"/></label>)}</div>}
function Sort({value,change}:{value:string;change:(value:string)=>void}){return <label className="text-sm font-semibold">Sort <select value={value} onChange={event=>change(event.target.value)} className="ml-2 rounded-lg border bg-white px-3 py-2"><option value="recommended">Recommended</option><option value="verified">Verified first</option><option value="response">Fastest response</option><option value="minimum-order">Lowest minimum order</option><option value="lead-time">Shortest lead time</option><option value="newest">Newest</option><option value="name-asc">Company name A–Z</option><option value="name-desc">Company name Z–A</option></select></label>}
function SupplierCard({supplier:s}:{supplier:Supplier}){const categories=split(s.categories).slice(0,3),brands=split(s.brands).slice(0,3);return <article className="flex min-h-[430px] min-w-0 flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg"><Link href={`/suppliers/${encodeURIComponent(s.publicSlug)}`} className="flex h-36 items-center justify-center bg-slate-50 p-5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600"><SupplierLogo name={s.displayName} url={s.logoUrl}/></Link><div className="flex flex-1 flex-col p-5"><span className="w-fit rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-800" aria-label="Verified supplier">✓ Verified</span><h3 className="mt-3 text-xl font-bold">{s.displayName}</h3>{(s.city||s.country)&&<p className="mt-1 text-sm text-slate-500">{[s.city,s.country].filter(Boolean).join(', ')}</p>}{s.supplierType&&<p className="mt-2 text-sm font-semibold text-blue-800">{s.supplierType}</p>}{s.shortDescription&&<p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-600">{s.shortDescription}</p>}{(categories.length>0||brands.length>0)&&<div className="mt-3 flex flex-wrap gap-1.5">{[...categories,...brands].slice(0,5).map(value=><span key={value} className="rounded bg-slate-100 px-2 py-1 text-xs text-slate-700">{value}</span>)}</div>}<dl className="mt-4 grid grid-cols-2 gap-2 text-xs">{s.minimumOrder!==null&&<Info label="Minimum order" value={`${s.minimumOrderCurrency||''} ${s.minimumOrder}`.trim()}/>} {s.leadTimeMaxDays!==null&&<Info label="Lead time" value={`${s.leadTimeMinDays??0}–${s.leadTimeMaxDays} days`}/>} {s.responseTimeHours!==null&&<Info label="Response" value={`${s.responseTimeHours} hours`}/>} {s.publicProductCount>0&&<Info label="Public products" value={String(s.publicProductCount)}/>}</dl>{s.deliveryCoverage&&<p className="mt-3 line-clamp-1 text-xs text-slate-500">Delivery: {s.deliveryCoverage}</p>}<div className="mt-auto flex flex-col gap-2 pt-5 sm:flex-row"><Link href={`/suppliers/${encodeURIComponent(s.publicSlug)}`} className="inline-flex flex-1 items-center justify-center rounded-lg border border-blue-200 px-4 py-2 text-sm font-bold text-blue-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600">View Supplier</Link><SupplierRequestQuoteButton publicSlug={s.publicSlug} supplierName={s.displayName}/></div></div></article>}
function SupplierLogo({name,url}:{name:string;url:string|null}){const[failed,setFailed]=useState(false),initials=name.split(/\s+/).slice(0,2).map(word=>word[0]).join('').toUpperCase();return validImage(url)&&!failed?<img src={url!} alt={`${name} logo`} onError={()=>setFailed(true)} className="h-full w-full object-contain"/>:<span className="flex h-20 w-20 items-center justify-center rounded-2xl bg-white text-2xl font-bold text-blue-700 shadow-sm" aria-label={`${name} initials`}>{initials||'VS'}</span>}
function Info({label,value}:{label:string;value:string}){return <div><dt className="text-slate-500">{label}</dt><dd className="font-semibold text-slate-800">{value}</dd></div>}
function Skeletons(){return <div className="mt-6 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{Array.from({length:6},(_,index)=><div key={index} className="h-[430px] animate-pulse rounded-2xl border bg-white p-5"><div className="h-32 rounded-xl bg-slate-100"/><div className="mt-5 h-5 w-2/3 rounded bg-slate-100"/><div className="mt-3 h-16 rounded bg-slate-100"/></div>)}</div>}
function State({title,action,onClick}:{title:string;action:string;onClick:()=>void}){return <div className="mt-6 rounded-2xl border border-dashed bg-white p-12 text-center"><p className="text-slate-600">{title}</p><button onClick={onClick} className="mt-4 rounded-lg bg-blue-700 px-4 py-2 font-bold text-white">{action}</button></div>}
function Pagination({data,go}:{data:Result;go:(page:number)=>void}){const pages=Array.from({length:Math.min(5,data.totalPages)},(_,index)=>Math.max(1,Math.min(data.totalPages-4,data.page-2))+index).filter(page=>page<=data.totalPages);return <nav aria-label="Supplier directory pages" className="mt-8 flex flex-wrap items-center justify-center gap-2"><button disabled={data.page<=1} onClick={()=>go(data.page-1)} className="rounded border px-3 py-2 disabled:opacity-40">Previous</button>{pages.map(page=><button key={page} aria-current={page===data.page?'page':undefined} onClick={()=>go(page)} className={`rounded px-3 py-2 ${page===data.page?'bg-blue-700 text-white':'border bg-white'}`}>{page}</button>)}<button disabled={data.page>=data.totalPages} onClick={()=>go(data.page+1)} className="rounded border px-3 py-2 disabled:opacity-40">Next</button></nav>}
