import PDFDocument from 'pdfkit';
import path from 'path';
import fs from 'fs';

type Model = any;
const navy='#071b3a',blue='#1d4ed8',muted='#475569',line='#cbd5e1';
const money=(currency:string,value:number)=>`${currency} ${Number(value).toFixed(2)}`;
const displayDate=(value:string)=>new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(value)).replaceAll('/','.');
const safe=(value:unknown)=>String(value??'').replace(/[\u0000-\u001f\u007f]/g,' ').trim();

export async function renderCanonicalInvoicePdf(model:Model):Promise<Buffer>{
 return new Promise((resolve,reject)=>{
  const doc=new PDFDocument({size:'A4',margin:40,bufferPages:true,info:{Title:`Proforma Invoice ${safe(model.invoice.invoiceNumber)}`,Author:'Electron Market'}});
  const chunks:Buffer[]=[];doc.on('data',chunk=>chunks.push(Buffer.from(chunk)));doc.on('end',()=>resolve(Buffer.concat(chunks)));doc.on('error',reject);
  const pageWidth=doc.page.width,left=40,right=pageWidth-40,contentWidth=right-left;
  const logo=path.join(process.cwd(),'public','reference','web_logo_em.png');
  const header=()=>{doc.rect(0,0,pageWidth,278).fill(navy);if(fs.existsSync(logo))doc.image(logo,left,26,{fit:[58,58]});doc.fillColor('white').font('Helvetica-Bold').fontSize(18).text('Electron Market',108,30,{width:220});doc.font('Helvetica').fontSize(11).text(safe(model.issuer.legalCompanyName),108,55,{width:220});doc.font('Helvetica-Bold').fontSize(16).text(`PROFORMA INVOICE #\n${safe(model.invoice.invoiceNumber)}`,320,30,{width:right-320,align:'right'});doc.fontSize(10).fillColor('#93c5fd').text('COMPANY DETAILS',left,104);doc.fillColor('white').font('Helvetica').fontSize(9).text(`${safe(model.issuer.legalCompanyName)}\n128 City Road\nLondon, EC1V 2NX\nUnited Kingdom\nCompany House number: ${safe(model.issuer.registrationNumber)}`,left,121,{width:270,lineGap:2});doc.fillColor('#93c5fd').font('Helvetica-Bold').text('BANK DETAILS',left,191);doc.fillColor('white').font('Helvetica').text(`Account: ${safe(model.issuer.accountHolder)}\nIBAN: ${safe(model.issuer.iban)}\nSWIFT: ${safe(model.issuer.swiftBic)}\nBank address: Wise, Rue du Trône 100, 3rd floor,\nBrussels, 1050, Belgium`,left,207,{width:285,lineGap:2});doc.fillColor('#93c5fd').font('Helvetica-Bold').text('DATE',335,112,{width:215,align:'right'});doc.fillColor('white').font('Helvetica').text(displayDate(model.invoice.generatedAt),335,128,{width:215,align:'right'});doc.fillColor('#93c5fd').font('Helvetica-Bold').text('PROCUREMENT',335,158,{width:215,align:'right'});doc.fillColor('white').font('Helvetica').text(safe(model.invoice.procurementNumber),335,174,{width:215,align:'right'});doc.fillColor('#93c5fd').font('Helvetica-Bold').text('STATUS',335,204,{width:215,align:'right'});doc.fillColor('white').font('Helvetica').text(safe(model.invoice.status),335,220,{width:215,align:'right'});doc.rect(0,278,pageWidth,4).fill(blue);doc.y=302};
  const tableHeader=(y:number)=>{const widths=[235,60,60,80,80],labels=['GOODS','AMOUNT','CURRENCY','PRICE','TOTAL'];let x=left;doc.rect(left,y,contentWidth,24).fill(navy);labels.forEach((label,i)=>{doc.fillColor('white').font('Helvetica-Bold').fontSize(8).text(label,x+5,y+8,{width:widths[i]-10,align:i? 'right':'left'});x+=widths[i]});return y+24};
  const newItemsPage=()=>{doc.addPage();doc.fillColor(navy).font('Helvetica-Bold').fontSize(12).text(`Proforma Invoice ${safe(model.invoice.invoiceNumber)}`,left,28);doc.fillColor(muted).font('Helvetica').fontSize(8).text('Invoice positions - continued',left,45);doc.y=70};
  header();doc.fillColor(blue).font('Helvetica-Bold').fontSize(9).text('CUSTOMER',left,302);doc.fillColor(navy).fontSize(15).text(safe(model.customer.companyName)||'-',left,320);doc.fillColor(muted).font('Helvetica').fontSize(9).text([model.customer.billingAddress,model.customer.registrationNumber&&`Registration: ${model.customer.registrationNumber}`,model.customer.vatNumber&&`VAT: ${model.customer.vatNumber}`,model.customer.billingEmail].filter(Boolean).map(safe).join('\n'),left,343,{width:contentWidth,lineGap:2});let y=Math.max(doc.y+20,410);y=tableHeader(y);
  const widths=[235,60,60,80,80];for(const item of model.items){const goods=[item.requestedMpn,item.offeredMpn&&item.offeredMpn!==item.requestedMpn?`Offered: ${item.offeredMpn}`:null,item.description,item.manufacturer&&`Manufacturer: ${item.manufacturer}`,item.leadTimeDays!=null&&`Lead time: ${item.leadTimeDays} days`,item.condition&&`Condition: ${item.condition}`].filter(Boolean).map(safe).join('\n');const rowHeight=Math.max(38,doc.heightOfString(goods,{width:widths[0]-10})+14);if(y+rowHeight>doc.page.height-55){newItemsPage();y=tableHeader(70)}let x=left;doc.rect(left,y,contentWidth,rowHeight).strokeColor(line).stroke();const values=[goods,`${item.quantity} ${safe(item.quantityUnit)}`,safe(item.currency),`${money(item.currency,item.selectedUnitPrice)}\n${item.priceBasisQuantity} / ${safe(item.priceBasisUnit)}`,money(item.currency,item.lineTotal)];values.forEach((value,i)=>{doc.fillColor(i===0?navy:muted).font(i===0?'Helvetica':'Helvetica-Bold').fontSize(i===0?8:8).text(value,x+5,y+7,{width:widths[i]-10,align:i?'right':'left'});if(i<values.length-1)doc.moveTo(x+widths[i],y).lineTo(x+widths[i],y+rowHeight).strokeColor(line).stroke();x+=widths[i]});y+=rowHeight}
  if(y+145>doc.page.height-45){doc.addPage();y=55}doc.fillColor(muted).font('Helvetica').fontSize(10).text('Subtotal',360,y+18,{width:90,align:'right'});doc.fillColor(navy).font('Helvetica-Bold').text(money(model.invoice.currency,model.invoice.subtotal),455,y+18,{width:100,align:'right'});doc.rect(355,y+42,200,34).fill('#eff6ff');doc.fillColor(navy).fontSize(13).text('Total',370,y+53,{width:70});doc.text(money(model.invoice.currency,model.invoice.total),440,y+53,{width:100,align:'right'});doc.fillColor(muted).font('Helvetica').fontSize(9).text('Please include the Invoice number in the payment reference.',left,y+96);doc.fillColor(navy).font('Helvetica-Bold').text(`Payment reference: ${safe(model.invoice.invoiceNumber)}`,left,y+112);doc.save();doc.page.margins.bottom=0;doc.fillColor(muted).font('Helvetica').fontSize(8).text(`Electron Market - Proforma Invoice ${safe(model.invoice.invoiceNumber)}`,left,doc.page.height-25,{width:contentWidth,align:'center',lineBreak:false});doc.restore();doc.end();
 });
}
