import type{ProductCandidate,ProductFinderResponse,ProductSearchIntent,SupplierCandidate}from'./contracts.ts';import{clarificationQuestions,determineMissingSpecifications}from'./intent.ts';import{rankCandidates,scoreCandidate}from'./scoring.ts';
export type FinderTools={searchInternalProducts:(intent:ProductSearchIntent)=>Promise<Omit<ProductCandidate,'compatibility'>[]>;searchCachedProducts?:(intent:ProductSearchIntent)=>Promise<Omit<ProductCandidate,'compatibility'>[]>;searchOctopartProducts:(intent:ProductSearchIntent)=>Promise<Omit<ProductCandidate,'compatibility'>[]>;researchPublicProductSources:(intent:ProductSearchIntent,existing?:Omit<ProductCandidate,'compatibility'>[])=>Promise<Omit<ProductCandidate,'compatibility'>[]>;discoverPotentialSuppliers:(intent:ProductSearchIntent,products:ProductCandidate[])=>Promise<SupplierCandidate[]>};
export const SUFFICIENT_SCORE=85;
type FinderRuntimeConfig={candidateFirst?:boolean;minimumIdentificationCharacters?:number;confidenceThreshold?:number;maxClarificationQuestions?:number;maxCandidates?:number;maxSupplierCandidates?:number;clarificationMessage?:string;noResultsMessage?:string};
const score=(intent:ProductSearchIntent,rows:Omit<ProductCandidate,'compatibility'>[],limit=20)=>rankCandidates(rows.slice(0,limit).map(row=>({...row,compatibility:scoreCandidate(intent,row)})).filter(row=>row.compatibility.overallScore>0&&row.verificationStatus!=='rejected_conflict'));
const identity=(row:Omit<ProductCandidate,'compatibility'>)=>`${String(row.manufacturer??'').toUpperCase().replace(/[^A-Z0-9]/g,'')}:${String(row.partNumber??row.productName).toUpperCase().replace(/[^A-Z0-9]/g,'')}`;
const combine=(rows:Omit<ProductCandidate,'compatibility'>[])=>[...rows.reduce((map,row)=>{const key=identity(row),current=map.get(key);if(!current){map.set(key,row);return map}map.set(key,{...current,manufacturer:current.manufacturer??row.manufacturer,partNumber:current.partNumber??row.partNumber,category:current.category??row.category,technicalParameters:{...current.technicalParameters,...row.technicalParameters},evidenceUrls:[...new Set([...current.evidenceUrls,...row.evidenceUrls])].slice(0,24),evidenceTitles:[...new Set([...current.evidenceTitles,...row.evidenceTitles])].slice(0,24),evidenceExtracts:[...new Set([...current.evidenceExtracts,...row.evidenceExtracts])].slice(0,24),verificationStatus:current.verificationStatus==='verified_from_public_source'||row.verificationStatus==='verified_from_public_source'?'verified_from_public_source':current.verificationStatus});return map},new Map<string,Omit<ProductCandidate,'compatibility'>>()).values()];
export async function runProductFinder(intent:ProductSearchIntent,tools:FinderTools,configuration:FinderRuntimeConfig={}):Promise<ProductFinderResponse>{const limit=configuration.maxCandidates??20;intent.missingRequiredFields=determineMissingSpecifications(intent);const minimumCharacters=configuration.minimumIdentificationCharacters??12;const hasIdentification=Boolean(intent.partNumber||intent.productName||intent.category||intent.intendedFunction||intent.rawQuery.trim().length>=minimumCharacters);const important=intent.missingRequiredFields.filter(v=>!['quantity','destination country','alternatives policy'].includes(v));const needsClarification=configuration.candidateFirst? !hasIdentification : important.length>0&&!intent.partNumber;if(needsClarification){return{assistantMessage:configuration.clarificationMessage||'I need one product-identification detail before searching.',nextState:'needs_clarification',extractedIntent:intent,clarificationQuestions:clarificationQuestions(intent).filter(question=>!/quantity|deliver|country|price|shipping|incoterm|payment|freight|invoice|quotation|schedule/i.test(question)).slice(0,configuration.maxClarificationQuestions??3),productCandidates:[],sourcingProgress:{stagesExecuted:[],potentialSources:0,outreachSent:0,responsesReceived:0},permittedActions:['answer_clarification','edit_requirements']}}
 const stages=['internal','cache','octopart'];const collected=await Promise.allSettled([tools.searchInternalProducts(intent),tools.searchCachedProducts?.(intent)??Promise.resolve([]),tools.searchOctopartProducts(intent)]),initial=combine(collected.flatMap(item=>item.status==='fulfilled'?item.value:[]));
 stages.push('internet');let web:Omit<ProductCandidate,'compatibility'>[]=[];try{web=await tools.researchPublicProductSources(intent,initial)}catch{}const candidates=score(intent,combine([...initial,...web]),limit);const verified=candidates.filter(c=>c.verificationStatus!=='unverified_ai_suggestion'&&c.verificationStatus!=='rejected_conflict');if(!verified.length)return result(configuration.noResultsMessage||'No verified product was found. The session is preserved for manual Procurement research.','sourcing_request_ready',intent,candidates,stages,[]);
 stages.push('supplier_discovery');const suppliers=(await tools.discoverPotentialSuppliers(intent,verified)).slice(0,configuration.maxSupplierCandidates??10);return result(`${suppliers.length} potential supply source${suppliers.length===1?' was':'s were'} identified. Supplier identities remain confidential.`,suppliers.length?'preparing_outreach':'sourcing_request_ready',intent,candidates,stages,suppliers)}
function result(message:string,state:ProductFinderResponse['nextState'],intent:ProductSearchIntent,candidates:ProductCandidate[],stages:string[],suppliers:SupplierCandidate[]):ProductFinderResponse{return{assistantMessage:message,nextState:state,extractedIntent:intent,clarificationQuestions:[],productCandidates:candidates,sourcingProgress:{stagesExecuted:stages,potentialSources:suppliers.length,outreachSent:0,responsesReceived:0},permittedActions:state==='preparing_outreach'?['request_admin_approval','change_requirements']:['select_product','compare','search_alternatives','start_sourcing_request']}}
