'use client';
import {useCallback,useEffect,useState} from 'react';
import {useParams,useRouter} from 'next/navigation';
import {AdminHeader,AdminShell,SectionCard,humanize} from '../../_components/detailShared';
import SupplierContactsReview from './SupplierContactsReview';
import PublicProfileReview from './PublicProfileReview';
const field='w-full rounded-md border border-slate-300 px-3 py-2 text-sm';
const checks=['company_registration_reviewed','company_identity_confirmed','primary_contact_verified','compliance_review_completed'];
const profileFields=['company_name','business_registration_number','tax_vat_number','country_name','legal_address','office_address','website','company_phone','company_email','company_description','product_categories_text','years_in_business','employee_count','regions_served','delivery_countries','preferred_currencies','logo_url','cover_image_url','admin_notes'];
const call=async(url:string,options?:RequestInit)=>{const r=await fetch(url,options),b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'Request failed.');return b};

export default function Page(){const routeId=useParams<{id:string}>().id,router=useRouter(),[data,setData]=useState<any>(),[tab,setTab]=useState('company'),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[promote,setPromote]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const body=await call(`/api/admin/suppliers/${routeId}`,{cache:'no-store'});setData(body);if(body.canonicalSupplierId!==routeId)router.replace(`/admin/suppliers/${body.canonicalSupplierId}`)}catch(e){setError(e instanceof Error?e.message:'Supplier could not be loaded.')}finally{setLoading(false)}},[routeId,router]);useEffect(()=>{load()},[load]);
 const change=(key:string,value:any)=>setData((d:any)=>({...d,profile:{...d.profile,[key]:value}}));
 const save=async(status?:string)=>{setSaving(true);try{const b=await call(`/api/admin/suppliers/${data.canonicalSupplierId}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({...data.profile,...(status?{verification_status:status}:{})})});setData((d:any)=>({...d,profile:b.profile}));setSuccess('Supplier review saved.')}catch(e){setError(e instanceof Error?e.message:'Save failed.')}finally{setSaving(false)}};
 const saveProduct=async(row:any,update:any)=>{setSaving(true);try{const b=await call(`/api/admin/suppliers/${data.canonicalSupplierId}/products/${row.product_id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({...row,...update})});setData((d:any)=>({...d,structuredProducts:d.structuredProducts.map((x:any)=>x.product_id===b.product.product_id?b.product:x),products:d.products.map((x:any)=>x.product_id===b.product.product_id?b.product:x)}));setSuccess('Product updated.')}catch(e){setError(e instanceof Error?e.message:'Product update failed.')}finally{setSaving(false)}};
 const importUpload=async(uploadId:string)=>{setSaving(true);try{const b=await call(`/api/admin/suppliers/${data.canonicalSupplierId}/uploads/${uploadId}/import`,{method:'POST'});setSuccess(b.message);await load();setTab('products')}catch(e){setError(e instanceof Error?e.message:'Import failed.')}finally{setSaving(false)}};
 const promoteNow=async()=>{setPromote(false);setSaving(true);try{await call(`/api/admin/suppliers/${data.canonicalSupplierId}/promote-to-verified`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({settings:{is_public:true}})});await load();setSuccess('Supplier promoted to Verified Supplier.')}catch(e){setError(e instanceof Error?e.message:'Promotion failed.')}finally{setSaving(false)}};
 if(loading)return <AdminShell><div className="p-8">Loading supplier review…</div></AdminShell>;if(!data)return <AdminShell><div className="p-8 text-red-700">{error}</div></AdminShell>;const p=data.profile,eligible=p.verification_status==='approved'&&Boolean(p.public_display_name||p.company_name);return <AdminShell><AdminHeader eyebrow="Supply HUB Review" title={p.company_name||'Supplier review'} subtitle={`Canonical supplier ${data.canonicalSupplierId}`} status={p.verification_status}/><div className="mx-auto max-w-7xl px-4 py-6">{error&&<Notice red>{error}</Notice>}{success&&<Notice>{success}</Notice>}<div className="mb-5 flex gap-2 overflow-x-auto">{['company','contacts','products','documents','verification','public','administration'].map(x=><button key={x} onClick={()=>setTab(x)} className={`whitespace-nowrap rounded-md px-4 py-2 text-sm font-bold ${tab===x?'bg-blue-700 text-white':'border bg-white'}`}>{humanize(x)}</button>)}</div>
 {tab==='company'&&<SectionCard title="Registered company information"><Editor fields={profileFields} data={p} change={change}/></SectionCard>}
 {tab==='contacts'&&<SectionCard title="Private contacts and authorized emails"><SupplierContactsReview supplierId={data.canonicalSupplierId} initialContacts={data.contacts} initialEmails={data.authorizedEmails} onMessage={(kind:string,message:string)=>kind==='error'?setError(message):setSuccess(message)}/></SectionCard>}
 {tab==='products'&&<Products data={data} saving={saving} importUpload={importUpload} saveProduct={saveProduct}/>} 
 {tab==='documents'&&<SectionCard title="Registration documents"><Simple heads={['Document','Type','File','Status','Uploaded']} rows={data.documents.map((d:any)=>[d.document_title,d.document_type,d.file_name,d.document_status,d.uploaded_at?new Date(d.uploaded_at).toLocaleDateString():'—'])}/></SectionCard>}
 {tab==='verification'&&<SectionCard title="Verification checklist"><div className="grid gap-3 sm:grid-cols-2">{checks.map(k=><label key={k} className="flex gap-2 rounded border p-3"><input type="checkbox" checked={!!p.verification_checklist?.[k]} onChange={e=>change('verification_checklist',{...p.verification_checklist,[k]:e.target.checked})}/>{humanize(k)}</label>)}</div><textarea className={`${field} mt-4`} value={p.decision_reason||''} onChange={e=>change('decision_reason',e.target.value)}/><div className="mt-4 flex flex-wrap gap-2"><Action onClick={()=>save('in_review')}>Start review</Action><Action onClick={()=>save('needs_update')}>Request information</Action><Action onClick={()=>save('approved')}>Approve supplier</Action><Action onClick={()=>save('rejected')}>Reject supplier</Action></div></SectionCard>}
 {tab==='public'&&<SectionCard title="Public Supplier Profile Review"><PublicProfileReview canonicalId={data.canonicalSupplierId} profile={p} snapshot={data.verifiedSupplier} onReload={load}/></SectionCard>}
 {tab==='administration'&&<SectionCard title="Administration"><p>Verification version: {p.verification_version}</p><p className="mt-2">Products count means active structured products; uploads use the separate counts shown in Products.</p>{!data.verifiedSupplier&&<div className="mt-5"><Action primary onClick={()=>setPromote(true)} disabled={!eligible}>Promote to Verified Supplier</Action>{!eligible&&<ul className="mt-3 list-disc pl-5 text-sm text-amber-800">{p.verification_status!=='approved'&&<li>Approved verification status is required.</li>}{!(p.public_display_name||p.company_name)&&<li>A company/public display name is required.</li>}</ul>}{data.counts.approvedProductCount===0&&<p className="mt-3 text-sm text-amber-800">No approved public products will currently appear on this supplier profile.</p>}</div>}<h3 className="mt-6 font-bold">Audit history</h3>{data.auditLog.map((a:any)=><div key={a.id} className="border-b py-2 text-sm">{new Date(a.created_at).toLocaleString()} — {humanize(a.action)}</div>)}</SectionCard>}
 <div className="mt-5 flex justify-end"><Action primary onClick={()=>save()}>{saving?'Saving…':'Save changes'}</Action></div></div>{promote&&<Confirm cancel={()=>setPromote(false)} confirm={promoteNow}/>}</AdminShell>}

function Products({data,saving,importUpload,saveProduct}:any){const[selected,setSelected]=useState(data.productUploads[0]?.id||'');const rows=data.uploadedItems.filter((x:any)=>x.upload_id===selected);return <div className="space-y-6"><SectionCard title="A. Uploaded product lists"><Simple heads={['Upload','Document','Original filename','Created','Rows','Valid','Errors','Status','AI','Mapping','Items','Actions']} rows={data.productUploads.map((u:any)=>[u.upload_number,u.document_name,u.original_file_name,new Date(u.created_at).toLocaleDateString(),u.total_rows,u.valid_rows,u.error_rows,humanize(u.status),humanize(u.ai_processing_status),humanize(u.column_mapping_status),data.uploadedItems.filter((x:any)=>x.upload_id===u.id).length,<div key={u.id} className="flex gap-2"><button className="text-blue-700" onClick={()=>setSelected(u.id)}>View products</button><button disabled={saving} className="text-emerald-700" onClick={()=>importUpload(u.id)}>Import valid products</button></div>])}/></SectionCard><SectionCard title="B. Products from uploaded lists">{selected?<Simple heads={['Row','Part number','Manufacturer','SKU','Product','Qty','MOQ','Price','Lead time','Validation','Import']} rows={rows.map((r:any)=>[r.row_number,r.part_number,r.manufacturer,r.supplier_sku,r.product_name,r.available_quantity,r.moq,r.unit_price!=null?`${r.unit_price} ${r.currency||''}`:'—',r.lead_time,humanize(r.validation_status),r.created_product_id?'Imported':humanize(r.import_status)])}/>:<p className="p-4 text-slate-500">Select an uploaded list.</p>}</SectionCard><SectionCard title="C. Structured supplier products"><Simple heads={['Product','Brand','Part number','Category','Review','Active','Public','Actions']} rows={data.structuredProducts.map((r:any)=>[r.product_name,r.brand_manufacturer,r.part_number_mpn,r.category||r.product_type,humanize(r.review_status),r.product_status==='active'?'Active':'Inactive',r.is_public?'Published':'Private',<div key={r.product_id} className="flex gap-2"><button onClick={()=>saveProduct(r,{review_status:'approved',is_public:false})}>Approve</button><button className="text-emerald-700" onClick={()=>saveProduct(r,{review_status:'approved',product_status:'active',is_public:true})}>Publish</button><button onClick={()=>saveProduct(r,{review_status:'inactive',product_status:'inactive',is_public:false})}>Deactivate</button><button className="text-red-700" onClick={()=>saveProduct(r,{review_status:'rejected',is_public:false,review_reason:'Rejected during Admin review'})}>Reject</button></div>])} empty="No structured products are linked to this supplier."/></SectionCard></div>}
function Editor({fields,data,change}:any){return <div className="grid gap-4 sm:grid-cols-2">{fields.map((k:string)=><label key={k}><span className="text-xs font-bold uppercase text-slate-500">{humanize(k)}</span>{k.includes('description')||k==='admin_notes'?<textarea className={field} value={data[k]??''} onChange={e=>change(k,e.target.value)}/>:<input className={field} value={data[k]??''} onChange={e=>change(k,e.target.value)}/>}</label>)}</div>}
function Simple({heads,rows,empty='No records found.'}:any){return <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead><tr>{heads.map((h:string)=><th key={h} className="border-b p-3">{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r:any[],i:number)=><tr key={i}>{r.map((v,j)=><td key={j} className="border-b p-3">{v??'—'}</td>)}</tr>):<tr><td colSpan={heads.length} className="p-8 text-center text-slate-500">{empty}</td></tr>}</tbody></table></div>}
function Action({children,onClick,primary=false,disabled=false}:any){return <button type="button" disabled={disabled} onClick={onClick} className={`rounded-md border px-4 py-2 text-sm font-bold disabled:cursor-not-allowed disabled:opacity-50 ${primary?'bg-indigo-900 text-white':'bg-white text-blue-800'}`}>{children}</button>}
function Notice({children,red=false}:any){return <div className={`mb-4 rounded p-3 ${red?'bg-red-50 text-red-700':'bg-emerald-50 text-emerald-700'}`}>{children}</div>}
function Confirm({cancel,confirm}:any){return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/70 p-4"><div className="max-w-lg rounded-xl bg-white p-6"><h2 className="text-xl font-bold">Promote to Verified Supplier?</h2><p className="mt-3 text-sm text-slate-600">This creates or updates one public snapshot linked to the canonical supplier.</p><div className="mt-6 flex justify-end gap-2"><Action onClick={cancel}>Cancel</Action><Action primary onClick={confirm}>Promote</Action></div></div></div>}
