'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {derivePublicProfileCompletion,mapSupplierProfile,mapVerifiedSupplierPublic,missingRequiredPublicProfileFields} from '../../../../lib/suppliers/profile-contract';

const labels:Record<string,string>={publicDisplayName:'Public display name',publicShortDescription:'Short description',publicDetailedDescription:'Full description',country:'Country',city:'City',supplierType:'Supplier type',website:'Website',logoUrl:'Logo',coverImageUrl:'Cover image',categories:'Categories',brands:'Brands',supportedLanguages:'Languages',employeeCount:'Employee count',minimumOrderValue:'Minimum order',typicalLeadTimeMinDays:'Lead time minimum',typicalLeadTimeMaxDays:'Lead time maximum',responseTimeHours:'Response time',publicIncoterms:'Incoterms',preferredCurrencies:'Currencies',deliveryCountries:'Delivery countries',regionsServed:'Delivery regions',manufacturingCapabilities:'Manufacturing',engineeringCapabilities:'Engineering',testingCapabilities:'Testing',qualityControlCapabilities:'Quality control',customSourcingCapabilities:'Custom sourcing',additionalCapabilities:'Additional capabilities',publicPaymentTerms:'Public payment terms'};
const shown=(v:unknown)=>Array.isArray(v)?v.join(', '):v===null||v===''?'—':String(v);
const call=async(id:string,payload:unknown)=>{const r=await fetch(`/api/admin/suppliers/${id}/public-profile`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'Action failed.');return b};

export default function PublicProfileReview({canonicalId,profile,snapshot,onReload}:{canonicalId:string;profile:any;snapshot:any;onReload:()=>Promise<void>}){
 const draft=useMemo(()=>mapSupplierProfile(profile),[profile]),approved=useMemo(()=>mapVerifiedSupplierPublic(snapshot||{}),[snapshot]),missing=missingRequiredPublicProfileFields(draft);
 const[preview,setPreview]=useState(false),[reason,setReason]=useState(''),[notes,setNotes]=useState(''),[busy,setBusy]=useState(''),[message,setMessage]=useState('');
 const[publication,setPublication]=useState(()=>({is_active:Boolean(snapshot?.is_active),is_public:Boolean(snapshot?.is_public),show_public_website:Boolean(snapshot?.show_public_website),show_on_homepage:Boolean(snapshot?.show_on_homepage),public_directory_sort_order:snapshot?.public_directory_sort_order??0,homepage_sort_order:snapshot?.homepage_sort_order??0}));const previewButton=useRef<HTMLButtonElement>(null),dialog=useRef<HTMLDivElement>(null);
 useEffect(()=>setPublication({is_active:Boolean(snapshot?.is_active),is_public:Boolean(snapshot?.is_public),show_public_website:Boolean(snapshot?.show_public_website),show_on_homepage:Boolean(snapshot?.show_on_homepage),public_directory_sort_order:snapshot?.public_directory_sort_order??0,homepage_sort_order:snapshot?.homepage_sort_order??0}),[snapshot]);
 useEffect(()=>{if(!preview)return;const previous=document.activeElement as HTMLElement;dialog.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setPreview(false);if(e.key==='Tab'){const nodes=dialog.current?.querySelectorAll<HTMLElement>('button,[href],[tabindex]:not([tabindex="-1"])');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();previewButton.current?.focus()}},[preview]);
 const act=async(action:string,extra={})=>{setBusy(action);setMessage('');try{await call(canonicalId,{action,...extra});setMessage('Action completed successfully.');await onReload()}catch(e){setMessage(e instanceof Error?e.message:'Action failed.')}finally{setBusy('')}};
 const savePublication=()=>act('publication',publication);
 return <div className="space-y-6"><div className="rounded-lg border bg-slate-50 p-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Status" value={profile.public_profile_status}/><Metric label="Completion" value={`${derivePublicProfileCompletion(draft)}%`}/><Metric label="Submitted" value={profile.pending_review_at?new Date(profile.pending_review_at).toLocaleString():'Not submitted'}/><Metric label="Last updated" value={profile.updated_at?new Date(profile.updated_at).toLocaleString():'—'}/></div>{missing.length>0&&<p className="mt-3 text-sm text-amber-800">Missing recommended fields: {missing.join(', ')}</p>}<p className="mt-2 text-sm">Canonical supplier: linked · Approved snapshot: {snapshot?'available':'not yet created'} · Directory: {snapshot?.show_public_website?'enabled':'disabled'} · Homepage: {snapshot?.show_on_homepage?'enabled':'disabled'}</p></div>
 <div className="grid gap-4 lg:grid-cols-2"><h3 className="font-bold lg:col-span-2">Supplier draft compared with current approved snapshot</h3>{Object.keys(labels).map(key=>{const left=(draft as any)[key],right=(approved as any)[key],state=JSON.stringify(left)===JSON.stringify(right)?'Unchanged':!shown(right)||shown(right)==='—'?'New':shown(left)==='—'?'Removed':'Changed';return <div key={key} className="contents"><div className="rounded border p-3"><span className="text-xs font-bold uppercase text-blue-700">{labels[key]} · {state}</span><p className="mt-1 whitespace-pre-wrap text-sm">{shown(left)}</p></div><div className="rounded border bg-slate-50 p-3"><span className="text-xs font-bold uppercase text-slate-500">Current approved</span><p className="mt-1 whitespace-pre-wrap text-sm">{shown(right)}</p></div></div>})}</div>
 {message&&<div role="status" className="rounded border bg-blue-50 p-3 text-sm">{message}</div>}<div className="flex flex-wrap gap-2"><button ref={previewButton} onClick={()=>setPreview(true)} className="rounded border px-4 py-2 font-bold">Preview proposed profile</button><button disabled={busy!==''||profile.public_profile_status!=='pending_review'} onClick={()=>act('approve')} className="rounded bg-emerald-700 px-4 py-2 font-bold text-white disabled:opacity-40">{busy==='approve'?'Approving…':'Approve public profile'}</button><button disabled={busy!==''||profile.public_profile_status!=='pending_review'||reason.trim().length<3} onClick={()=>act('reject',{reason,internalNotes:notes})} className="rounded bg-red-700 px-4 py-2 font-bold text-white disabled:opacity-40">Reject public profile</button>{profile.public_profile_status==='suspended'?<button onClick={()=>act('restore')} className="rounded border px-4 py-2 font-bold">Restore profile</button>:<button disabled={!['pending_review','approved'].includes(profile.public_profile_status)} onClick={()=>confirm('Suspend this public profile and disable all visibility?')&&act('suspend')} className="rounded border px-4 py-2 font-bold">Suspend profile</button>}</div>
 <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Supplier-visible rejection reason<textarea value={reason} onChange={e=>setReason(e.target.value)} className="mt-1 min-h-24 w-full rounded border p-2"/></label><label className="text-sm font-bold">Internal Admin notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} className="mt-1 min-h-24 w-full rounded border p-2"/><span className="block text-xs font-normal text-slate-500">Private; never copied to the approved snapshot.</span></label></div>
 {snapshot&&<div className="rounded-lg border p-4"><h3 className="font-bold">Publication Controls</h3><p className="mb-3 text-sm text-slate-500">Homepage requires Active, Public, and Directory eligibility. Content approval does not change these controls.</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{([['is_active','Active'],['is_public','Public'],['show_public_website','Show in Directory'],['show_on_homepage','Show on Homepage']] as const).map(([key,label])=><label key={key} className="flex gap-2"><input type="checkbox" checked={publication[key]} onChange={e=>setPublication(current=>({...current,[key]:e.target.checked}))}/>{label}</label>)}<label>Directory sort order<input type="number" value={publication.public_directory_sort_order} onChange={e=>setPublication(current=>({...current,public_directory_sort_order:Number(e.target.value)}))} className="block w-full rounded border p-2"/></label><label>Homepage sort order<input type="number" value={publication.homepage_sort_order} onChange={e=>setPublication(current=>({...current,homepage_sort_order:Number(e.target.value)}))} className="block w-full rounded border p-2"/></label></div><button disabled={busy!==''} onClick={savePublication} className="mt-4 rounded bg-indigo-900 px-4 py-2 font-bold text-white">Save publication controls</button></div>}
 {preview&&<div className="fixed inset-0 z-[120] flex items-center justify-center bg-slate-950/70 p-4" onMouseDown={e=>e.target===e.currentTarget&&setPreview(false)}><div ref={dialog} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="proposed-profile-title" className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-xl bg-white p-6 outline-none"><div className="flex justify-between"><h2 id="proposed-profile-title" className="text-xl font-bold">Preview proposed public profile</h2><button onClick={()=>setPreview(false)} aria-label="Close preview">✕</button></div><div className="mt-5 space-y-4">{Object.keys(labels).filter(key=>shown((draft as any)[key])!=='—').map(key=><div key={key}><h3 className="text-sm font-bold text-slate-500">{labels[key]}</h3><p className="whitespace-pre-wrap">{shown((draft as any)[key])}</p></div>)}</div><button onClick={()=>setPreview(false)} className="mt-6 rounded border px-4 py-2 font-bold">Close</button></div></div>}</div>;
}
function Metric({label,value}:{label:string;value:string}){return <div><span className="block text-xs font-bold uppercase text-slate-500">{label}</span><span className="text-sm font-semibold">{value}</span></div>}
