import{notFound}from'next/navigation';import EntityDetailLayout from'../../components/details/EntityDetailLayout';import RelatedProductsState from'../../components/details/RelatedProductsState';import{getListingUser}from'../../../lib/product-listings';import{createAdminClient}from'../../../lib/supabase/admin';
export const dynamic='force-dynamic';
export default async function Page({params}:{params:Promise<{supplierId:string}>}){
 const slug=decodeURIComponent((await params).supplierId).trim();if(!slug||slug.length>180)notFound();const database=createAdminClient();if(!database)throw new Error('Supplier details are temporarily unavailable.');
 const supplier=await database.from('verified_supplier').select('supplier_id,canonical_supplier_id,name,pic,delivery_product,public_display_name,public_short_description,public_detailed_description,public_country,public_city,public_categories,public_brands,show_external_website,public_website_url').eq('public_slug',slug).eq('show_public_website',true).eq('is_public',true).eq('is_active',true).maybeSingle();if(!supplier.data||!supplier.data.canonical_supplier_id)notFound();
 const canonical=await database.from('suppliers').select('supplier_id').eq('supplier_id',supplier.data.canonical_supplier_id).eq('verified_supplier',true).eq('supplier_status','active').maybeSingle();if(!canonical.data)notFound();
 const products=supplier.data.canonical_supplier_id?await database.from('products').select('product_id,product_name,brand_manufacturer,part_number_mpn,category,product_type,short_description,main_image_url,moq_quantity,lead_time,availability,condition').eq('supplier_id',supplier.data.canonical_supplier_id).eq('is_public',true).eq('review_status','approved').eq('product_status','active').order('public_sort_order').order('product_name'):{data:[]};const name=supplier.data.public_display_name||supplier.data.name||'Verified Supplier';
 return <EntityDetailLayout entityType="Supplier" title={name} subtitle={supplier.data.public_short_description||supplier.data.delivery_product} description={supplier.data.public_detailed_description} image={supplier.data.pic} badges={['Verified Supplier']} information={[{label:'Country',value:supplier.data.public_country},{label:'City',value:supplier.data.public_city},{label:'Product categories',value:supplier.data.public_categories},{label:'Brands / manufacturers',value:supplier.data.public_brands},{label:'Specialization',value:supplier.data.delivery_product},{label:'Website',value:supplier.data.show_external_website?supplier.data.public_website_url:null}]} user={await getListingUser()}><section className="mt-6"><h2 className="text-2xl font-bold">Products supplied</h2>{products.data?.length?<div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.data.map((p:any)=><article key={p.product_id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex h-44 items-center justify-center bg-slate-50 p-5">{p.main_image_url?<img src={p.main_image_url} alt="" className="h-full w-full object-contain"/>:<span className="text-2xl font-bold text-blue-700">{String(p.product_name||'PR').slice(0,2)}</span>}</div><div className="p-5"><span className="text-xs font-bold uppercase text-blue-700">{p.category||p.product_type||'Component'}</span><h3 className="mt-2 text-lg font-bold">{p.product_name}</h3>{p.brand_manufacturer&&<p className="mt-1 text-sm text-slate-500">{p.brand_manufacturer}</p>}{p.part_number_mpn&&<p className="mt-2 font-mono text-sm">{p.part_number_mpn}</p>}{p.short_description&&<p className="mt-3 text-sm leading-6 text-slate-600">{p.short_description}</p>}<dl className="mt-4 grid grid-cols-2 gap-2 text-xs"><div><dt className="text-slate-500">MOQ</dt><dd>{p.moq_quantity||'—'}</dd></div><div><dt className="text-slate-500">Lead time</dt><dd>{p.lead_time||'—'}</dd></div></dl><a href="/create-request" className="mt-5 inline-flex rounded-md bg-blue-600 px-4 py-2 text-sm font-bold text-white">Ask for availability</a></div></article>)}</div>:<RelatedProductsState title="Products from this supplier" message="No approved public products are currently available."/>}</section></EntityDetailLayout>;
}
