'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';

const tabs=['Summary','Message','Positions','Attachments','Processing'] as const;
type Tab=typeof tabs[number];
const format=(value:unknown)=>value===null||value===undefined||value===''?'—':String(value).replaceAll('_',' ');
const date=(value:unknown)=>value?new Date(String(value)).toLocaleString():'—';
const percent=(value:unknown)=>value===null||value===undefined?'—':`${Math.round(Number(value)*100)}%`;
const size=(bytes:unknown)=>{const number=Number(bytes);if(!Number.isFinite(number))return '—';if(number<1024)return `${number} B`;if(number<1048576)return `${(number/1024).toFixed(1)} KB`;return `${(number/1048576).toFixed(1)} MB`};

export default function MessageDetailModal({messageId,onClose,onReprocess}:{messageId:string;onClose:()=>void;onReprocess:(messageId:string)=>Promise<void>}){
 const[data,setData]=useState<any>(null),[tab,setTab]=useState<Tab>('Summary'),[bodyMode,setBodyMode]=useState<'plain'|'html'>('plain'),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false);
 const load=async()=>{setLoading(true);setError('');try{const response=await fetch(`/api/admin/supplier-inbox/${encodeURIComponent(messageId)}`,{cache:'no-store'}),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.message||body.error||'Message could not be loaded.');setData(body)}catch(e){setError(e instanceof Error?e.message:'Message could not be loaded.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[messageId]);useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose()};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[onClose]);
 const reprocess=async()=>{setBusy(true);try{await onReprocess(messageId);await load()}catch(e){setError(e instanceof Error?e.message:'Message could not be reprocessed.')}finally{setBusy(false)}};
 return <div className="fixed inset-0 z-[120] flex items-center justify-center bg-slate-950/75 p-0 sm:p-4" role="dialog" aria-modal="true" aria-labelledby="message-detail-title" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><div className="flex h-full w-full flex-col overflow-hidden bg-slate-100 shadow-2xl sm:h-auto sm:max-h-[90vh] sm:w-[min(1200px,94vw)] sm:rounded-2xl">
  <header className="flex items-start justify-between gap-4 bg-gradient-to-r from-slate-950 to-blue-950 px-5 py-4 text-white"><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-widest text-cyan-300">Supplier email</p><h2 id="message-detail-title" className="mt-1 truncate text-xl font-bold">{data?.email?.procurementNumber||data?.email?.subject||'Message details'}</h2>{data&&<p className="mt-1 truncate text-sm text-blue-100">{data.email.subject||'(no subject)'}</p>}</div><button onClick={onClose} className="rounded-lg border border-white/40 px-3 py-2 text-sm font-bold hover:bg-blue-100 hover:text-slate-950">Close</button></header>
  {loading?<div className="grid min-h-80 place-items-center p-8 text-slate-600">Loading message details…</div>:error&&!data?<div className="grid min-h-80 place-items-center p-8"><div className="text-center"><p className="text-red-700">{error}</p><button onClick={load} className="mt-4 rounded-lg bg-blue-700 px-4 py-2 font-bold text-white">Retry</button></div></div>:data&&<>
   <div className="border-b bg-white px-5 py-4"><dl className="grid gap-x-6 gap-y-2 text-sm sm:grid-cols-2 lg:grid-cols-4"><Meta label="From" value={data.email.from}/><Meta label="To" value={data.email.to}/><Meta label="Received" value={date(data.email.receivedAt)}/><Meta label="Message ID" value={data.email.internetMessageId||data.email.providerMessageId}/><Meta label="Sender authorization" value={data.states.senderAuthorization}/><Meta label="Procurement matching" value={data.states.procurementMatching}/><Meta label="RFQ assignment" value={data.states.rfqAssignment}/><Meta label="AI processing" value={data.states.aiProcessing}/></dl></div>
   <nav className="flex gap-1 overflow-x-auto border-b bg-white px-4" aria-label="Message detail sections">{tabs.map(value=><button key={value} onClick={()=>setTab(value)} className={`whitespace-nowrap border-b-2 px-4 py-3 text-sm font-bold ${tab===value?'border-blue-700 text-blue-800':'border-transparent text-slate-500 hover:text-slate-900'}`}>{value}{value==='Positions'?` (${data.extractedItems.length})`:value==='Attachments'?` (${data.attachments.length})`:''}</button>)}</nav>
   {error&&<div className="mx-5 mt-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
   <div className="min-h-0 flex-1 overflow-y-auto p-5">
    {tab==='Summary'&&<Summary data={data}/>} {tab==='Message'&&<Message data={data} mode={bodyMode} setMode={setBodyMode}/>} {tab==='Positions'&&<Positions rows={data.extractedItems}/>} {tab==='Attachments'&&<Attachments rows={data.attachments}/>} {tab==='Processing'&&<Processing data={data}/>} 
   </div>
   <footer className="flex flex-wrap items-center gap-2 border-t bg-white px-5 py-4"><button onClick={reprocess} disabled={busy} className="rounded-lg bg-indigo-800 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{busy?'Reprocessing…':'Reprocess message'}</button>{data.actions.procurementUrl&&<Link href={data.actions.procurementUrl} className="rounded-lg border border-blue-300 px-4 py-2 text-sm font-bold text-blue-800">Open procurement order</Link>}{data.actions.rawDownloadUrl&&<a href={data.actions.rawDownloadUrl} className="rounded-lg border border-blue-300 px-4 py-2 text-sm font-bold text-blue-800">Download original .eml</a>}{data.email.procurementNumber&&<button onClick={async()=>{await navigator.clipboard.writeText(data.email.procurementNumber);setCopied(true);setTimeout(()=>setCopied(false),1500)}} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-bold">{copied?'Copied':'Copy procurement number'}</button>}<button onClick={onClose} className="ml-auto rounded-lg border border-slate-300 px-4 py-2 text-sm font-bold">Close</button></footer>
  </>}
 </div></div>;
}

function Meta({label,value}:{label:string;value:unknown}){return <div className="min-w-0"><dt className="text-xs font-bold uppercase text-slate-400">{label}</dt><dd className="truncate font-medium text-slate-800" title={String(value??'')}>{format(value)}</dd></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-bold text-slate-950">{title}</h3><div className="mt-4">{children}</div></section>}
function Summary({data}:any){const summary=data.aiSummary;return <div className="space-y-5"><Panel title="AI summary">{summary?<div className="space-y-4 text-sm text-slate-700"><p className="text-base leading-7">{summary.summary}</p><dl className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Meta label="Response type" value={summary.responseType}/><Meta label="Positions" value={`${summary.availablePositionCount} available / ${summary.positionCount} extracted`}/><Meta label="Currency" value={summary.defaultCurrency}/><Meta label="Valid until" value={summary.quoteValidUntil}/></dl>{summary.prices.length>0&&<div><h4 className="font-bold text-slate-900">Important prices</h4><div className="mt-2 flex flex-wrap gap-2">{summary.prices.map((price:any,index:number)=><span key={index} className="rounded-full bg-blue-50 px-3 py-1 text-blue-800">{price.partNumber||'Position'}: {price.amount} {price.currency||''}</span>)}</div></div>}<List title="Missing information" rows={summary.missingInformation}/><List title="Risks or ambiguities" rows={summary.risks}/><div className="rounded-lg bg-emerald-50 p-3"><strong>Recommended action:</strong> {summary.recommendedAction}</div><p className="text-xs text-slate-400">Stored AI result · {date(summary.createdAt)}{summary.modelLabel?` · ${summary.modelLabel}`:''}</p></div>:<div><p className="text-slate-600">AI summary is not available yet.</p><p className="mt-2 text-sm text-slate-500">Reprocess the message to generate the stored commercial extraction.</p></div>}</Panel><Panel title="AI analysis notes"><dl className="grid gap-3 sm:grid-cols-3"><Meta label="Parse status" value={data.aiAnalysis.parseStatus}/><Meta label="Parser" value={data.aiAnalysis.parserVersion}/><Meta label="Confidence" value={percent(data.aiAnalysis.extractionConfidence)}/></dl><List title="Parsing warnings" rows={data.aiAnalysis.warnings}/></Panel></div>}
function List({title,rows}:{title:string;rows:unknown[]}){if(!rows?.length)return null;return <div><h4 className="font-bold text-slate-900">{title}</h4><ul className="mt-2 list-disc space-y-1 pl-5">{rows.map((row,index)=><li key={index}>{String(row)}</li>)}</ul></div>}
function Message({data,mode,setMode}:any){return <Panel title="Original message"><div className="mb-4 flex gap-2"><button onClick={()=>setMode('plain')} className={`rounded-lg px-3 py-2 text-sm font-bold ${mode==='plain'?'bg-blue-700 text-white':'border bg-white'}`}>Plain text</button><button onClick={()=>setMode('html')} className={`rounded-lg px-3 py-2 text-sm font-bold ${mode==='html'?'bg-blue-700 text-white':'border bg-white'}`}>HTML preview</button>{data.actions.rawDownloadUrl&&<a href={data.actions.rawDownloadUrl} className="rounded-lg border px-3 py-2 text-sm font-bold">Raw source</a>}</div><pre className="max-h-[55vh] overflow-auto whitespace-pre-wrap break-words rounded-lg bg-slate-950 p-4 font-sans text-sm leading-6 text-slate-100">{mode==='plain'?(data.email.plainTextBody||'Plain-text body is not available.'):(data.email.htmlPreviewText||'HTML body is not available.')}</pre>{mode==='html'&&<p className="mt-3 text-xs text-slate-500">Safe text-only preview: scripts, frames, remote images, event handlers, and active HTML are not rendered.</p>}</Panel>}
function Positions({rows}:{rows:any[]}){return <Panel title="Extracted offer positions">{rows.length?<div className="overflow-x-auto"><table className="min-w-[1500px] text-left text-xs"><thead className="bg-slate-50"><tr>{['Row','Matched BOM / RFQ item','Customer part','Supplier part','Manufacturer','Offered / available','Unit price','Currency','MOQ','Lead time','Condition','Confidence','Match','Review'].map(value=><th key={value} className="border-b px-3 py-2">{value}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={row.id} className="border-b align-top"><td className="px-3 py-3">{row.row??index+1}</td><td className="px-3 py-3">{row.matchedItem?`${row.matchedItem.row_number??''} ${row.matchedItem.part_number??''}`:'Unmatched'}</td><td className="px-3 py-3">{format(row.customerPartNumber)}</td><td className="px-3 py-3">{format(row.supplierPartNumber)}</td><td className="px-3 py-3">{format(row.manufacturer)}</td><td className="px-3 py-3">{format(row.offeredQuantity)} / {format(row.availableQuantity)}</td><td className="px-3 py-3">{format(row.unitPrice)}</td><td className="px-3 py-3">{format(row.currency)}</td><td className="px-3 py-3">{format(row.moq)}</td><td className="px-3 py-3">{format(row.leadTime||row.leadTimeDays)}</td><td className="px-3 py-3">{format(row.condition)}</td><td className="px-3 py-3">AI {percent(row.extractionConfidence)}<br/>Match {percent(row.matchingConfidence)}</td><td className="px-3 py-3">{format(row.matchMethod||row.normalizationStatus)}</td><td className="px-3 py-3">{format(row.reviewStatus)}</td></tr>)}</tbody></table></div>:<p className="text-slate-600">No extracted commercial positions are available for this message.</p>}</Panel>}
function Attachments({rows}:{rows:any[]}){return <Panel title="Attachments">{rows.length?<div className="space-y-3">{rows.map(row=><div key={row.id} className="flex flex-col gap-3 rounded-lg border p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">{row.fileName}</p><p className="mt-1 text-xs text-slate-500">{format(row.mimeType)} · {size(row.sizeBytes)} · {format(row.extractionStatus)} · {row.extractedRowCount} extracted rows</p>{row.processingError&&<p className="mt-2 text-sm text-red-700">{row.processingError}</p>}</div><a href={row.downloadUrl} className="rounded-lg border border-blue-300 px-3 py-2 text-center text-sm font-bold text-blue-800">Secure download</a></div>)}</div>:<p className="text-slate-600">This message has no attachments.</p>}</Panel>}
function Processing({data}:any){return <div className="space-y-5"><Panel title="Processing history">{data.processingHistory.length?<ol className="relative ml-2 border-l border-blue-200 pl-5">{data.processingHistory.map((event:any,index:number)=><li key={`${event.label}-${event.at}-${index}`} className="mb-5 last:mb-0"><span className="absolute -ml-[25px] mt-1.5 h-2.5 w-2.5 rounded-full bg-blue-600"/><p className="font-bold text-slate-900">{event.label}</p><p className="text-xs text-slate-500">{date(event.at)}{event.status?` · ${format(event.status)}`:''}</p></li>)}</ol>:<p className="text-slate-600">No processing history is available.</p>}</Panel>{data.email.processingError&&<Panel title="Processing error"><p className="text-red-700">{data.email.processingError}</p></Panel>}</div>}
