type Database = any;
export async function inspectRfqDeletion(database:Database,rfqId:string){
 const rfq=await database.from('rfq_orders0').select('*').eq('rfq_id',rfqId).maybeSingle();if(rfq.error||!rfq.data)return {error:'RFQ not found.',status:404 as const};const row=rfq.data,chainId=row.procurement_chain_id;
 const [items,assignments,messages,responses,quotes,invoices,orders,boms,waybills,receipts]=await Promise.all([
  database.from('rfq_order_items0').select('rfq_item_id,source_bom_item_id',{count:'exact'}).eq('rfq_id',rfqId),database.from('rfq_supplier_assignments').select('assignment_id',{count:'exact'}).eq('rfq_id',rfqId),database.from('supplier_inbound_messages').select('id',{count:'exact'}).eq('rfq_id',rfqId),database.from('supplier_responses').select('id',{count:'exact'}).eq('rfq_id',rfqId),database.from('supplier_quotes0').select('quote_id',{count:'exact'}).eq('rfq_id',rfqId),database.from('procurement_invoices').select('id,invoice_status,payment_status',{count:'exact'}).or(`source_rfq_id.eq.${rfqId}${chainId?`,procurement_chain_id.eq.${chainId}`:''}`),database.from('active_orders').select('active_order_id,order_status,payment_status',{count:'exact'}).eq('rfq_id',rfqId),chainId?database.from('customer_bom_uploads').select('id,original_file_name,document_name').eq('procurement_chain_id',chainId).order('created_at').limit(1):Promise.resolve({data:[],count:0,error:null}),chainId?database.from('procurement_waybills').select('id',{count:'exact'}).eq('procurement_chain_id',chainId):Promise.resolve({data:[],count:0,error:null}),chainId?database.from('procurement_receive_orders').select('id',{count:'exact'}).eq('procurement_chain_id',chainId):Promise.resolve({data:[],count:0,error:null})
 ]);
 const bom=boms.data?.[0]??null,cameFromBom=Boolean(row.source_bom_upload_id||bom||(items.data??[]).some((x:any)=>x.source_bom_item_id));const blocked=(invoices.count??0)>0||(orders.count??0)>0||(waybills.count??0)>0||(receipts.count??0)>0;
 const runtimeSignature=String(row.order_number||'').startsWith('RT-');const classification=runtimeSignature&&!chainId?'Test / Orphaned':!chainId?'Orphaned':cameFromBom?'BOM-created':'Standard';
 return {data:{rfq:{id:row.rfq_id,procurementChainId:chainId,procurementNumber:row.procurement_number||row.order_number,customer:row.customer_company_name,status:row.rfq_status,createdAt:row.created_at},cameFromBom,sourceBom:bom|| (row.source_bom_upload_id?{id:row.source_bom_upload_id}:null),classification,dependencies:{items:items.count??0,assignments:assignments.count??0,supplierEmails:messages.count??0,supplierResponses:responses.count??0,quotes:quotes.count??0,invoices:invoices.count??0,orders:orders.count??0,waybills:waybills.count??0,receiveOrders:receipts.count??0},blocked,blockedReason:blocked?'This RFQ cannot be deleted because downstream financial, order, or shipping documents exist.':null}};
}
