export async function confirmManualOfferMatch(database:any,input:{rfqId:string;rfqItemId:string;offerItemId:string;adminId:string}){
 const [rfq,item,offer]=await Promise.all([
  database.from('rfq_orders0').select('rfq_id,procurement_chain_id,procurement_number').eq('rfq_id',input.rfqId).maybeSingle(),
  database.from('rfq_order_items0').select('rfq_item_id,rfq_id,procurement_chain_id,line_number,part_number').eq('rfq_item_id',input.rfqItemId).maybeSingle(),
  database.from('supplier_response_items').select('id,rfq_id,rfq_item_id,procurement_chain_id,supplier_id,supplier_response_id,match_method,matching_confidence,is_current,source_message_id').eq('id',input.offerItemId).maybeSingle(),
 ]);
 if(rfq.error||!rfq.data)return{error:'RFQ was not found.',status:404}as const;if(item.error||!item.data)return{error:'RFQ position was not found.',status:404}as const;if(offer.error||!offer.data)return{error:'Supplier position was not found.',status:404}as const;
 const response=await database.from('supplier_responses').select('id,rfq_id,procurement_chain_id,supplier_id').eq('id',offer.data.supplier_response_id).maybeSingle();if(response.error||!response.data)return{error:'Supplier response was not found.',status:404}as const;
 if(item.data.rfq_id!==rfq.data.rfq_id||item.data.procurement_chain_id!==rfq.data.procurement_chain_id||offer.data.procurement_chain_id!==rfq.data.procurement_chain_id||response.data.procurement_chain_id!==rfq.data.procurement_chain_id||response.data.supplier_id!==offer.data.supplier_id||response.data.rfq_id!==rfq.data.rfq_id)return{error:'Supplier position or target belongs to another procurement order.',status:422}as const;
 if(!offer.data.is_current)return{error:'An inactive supplier position cannot be matched.',status:409}as const;
 if(offer.data.rfq_item_id===item.data.rfq_item_id&&offer.data.rfq_id===rfq.data.rfq_id)return{data:{result:'already_matched',rfqItemId:item.data.rfq_item_id,lineNumber:item.data.line_number}}as const;
 if(offer.data.rfq_item_id&&offer.data.rfq_item_id!==item.data.rfq_item_id)return{error:`Supplier position is already matched to RFQ item ${offer.data.rfq_item_id}.`,status:409}as const;
 const protectedItem=await database.from('procurement_invoice_items').select('id').eq('source_supplier_response_item_id',offer.data.id).limit(1).maybeSingle();if(protectedItem.data)return{error:'An Invoice-linked supplier position cannot be remapped.',status:409}as const;
 const approved=await database.from('procurement_supplier_allocations').select('id').eq('supplier_response_item_id',offer.data.id).eq('is_active',true).limit(1).maybeSingle();if(approved.data)return{error:'An approved supplier position cannot be remapped.',status:409}as const;
 const now=new Date().toISOString(),updated=await database.from('supplier_response_items').update({rfq_id:rfq.data.rfq_id,rfq_item_id:item.data.rfq_item_id,match_method:'manual_admin',updated_at:now}).eq('id',offer.data.id).eq('is_current',true).select('id,rfq_id,rfq_item_id,match_method').single();if(updated.error)return{error:'Manual mapping could not be saved.',status:409}as const;
 const reviews=await database.from('supplier_response_match_reviews').select('id').eq('supplier_response_item_id',offer.data.id).eq('status','pending');
 if(reviews.data?.length)await database.from('supplier_response_match_reviews').update({status:'resolved',suggested_rfq_item_id:item.data.rfq_item_id,reviewed_by:input.adminId,reviewed_at:now,resolution_note:`Admin manually confirmed RFQ position ${item.data.line_number}. Previous method: ${offer.data.match_method??'unmatched'}; confidence: ${offer.data.matching_confidence??'not provided'}.`}).in('id',reviews.data.map((row:any)=>row.id));
 else await database.from('supplier_response_match_reviews').insert({procurement_chain_id:rfq.data.procurement_chain_id,message_id:offer.data.source_message_id,supplier_response_id:offer.data.supplier_response_id,supplier_response_item_id:offer.data.id,review_type:'manual_admin_mapping',status:'resolved',candidate_rfq_item_ids:[item.data.rfq_item_id],suggested_rfq_item_id:item.data.rfq_item_id,reason:'Admin manually confirmed supplier position mapping.',matching_confidence:offer.data.matching_confidence,reviewed_by:input.adminId,reviewed_at:now,resolution_note:`Mapped to RFQ position ${item.data.line_number}.`});
 return{data:{result:'matched_manual',rfqItemId:item.data.rfq_item_id,lineNumber:item.data.line_number,partNumber:item.data.part_number}}as const;
}
